java-checks/src/main/java/org/sonar/java/checks/ConstantsShouldBeStaticFinalCheck.java
java-checks/src/main/java/org/sonar/java/checks/OperatorPrecedenceCheck.java
java-checks/src/main/java/org/sonar/java/checks/UselessParenthesesCheck.java
java-checks/src/main/java/org/sonar/java/symexec/SymbolicEvaluator.java
java-checks/src/test/files/checks/ConstantsShouldBeStaticFinalCheck.java
java-squid/src/main/java/org/sonar/java/ast/parser/JavaGrammar.java
java-squid/src/main/java/org/sonar/java/ast/parser/JavaLexer.java
java-squid/src/main/java/org/sonar/java/ast/parser/TreeFactory.java
java-squid/src/main/java/org/sonar/java/model/ArrayDimensionTreeImpl.java
java-squid/src/main/java/org/sonar/java/model/expression/ArrayAccessExpressionTreeImpl.java
java-squid/src/main/java/org/sonar/java/model/expression/NewArrayTreeImpl.java
java-squid/src/main/java/org/sonar/java/resolve/TypeAndReferenceSolver.java
java-squid/src/main/java/org/sonar/java/syntaxtoken/LastSyntaxTokenFinder.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/ArrayAccessExpressionTree.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/ArrayDimensionTree.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/BaseTreeVisitor.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/NewArrayTree.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/Tree.java
java-squid/src/main/java/org/sonar/plugins/java/api/tree/TreeVisitor.java
java-squid/src/test/files/metrics/CommentsFull.java
java-squid/src/test/java/org/sonar/java/ast/parser/grammar/expressions/ExpressionTest.java
java-squid/src/test/java/org/sonar/java/model/JavaTreeModelTest.java
java-squid/src/test/java/org/sonar/java/syntaxtoken/LastSyntaxTokenFinderTest.java

Created new tree `ArrayDimensionTree`

SONARJAVA-1158 Brackets and Annotations for array dimensions

---

java-checks/src/main/java/org/sonar/java/checks/StaticMembersAccessCheck.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSonarWayProfileTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1198

SONARJAVA-1198 Rule: StaticMembersAccessCheck S2209 should be activated by default

---

java-checks/src/main/java/org/sonar/java/checks/BooleanInversionCheck.java
java-checks/src/main/java/org/sonar/java/checks/ConstantMathCheck.java
java-checks/src/main/java/org/sonar/java/checks/EnumMapCheck.java
java-checks/src/main/java/org/sonar/java/checks/EqualsArgumentTypeCheck.java
java-checks/src/main/java/org/sonar/java/checks/FileCreateTempFileCheck.java
java-checks/src/main/java/org/sonar/java/checks/IndexOfStartPositionCheck.java
java-checks/src/main/java/org/sonar/java/checks/NullDereferenceInConditionalCheck.java
java-checks/src/main/java/org/sonar/java/checks/StringConcatenationInLoopCheck.java
java-checks/src/main/java/org/sonar/java/checks/UnusedPrivateFieldCheck.java
java-checks/src/main/java/org/sonar/java/checks/UnusedReturnedDataCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/ExpressionsHelper.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1068.html
java-checks/src/test/files/checks/UnusedPrivateFieldCheck.java
java-checks/src/test/java/org/sonar/java/checks/helpers/ExpressionsHelperTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1156

SONARJAVA-1156 FP on S1068: Annotated unused private fields should be ignored

---

java-checks/src/main/java/org/sonar/java/checks/MethodWithExcessiveReturnsCheck.java
java-checks/src/test/files/checks/MethodWithExcessiveReturnsCheck.java
java-checks/src/test/files/checks/MethodWithExcessiveReturnsCheckCustom.java
java-checks/src/test/java/org/sonar/java/checks/MethodWithExcessiveReturnsCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1188

SONARJAVA-1188 S1142 FP with return statements in Lambdas

---

java-checks/src/main/java/org/sonar/java/checks/NoTestInTestClassCheck.java
java-checks/src/test/files/checks/NoTestInTestClassCheckNoClasspath.java
java-checks/src/test/java/org/sonar/java/checks/NoTestInTestClassCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/verifier/JavaCheckVerifier.java

http://jira.sonarsource.com/browse/SONARJAVA-1193

SONARJAVA-1193 FP on S2187 if semantic is not available

---

java-squid/src/main/java/org/sonar/java/model/LiteralUtils.java
java-squid/src/test/java/org/sonar/java/model/LiteralUtilsTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1200

SONARJAVA-1200 LiteralUtils should not fail on integer literals containing underscores

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/LoggersDeclarationCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1312.html
java-checks/src/test/files/checks/LoggersDeclarationCheck.java
java-checks/src/test/files/checks/LoggersDeclarationCheckCustom.java
java-checks/src/test/java/org/sonar/java/checks/LoggersDeclarationCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1191

SONARJAVA-1191S1312 should not raise issues for maven loggers

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheckAssertJ.java
java-checks/src/test/files/checks/AssertionsInTestsCheckJunit4.java
java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1187
http://jira.sonarsource.com/browse/SONARJAVA-1189

SONARJAVA-1187 and SONARJAVA-1189

---

java-checks/src/main/java/org/sonar/java/checks/ToStringUsingBoxingCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1158.html
java-checks/src/test/files/checks/ToStringUsingBoxingCheck.java
java-checks/src/test/java/org/sonar/java/checks/ToStringUsingBoxingCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1140

SONARJAVA-1140 Expand S1158 to also cover "compareTo"

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/ThreadSleepInTestsCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2925.html
java-checks/src/test/files/checks/ThreadSleepInTestsCheck.java
java-checks/src/test/java/org/sonar/java/checks/ThreadSleepInTestsCheckTest.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSonarWayProfileTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1207

SONARJAVA-1207 Rule: "Thread.sleep" should not be used in tests

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsCompletenessCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2970.html
java-checks/src/test/files/checks/AssertionsCompletenessCheck.java

http://jira.sonarsource.com/browse/SONARJAVA-1203

SONARJAVA-1203 Rule: update AssertionsCompletenessCheck (S2970) to detect incomplete AssertJ assertions

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/UnusedTestRuleCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2924.html
java-checks/src/test/files/checks/UnusedTestRuleCheck.java
java-checks/src/test/java/org/sonar/java/checks/UnusedTestRuleCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1208

SONARJAVA-1208 Rule: JUnit rules should be used

---

its/ruling/src/test/java/org/sonar/java/it/JavaRulingTest.java
java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/ServletMethodsExceptionsThrownCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1989.html
java-checks/src/test/files/checks/ServletMethodsExceptionsThrownCheck.java
java-checks/src/test/java/org/sonar/java/checks/ServletMethodsExceptionsThrownCheckTest.java
travis.sh

http://jira.sonarsource.com/browse/SONARJAVA-784

SONARJAVA-784 Rule: Exception should not be thrown from servlet methods

---

java-checks/src/main/java/org/sonar/java/checks/AvoidDESCheck.java
java-checks/src/test/files/checks/AvoidDESCheck.java

http://jira.sonarsource.com/browse/SONARJAVA-1210
This implementation handle the case of values retrieved from properties but doesn't fix the root cause of the issue, which corresponds to the evaluation of the provided argument, and would probably need CFG analysis.

SONARJAVA-1210 Handle special case of properties

---

its/plugin/projects/suppress-warnings/src/main/java/SuppressWarningsAtFieldLevel.java
its/plugin/projects/suppress-warnings/src/main/java/SuppressWarningsAtFieldLevelWithRule.java
java-squid/src/main/java/org/sonar/java/JavaFilesCache.java
java-squid/src/test/java/org/sonar/java/JavaFilesCacheTest.java
java-squid/src/test/resources/JavaFilesCacheTest.java

http://jira.sonarsource.com/browse/SONARJAVA-555

SONARJAVA-555

---

java-squid/src/main/java/org/sonar/java/resolve/FirstPass.java
java-squid/src/test/files/sym/declarations/InterfaceDeclaration.java
java-squid/src/test/java/org/sonar/java/resolve/SymbolTableTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1220

SONARJAVA-1220 Properly flag interface members during semantic analysis

---

its/ruling/src/test/resources/expected/squid-S1871.json
java-checks/src/main/java/org/sonar/java/checks/IdenticalCasesInSwitchCheck.java
java-checks/src/test/files/checks/IdenticalCasesInSwitchCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1137

SONARJAVA-1137 Add exception for empty blocks

---

java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/test/files/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/test/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheckTest.java

http://jira.sonarsource.com/browse/SONARJAVA-1190

SONARJAVA-1190

---

java-checks/src/main/java/org/sonar/java/checks/PublicStaticMutableMembersCheck.java
java-checks/src/test/files/checks/PublicStaticMutableMembersCheck.java
java-checks/src/test/java/org/sonar/java/checks/PublicStaticMutableMembersCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1209

SONARJAVA-1209 Do not raise issues when the inizializer type is unknown

---

its/ruling/src/test/resources/expected/squid-S3047.json
java-checks/src/main/java/org/sonar/java/checks/LoopsOnSameSetCheck.java
java-checks/src/test/files/checks/LoopsOnSameSetCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1217
When the iterable is an identifier raise an issue only if its owner
is a method to skip fields.
When the iterable is not an identifier raise issues only for
consecutives foreachs.

SONARJAVA-1217 Refine raised issues

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/OneClassInterfacePerFileCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1996.html
java-checks/src/test/files/checks/OneClassInterfacePerFileCheck.java
java-checks/src/test/files/checks/OneClassInterfacePerFileCheckNoncompliant.java
java-checks/src/test/java/org/sonar/java/checks/OneClassInterfacePerFileCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1249

SONARJAVA-1249 S1996 : Files should contain only one class or interface each

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/MainInServletCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2653.html
java-checks/src/test/files/checks/MainInServletCheck.java
java-checks/src/test/java/org/sonar/java/checks/MainInServletCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1245

SONARJAVA-1245 Rule S2653: Web applications should not have a "main" method

---

its/ruling/src/test/resources/guava/squid-S1258.json
java-checks/src/main/java/org/sonar/java/checks/AtLeastOneConstructorCheck.java
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1258.html
java-checks/src/test/files/checks/AtLeastOneConstructorCheck.java
java-checks/src/test/java/org/sonar/java/checks/AtLeastOneConstructorCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1248

SONARJAVA-1248 Rule S1258 : Classes with private members should have a constructor

---

java-checks/src/main/java/org/sonar/java/checks/PackageInfoCheck.java
java-checks/src/test/files/checks/packageInfo/HelloWorld.java
java-checks/src/test/files/checks/packageInfo/nopackageinfo/HelloWorld.java
java-checks/src/test/java/org/sonar/java/checks/PackageInfoCheckTest.java
java-squid/src/main/java/org/sonar/java/SonarComponents.java
java-squid/src/main/java/org/sonar/java/model/VisitorsBridge.java
java-squid/src/main/java/org/sonar/plugins/java/api/JavaFileScannerContext.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/Bridges.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/bridges/ChecksBridge.java

https://jira.sonarsource.com/browse/SONARJAVA-1251

SONARJAVA-1251 S1228 Package-Info raise false positive when analyzing a single file

---

java-checks/src/main/java/org/sonar/java/checks/helpers/JavaPropertiesHelper.java
java-checks/src/test/files/checks/DeprecatedHashAlgorithmCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1247

SONARJAVA-1247 NPE when retrieving default value of identifier

---

java-checks/src/main/java/org/sonar/java/checks/SerializableObjectInSessionCheck.java
java-checks/src/test/files/checks/SerializableObjectInSessionCheck.java
java-checks/src/test/java/org/sonar/java/checks/SerializableObjectInSessionCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1238

SONARJAVA-1238 FP on S2441: Rule should take into account autoboxing of primitive types

---

its/ruling/src/test/resources/commons-beanutils/squid-S2699.json
java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheckJunit4.java

https://jira.sonarsource.com/browse/SONARJAVA-1258

SOANRJAVA-1258 FP in S2699: when assertion calls originate from junit.framework.TestCase

---

java-surefire/src/main/java/org/sonar/plugins/surefire/data/SurefireStaxHandler.java
java-surefire/src/test/java/org/sonar/plugins/surefire/data/SurefireStaxHandlerTest.java
java-surefire/src/test/resources/org/sonar/plugins/surefire/data/SurefireStaxHandlerTest/skippedWithoutTimeAttribute.xml

https://jira.sonarsource.com/browse/SONARJAVA-1250

SONARJAVA-1250 Surefire Parser: do not try to read time attribute for skipped tests

---

java-squid/src/main/java/org/sonar/java/resolve/Resolve.java
java-squid/src/test/files/sym/references/MethodCall.java
java-squid/src/test/java/org/sonar/java/resolve/SymbolTableTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1149

SONARJAVA-1149 Incorrect resolution of overloaded variadic methods

---

java-checks/src/test/files/checks/RedundantThrowsDeclaration.java
java-checks/src/test/files/checks/ThrowsSeveralCheckedException.java
java-squid/src/main/java/org/sonar/java/resolve/JavaSymbol.java
java-squid/src/test/java/org/sonar/java/resolve/JavaSymbolTest.java
java-squid/src/test/java/org/sonar/java/resolve/JavaTypeTest.java
java-squid/src/test/java/org/sonar/java/resolve/ResolveTest.java
java-squid/src/test/java/org/sonar/java/resolve/TypeSubstitutionTest.java
java-squid/src/test/java/org/sonar/java/resolve/targets/FullyQualifiedName.java

https://jira.sonarsource.com/browse/SONARJAVA-1265

SONARJAVA-1265 TypeJavaSymbol.getFullyQualifiedName should return full qualified name for nested and anonymous classes

---

java-squid/src/main/java/org/sonar/java/resolve/Types.java
java-squid/src/test/files/sym/references/MethodCall.java
java-squid/src/test/java/org/sonar/java/resolve/Result.java
java-squid/src/test/java/org/sonar/java/resolve/SymbolTableTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1150

SONARJAVA-1150 Fix incorrect resolution of methods in generic classes

---

java-squid/pom.xml
java-squid/src/main/java/org/sonar/java/cfg/CFG.java
java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java
java-squid/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-squid/src/test/files/se/NullPointerCheck.java

Variables of forEach loop must be initialized to a new symbolic value,
unrelated to any previous ones.

SONARJAVA-1320 - Initialization of forEach loop

---

java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java
java-squid/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-squid/src/test/files/se/NullPointerCheck.java

Non-local variables generate false positive NPE when they are
initialized within method calls.

SONARJAVA-1333 - Non-local variables & local methods

---

java-checks/src/main/java/org/sonar/java/checks/ImmediateReverseBoxingCheck.java
java-checks/src/test/files/checks/ImmediateReverseBoxingCheck.java

- Also added handling of `char` primitive type.

SONARJAVA-1252 Handle classes having same name as wrapper with no parameter constructors

---

its/ruling/src/test/resources/commons-beanutils/squid-S1181.json
java-checks/src/main/java/org/sonar/java/checks/CatchOfThrowableOrErrorCheck.java
java-checks/src/test/files/checks/CatchOfThrowableOrErrorCheck.java
java-checks/src/test/java/org/sonar/java/checks/CatchOfThrowableOrErrorCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1278

SONARJAVA-1278 Rule S1181: Add exception to not raise an issue if a method call explicitly throws a Throwable

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/ClassVariableVisibilityCheck.html

https://jira.sonarsource.com/browse/SONARJAVA-1281

SOANRJAVA-1281 Update description of ClassVariableVisibilityCheck for exclusion of final fields

---

java-checks/src/main/java/org/sonar/java/checks/ClassWithOnlyStaticMethodsInstantiationCheck.java
java-checks/src/test/files/checks/ClassWithOnlyStaticMethodsInstantiationCheck.java
java-checks/src/test/java/org/sonar/java/checks/ClassWithOnlyStaticMethodsInstantiationCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1324

SONARJAVA-1324 FP on S2440: inner class with public fields should not raise issue

---

java-checks/src/main/java/org/sonar/java/checks/HardCodedCredentialsCheck.java
java-checks/src/test/files/checks/HardCodedCredentialsCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1331

SONARJAVA-1331 S2068: include 'passwd' and 'pwd' patterns

---

its/ruling/src/test/resources/commons-beanutils/squid-MethodCyclomaticComplexity.json
its/ruling/src/test/resources/guava/squid-MethodCyclomaticComplexity.json
its/ruling/src/test/resources/sonar-server/squid-MethodCyclomaticComplexity.json
java-checks/src/main/java/org/sonar/java/checks/MethodComplexityCheck.java
java-checks/src/test/files/checks/MethodComplexityNoncompliant.java

https://jira.sonarsource.com/browse/SONARJAVA-1290

SONARJAVA-1290 Add exceptions to S133 : Methods should not be too complex

---

appveyor.ps1
appveyor.yml

Test: run ruling in 1 job

---

java-checks/src/main/java/org/sonar/java/checks/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/files/checks/SerializableFieldInSerializableClassCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1266

SONARJAVA-1266 FP in S1948: Fields having unknown symbol type should not be considered as being not serializable

---

java-squid/src/main/java/org/sonar/java/JavaFilesCache.java
java-squid/src/test/java/org/sonar/java/JavaFilesCacheTest.java
java-squid/src/test/resources/JavaFilesCacheTestFile.java
java-squid/src/test/resources/JavaSuppressWarning.java

https://jira.sonarsource.com/browse/SONARJAVA-1233

SONARJAVA-1233 @SuppressWarnings : IndexOutOfBoundsException when the annotation is not java.lang.SuppressWarnings and binaries can not be resolved

---

java-checks/src/main/java/org/sonar/java/checks/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/files/checks/SerializableFieldInSerializableClassCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1341

SONARJAVA-1341 Fix ClassCastException in SerializableFieldInSerializableClassCheck (S1948)

---

java-checks/src/main/java/org/sonar/java/checks/DeadStoreCheck.java
java-checks/src/test/files/checks/DeadStoreCheckJavaLangNoFailure.java
java-checks/src/test/java/org/sonar/java/checks/DeadStoreCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1343

SONARJAVA-1343 Fix NPE in rule DeadStoreCheck (S1854) if semantic is not available

---

its/plugin/projects/squid/src/main/java/package2/Class2.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/SquidTest.java
its/plugin/tests/src/test/resources/com/sonar/it/java/SquidTest/squid-backup.xml
java-checks/src/main/java/org/sonar/java/checks/UnusedPrivateMethodCheck.java
java-checks/src/main/java/org/sonar/java/checks/UnusedProtectedMethodCheck.java
java-squid/src/main/java/org/sonar/java/SonarComponents.java

https://jira.sonarsource.com/browse/SONARJAVA-1360

SONARJAVA-1360 Fix IllegalArgumentException when BytecodeVisitor raise an issue at file level

---

java-squid/src/main/java/org/sonar/java/model/DefaultJavaFileScannerContext.java
java-squid/src/main/java/org/sonar/plugins/java/api/JavaFileScannerContext.java

https://jira.sonarsource.com/browse/SONARJAVA-1374

SONARJAVA-1374 Remove addNoSonarLines method from JavaFileScannerContext

---

its/ruling/src/test/resources/guava/squid-S00107.json
java-checks/src/main/java/org/sonar/java/checks/TooManyParameters_S00107_Check.java
java-checks/src/test/files/checks/TooManyParameters.java
java-checks/src/test/files/checks/TooManyParametersCustom.java
java-checks/src/test/java/org/sonar/java/checks/TooManyParameters_S00107_CheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1349

SONARJAVA-1349 Rule S00107 should exclude overridden methods

---

its/ruling/src/test/resources/fluent-http/squid-S2301.json
its/ruling/src/test/resources/guava/squid-S2301.json
java-checks/src/main/java/org/sonar/java/checks/SelectorMethodArgumentCheck.java
java-checks/src/test/files/checks/SelectorMethodArgumentCheck.java
java-checks/src/test/java/org/sonar/java/checks/SelectorMethodArgumentCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1345

SONARJAVA-1345 Rule: SelectorMethodArgumentCheck S2301 should exclude overridden methods

---

java-checks/src/main/java/org/sonar/java/checks/NoTestInTestClassCheck.java
java-checks/src/test/files/checks/NoTestInTestClassCheck.java

https://jira.sonarsource.com/browse/SONARJAVA-1373

SONARJAVA-1373 FP: Rule NoTestInTestClassCheck S2187 should not raise issues when TestNG Test annotation is used at class level

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheckJunit4.java
java-squid/src/main/java/org/sonar/java/model/declaration/MethodTreeImpl.java
java-squid/src/main/java/org/sonar/java/resolve/JavaSymbol.java
java-squid/src/test/java/org/sonar/java/resolve/MethodJavaSymbolTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1371

SONARJAVA-1371 FP: Rule AssertionsInTestsCheck S2699 should not raise issues for abstract methods

---

java-checks/src/main/java/org/sonar/java/checks/UselessIncrementCheck.java
java-checks/src/test/files/checks/UselessIncrementCheck.java
java-checks/src/test/java/org/sonar/java/checks/UselessIncrementCheckTest.java

https://jira.sonarsource.com/browse/SONARJAVA-1376

SONARJAVA-1376 FP S2123 Issue should not be raised on fields

---

java-squid/src/main/java/org/sonar/java/cfg/CFG.java
java-squid/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
java-squid/src/test/java/org/sonar/java/cfg/CFGTest.java

SONARJAVA-1384 - A switch statement without default case must allow for

---

java-squid/src/main/java/org/sonar/java/collections/AVLTree.java
java-squid/src/main/java/org/sonar/java/collections/PCollections.java
java-squid/src/main/java/org/sonar/java/collections/PMap.java
java-squid/src/main/java/org/sonar/java/collections/PSet.java
java-squid/src/main/java/org/sonar/java/collections/package-info.java
java-squid/src/main/java/org/sonar/java/se/CheckerDispatcher.java
java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java
java-squid/src/main/java/org/sonar/java/se/ExplodedGraph.java
java-squid/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-squid/src/main/java/org/sonar/java/se/ProgramState.java
java-squid/src/main/java/org/sonar/java/se/SymbolicValue.java
java-squid/src/test/java/org/sonar/java/collections/AVLTreeTest.java
java-squid/src/test/java/org/sonar/java/collections/PCollectionsTest.java

Done in two ways : better data structure for counting visited points and caching of hashcode for program state avoiding recomputing over and over hashcodes.

SONARJAVA-1389 Optimisation of SE by working on hashcode calls

---

java-squid/src/main/java/org/sonar/java/ast/parser/JavaGrammar.java
java-squid/src/main/java/org/sonar/java/ast/parser/TreeFactory.java
java-squid/src/test/java/org/sonar/java/ast/parser/grammar/expressions/ExpressionTest.java

This solves problem described in ticket [SONARJAVA-793](https://jira.sonarsource.com/browse/SONARJAVA-793) and most likely improves performance in general, but I didn't checked.

SONARJAVA-793

---

its/ruling/src/test/resources/sonar-server/squid-S2095.json
java-squid/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-squid/src/main/java/org/sonar/java/se/ProgramState.java
java-squid/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java
java-squid/src/test/files/se/JdbcResourcesTestFile.java
java-squid/src/test/java/org/sonar/java/se/checks/UnclosedResourcesCheckTest.java

There is room for discussion. For example, the JDBC world could be placed in a seperatly activable checker. But So far, I have no idea where such an activation can take place...

SONARJAVA-1416 - Generalization of unclosed opened resources

---

java-squid/src/main/java/org/sonar/java/se/EqualRelation.java
java-squid/src/main/java/org/sonar/java/se/NotEqualRelation.java
java-squid/src/main/java/org/sonar/java/se/ProgramState.java
java-squid/src/main/java/org/sonar/java/se/SymbolicValue.java
java-squid/src/main/java/org/sonar/java/se/SymbolicValueRelation.java
java-squid/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
java-squid/src/test/java/org/sonar/java/se/SymbolicValueRelationsTest.java

Supersedes PR SONARJAVA-1451 because it includes the refactoring for it.

SONARJAVA-1452 - Handle simple and transitive equality between symbolic values

---

java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/XmlCheckVerifier.java
java-checks-testkit/src/test/files/xml/XmlCheckVerifierSecondaries.xml
java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/XmlCheckVerifierTest.java
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/xml/struts/ActionNumberCheck.java
java-checks/src/main/java/org/sonar/java/checks/xml/struts/package-info.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3373.html
java-checks/src/test/files/checks/xml/struts/ActionNumberCheck/tooManyActionsCustom/struts-config.xml
java-checks/src/test/files/checks/xml/struts/ActionNumberCheck/tooManyActionsDefault/struts-config.xml
java-checks/src/test/files/checks/xml/struts/ActionNumberCheck/validActions/struts-config.xml
java-checks/src/test/java/org/sonar/java/checks/xml/struts/ActionNumberCheckTest.java
java-squid/src/main/java/org/sonar/java/xml/XmlCheckContext.java
java-squid/src/main/java/org/sonar/java/xml/XmlCheckContextImpl.java
java-squid/src/test/java/org/sonar/java/xml/XmlCheckContextImplTest.java

Also contains handling of secondaries and cost.

SONARJAVA-1494 RSPEC-3373 "action" mappings should not have too many "forward"

---

java-checks/src/main/java/org/sonar/java/checks/StringLiteralDuplicatedCheck.java
java-checks/src/test/files/checks/StringLiteralDuplicatedCheck.java

SONARJAVA-1231 Ignore default methods in interfaces

---

java-checks/src/main/java/org/sonar/java/checks/ServletInstanceFieldCheck.java
java-checks/src/test/files/checks/ServletInstanceFieldCheck.java
java-checks/src/test/java/org/sonar/java/checks/ServletInstanceFieldCheckTest.java

Those are often injected as singletons and therefore issue is a false positive

SONARJAVA-1550 Ignore variable annotated with @Inject

---

java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/files/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheckTest.java

Field annotated with @Inject are more often than not serializable.

SONARJAVA-1564 Exclude injected fields

---

java-checks/src/main/java/org/sonar/java/checks/EqualsNotOverridenWithCompareToCheck.java
java-checks/src/test/files/checks/EqualsNotOverridenWithCompareToCheck.java

This replaces pull request https://github.com/SonarSource/sonar-java/pull/752
Comments actioned, squashed commits and used Jira issue for all commits and pull request

SONARJAVA-1614 Handle lombok annotations generating equals() methods

---

its/plugin/projects/dit-check/pom.xml
its/plugin/projects/multi-module-project/pom.xml
its/plugin/projects/multi-module-with-findbugs/pom.xml

Update projects using sonar-maven-plugin to use latest version

---

java-frontend/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java
java-frontend/src/test/files/se/StreamResource.java
java-frontend/src/test/files/se/UnclosedResourcesCheck.java
java-frontend/src/test/java/org/sonar/java/se/checks/UnclosedResourcesCheckTest.java

Sonarjava 1478

---

java-frontend/src/main/java/org/sonar/java/se/checks/NonNullSetToNullCheck.java
java-frontend/src/test/files/se/NonNullSetToNullCheck.java

SONARJAVA-1648 - NPE on S2637 when return statement has no expression

---

java-checks/src/main/java/org/sonar/java/filters/BaseTreeVisitorIssueFilter.java

Simplify filters: No need to store results for every component

---

its/ruling/src/test/resources/guava/squid-S1698.json
java-frontend/src/main/java/org/sonar/java/resolve/DeferredType.java
java-frontend/src/main/java/org/sonar/java/resolve/Resolve.java
java-frontend/src/main/java/org/sonar/java/resolve/Symbols.java
java-frontend/src/main/java/org/sonar/java/resolve/TypeAndReferenceSolver.java
java-frontend/src/main/java/org/sonar/java/resolve/TypeSubstitution.java
java-frontend/src/main/java/org/sonar/java/resolve/TypeSubstitutionSolver.java
java-frontend/src/test/files/sym/references/GenericMethodCall.java
java-frontend/src/test/java/org/sonar/java/resolve/GenericsTest.java
java-frontend/src/test/java/org/sonar/java/resolve/SymbolTableTest.java

SONARJAVA-1581 Defer resolution of method invocation expression type

---

java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/files/checks/serialization/SerializableFieldInSerializableClassCheck.java

2nd commit rework detection of methods from `Serializable`

SONARJAVA-1680 Handle nested collections

---

java-frontend/src/main/java/org/sonar/java/resolve/TypeAndReferenceSolver.java
java-frontend/src/test/files/sym/InferedCascadedReturnType.java
java-frontend/src/test/java/org/sonar/java/resolve/SymbolTableTest.java

SONARJAVA-1740 Propagate defered type

---

its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTestSuite.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/SonarLintTest.java
java-frontend/src/main/java/org/sonar/java/SonarComponents.java
java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
java-frontend/src/test/java/org/sonar/java/ast/visitors/SyntaxHighlighterVisitorTest.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSquidSensor.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/XmlFileSensor.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSquidSensorTest.java

SONARJAVA-1739 Sample SonarLint IT

---

.travis.yml
travis.sh

use travis-utils for getting jdk8u92

---

java-checks/src/main/java/org/sonar/java/checks/unused/UnusedMethodParameterCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1172_java.html
java-checks/src/test/files/checks/unused/UnusedMethodParameterCheck.java

- Couldn't get these to run properly, I'll see what the CI results say 😇 Hm, looks like the local results weren't weird then 😃 
Methods annotated with @SuppressWarning for unchecked and rawtypes should
not cause method variables to be considered 'needed' by external systems.

SONARJAVA-1691: Reduce FN amount.

---

java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableObjectInSessionCheck.java
java-checks/src/test/files/checks/serialization/SerializableObjectInSessionCheck.java

SONARJAVA-1810 Array or Collection of Serializable objects are Serializable

---

java-frontend/src/main/java/org/sonar/java/AbstractJavaClasspath.java

SONARJAVA-1818 Improve classpath construction time

---

java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/JavaCheckVerifier.java
java-frontend/pom.xml
java-frontend/src/main/java/org/sonar/java/AbstractJavaClasspath.java
java-frontend/src/main/java/org/sonar/java/bytecode/loader/FileSystemLoader.java
java-frontend/src/main/java/org/sonar/java/bytecode/loader/JarLoader.java
java-frontend/src/test/java/org/sonar/java/bytecode/loader/SquidClassLoaderTest.java
pom.xml
sonar-java-plugin/src/main/java/org/sonar/plugins/java/CommonRulesSonarWayProfile.java

SONARJAVA-1708 Remove usage of commons-io

---

java-checks/src/main/java/org/sonar/java/checks/UndocumentedApiCheck.java
java-checks/src/test/files/checks/UndocumentedApiExclusion.java
java-checks/src/test/java/org/sonar/java/checks/UndocumentedApiCheckTest.java

The new parameters allows to switch between inclusion and exclusion mode.

SONARJAVA-1794: Add parameter to toggle UndocumentedAPI behaviour

---

its/ruling/pom.xml
its/ruling/src/test/java/org/sonar/java/it/JavaRulingTest.java
its/ruling/src/test/java/org/sonar/java/it/ProfileGenerator.java

Example:
its/ruling$ mvn test -Drules=S100,S101
```bash
mvn                                     -DskipTests=false clean test # 06 min 09 sec
mvn                       -Drules=S1068 -DskipTests=false clean test # 03 min 38 sec
mvn -Dtest='#fluent_http'               -DskipTests=false clean test # 01 min 17 sec
mvn -Dtest='#fluent_http' -Drules=S1068 -DskipTests=false clean test # 00 min 58 sec
```

SONARJAVA-1769 Add the command line option "rules" to ruling

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/UnnecessarySemicolonCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2959_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2959_java.json
java-checks/src/test/files/checks/UnnecessarySemicolonCheck.java
java-checks/src/test/java/org/sonar/java/checks/UnnecessarySemicolonCheckTest.java

SONARJAVA-1843 Rule S2959: Unnecessary semicolons should be omitted

---

java-frontend/src/main/java/org/sonar/java/matcher/MethodMatcher.java
java-frontend/src/test/files/matcher/Test.java
java-frontend/src/test/java/org/sonar/java/matcher/MethodMatcherTest.java

Increase MethodMatcher test coverage

---

its/performancing/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jacoco-previous/pom.xml
java-jacoco/pom.xml
java-maven-model/pom.xml
java-surefire/pom.xml
pom.xml
sonar-jacoco-listeners/pom.xml
sonar-java-plugin/pom.xml
travis.sh

Move to new release process (release once)

---

java-checks/src/main/java/org/sonar/java/checks/CatchUsesExceptionWithContextCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1166_java.html
java-checks/src/test/files/checks/CatchUsesExceptionWithContextCheck.java

It's the same case of NumberFormatException, ParseException and MalformedURLException.

DateTimeParseException should be an exception too

---

java-checks/src/main/java/org/sonar/java/checks/BooleanInversionCheck.java
java-checks/src/main/java/org/sonar/java/checks/ConstantMathCheck.java
java-checks/src/main/java/org/sonar/java/checks/DeadStoreCheck.java
java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
java-checks/src/main/java/org/sonar/java/checks/EnumMapCheck.java
java-checks/src/main/java/org/sonar/java/checks/EqualsArgumentTypeCheck.java
java-checks/src/main/java/org/sonar/java/checks/FileCreateTempFileCheck.java
java-checks/src/main/java/org/sonar/java/checks/IdenticalCasesInSwitchCheck.java
java-checks/src/main/java/org/sonar/java/checks/IndexOfStartPositionCheck.java
java-checks/src/main/java/org/sonar/java/checks/LoopsOnSameSetCheck.java
java-checks/src/main/java/org/sonar/java/checks/NullDereferenceInConditionalCheck.java
java-checks/src/main/java/org/sonar/java/checks/PreparedStatementAndResultSetCheck.java
java-checks/src/main/java/org/sonar/java/checks/PublicStaticMutableMembersCheck.java
java-checks/src/main/java/org/sonar/java/checks/RawByteBitwiseOperationsCheck.java
java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/main/java/org/sonar/java/checks/StringConcatenationInLoopCheck.java
java-checks/src/main/java/org/sonar/java/checks/ToStringReturningNullCheck.java
java-checks/src/main/java/org/sonar/java/checks/UselessIncrementCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/ExpressionsHelper.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedPrivateFieldCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedReturnedDataCheck.java
java-checks/src/test/files/checks/DeadStoreCheck.java
java-frontend/src/main/java/org/sonar/java/cfg/CFG.java
java-frontend/src/main/java/org/sonar/java/model/ExpressionUtils.java
java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-frontend/src/main/java/org/sonar/java/se/checks/CheckerTreeNodeVisitor.java
java-frontend/src/main/java/org/sonar/java/se/checks/DivisionByZeroCheck.java
java-frontend/src/main/java/org/sonar/java/se/checks/NonNullSetToNullCheck.java
java-frontend/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java

SONARJAVA-1896 Handle parenthesis in simple assignment expressions

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/UndocumentedApiCheck.java
java-checks/src/test/files/checks/UndocumentedApi.java
java-checks/src/test/java/org/sonar/java/checks/UndocumentedApiCheckTest.java

SONARJAVA-1807 Ignore overriding methods

---

its/ruling/src/test/resources/fluent-http/squid-S1820.json
its/ruling/src/test/resources/guava/squid-S1820.json
its/ruling/src/test/resources/java-squid/squid-S1820.json
its/ruling/src/test/resources/jdk6/squid-S1820.json
its/ruling/src/test/resources/sonar-server/squid-S1820.json
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/ClassFieldCountCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1820_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1820_java.json
java-checks/src/test/files/checks/ClassFieldCountCheck.java
java-checks/src/test/files/checks/ClassFieldCountCheck/CountOnlyPublicFields.java
java-checks/src/test/files/checks/ClassFieldCountCheck/SimpleDefaultCase.java
java-checks/src/test/files/checks/ClassFieldCountCheck/UnusualTrees.java
java-checks/src/test/java/org/sonar/java/checks/ClassFieldCountCheckTest.java

SONARJAVA-1876 Rule S1820: Classes should not have too many fields

---

java-checks/src/main/java/org/sonar/java/checks/synchronization/WriteObjectTheOnlySynchronizedMethodCheck.java

Sonarjava 1905

---

java-checks/src/main/java/org/sonar/java/checks/synchronization/DoubleCheckedLockingCheck.java
java-checks/src/test/files/checks/ClassFieldCountCheck/ClassFieldCountCheck.java
java-checks/src/test/files/checks/DoubleCheckedLockingCheck.java
java-checks/src/test/files/checks/WriteObjectTheOnlySynchronizedMethodCheck.java
java-checks/src/test/java/org/sonar/java/checks/ClassFieldCountCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/synchronization/DoubleCheckedLockingCheckTest.java

fix quality flaw: increase coverage

Increase coverage

---

java-checks/src/main/java/org/sonar/java/checks/IndentationCheck.java

SONARJAVA-1954 Rule: IndentationCheck - update parameter

SONARJAVA-1954 Rule: IndentationCheck - update parameter

---

java-frontend/src/main/java/org/sonar/java/se/ExplodedGraph.java
java-frontend/src/main/java/org/sonar/java/se/checks/SECheck.java
java-frontend/src/test/java/org/sonar/java/se/checks/SECheckTest.java

SONARJAVA-1959 Fix recursion issue

---

java-frontend/src/main/java/org/sonar/java/model/DefaultJavaFileScannerContext.java
java-frontend/src/test/java/org/sonar/java/model/DefaultJavaFileScannerContextTest.java

Multiple secondary where reported as a single flow, displaying numbered items in SQ UI.

SONARJAVA-1955 Fix reporting of multiple secondary

---

java-frontend/pom.xml
java-frontend/src/main/java/org/sonar/java/se/checks/NonNullSetToNullCheck.java
java-frontend/src/test/files/se/NonNullSetToNullCheck.java
java-frontend/src/test/java/org/sonar/java/se/JavaCheckVerifierTest.java

SONARJAVA-1977: S2637 excludes default constructors for JPA entities.

---

java-frontend/src/main/java/org/sonar/java/se/checks/LocksNotUnlockedCheck.java
java-frontend/src/main/java/org/sonar/java/se/checks/SECheck.java
java-frontend/src/test/files/se/LocksNotUnlockedCheck.java

S2222 should rely on flow reporting rather than syntax node in constraint

SONARJAVA-1960: flow reporting for S2222

---

java-frontend/src/main/java/org/sonar/java/se/checks/NullDereferenceCheck.java
java-frontend/src/test/files/se/FlowComputation.java
java-frontend/src/test/files/se/NPE_reporting.java
java-frontend/src/test/java/org/sonar/java/se/Expectations.java
java-frontend/src/test/java/org/sonar/java/se/ExpectationsParserTest.java
java-frontend/src/test/java/org/sonar/java/se/JavaCheckVerifier.java
java-frontend/src/test/java/org/sonar/java/se/JavaCheckVerifierTest.java

* Refactored Expectations.Parser to allow more robust parsing of comments in test
* added messages to the flows for NPE check

SONARJAVA-1998 NPE issue location is also item of the flow

---

its/ruling/src/test/resources/guava/squid-S2095.json
its/ruling/src/test/resources/jdk6/squid-S2095.json
its/ruling/src/test/resources/jdk6/squid-S2583.json
its/ruling/src/test/resources/sonar-server/squid-JsonWriterNotClosed.json
its/ruling/src/test/resources/sonar-server/squid-S2095.json
java-frontend/src/main/java/org/sonar/java/cfg/CFG.java
java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-frontend/src/main/java/org/sonar/java/se/MethodBehavior.java
java-frontend/src/main/java/org/sonar/java/se/MethodYield.java
java-frontend/src/main/java/org/sonar/java/se/ProgramState.java
java-frontend/src/main/java/org/sonar/java/se/constraint/ConstraintManager.java
java-frontend/src/main/java/org/sonar/java/se/symbolicvalues/SymbolicValue.java
java-frontend/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
java-frontend/src/test/files/se/LocksNotUnlockedCheck.java
java-frontend/src/test/files/se/UnclosedResourcesCheck.java
java-frontend/src/test/files/se/XProcExceptionalBranching.java
java-frontend/src/test/files/se/XProcMethodBehaviorExplicitException.java
java-frontend/src/test/files/se/XProcMethodBehaviorExplicitExceptionBranching.java
java-frontend/src/test/java/org/sonar/java/se/ExplodedGraphWalkerTest.java
java-frontend/src/test/java/org/sonar/java/se/MethodYieldTest.java
java-frontend/src/test/java/org/sonar/java/se/SymbolicExecutionVisitorTest.java

SONARJAVA-1986 Branch only to corresponding catch block

---

its/ruling/src/test/resources/jdk6/squid-S2259.json
java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java

This clearly lack some regression tests but as far as I can tell it is a real struggle to finally just try to reproduce a hash collision so ROI seems low.

SONARJAVA-2050 Guarantee order of end of execution path evaluations

---

its/ruling/src/test/resources/jdk6/squid-S1141.json
java-checks/src/main/java/org/sonar/java/checks/NestedTryCatchCheck.java
java-checks/src/test/files/checks/NestedTryCatchCheck.java

SONARJAVA-1948 handle nested classes

---

its/plugin/plugins/pom.xml
pom.xml

Fix quality flaw: reorder pom elements

---

java-frontend/src/main/java/org/sonar/java/se/ProgramPoint.java
java-frontend/src/test/java/org/sonar/java/se/SECheckTest.java

I realized something fishy in the ProgramPoint invariant check and added FIXME to investigate it later, thus change involves bit more than what was requested

SONARJAVA-2097 fix review comments

---

java-frontend/src/test/java/org/sonar/java/xml/XmlParserTest.java

I guess I should just use Linux :-)

Fix path separators in test, so it works on Windows

---

README.md

README: Fix broken links, use https

---

java-frontend/src/main/java/org/sonar/java/se/symbolicvalues/RelationState.java
java-frontend/src/main/java/org/sonar/java/se/symbolicvalues/RelationalSymbolicValue.java
java-frontend/src/test/files/se/NPE_transitive.java
java-frontend/src/test/files/se/Transitivity.java
java-frontend/src/test/java/org/sonar/java/se/symbolicvalues/RelationalSymbolicValueTest.java

- fixes SOE in elasticsearch analysis
- contains also refactoring to reuse transitive relationships between resolution and copying of constraints

SONARJAVA-2207 fix infinite recursion when resolving relations

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheckRestAssured.java
java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java

it includes: body, content, contentType, cookie, cookies, header,
headers, spec, specfication, statusCode, statusLine, time

SONARJAVA-2230 - Add restassured support for S2699

---

java-checks/src/main/java/org/sonar/java/checks/DoubleBraceInitializationCheck.java
java-checks/src/main/java/org/sonar/java/checks/SystemOutOrErrUsageCheck.java
java-checks/src/main/java/org/sonar/java/checks/WaitInSynchronizeCheck.java
java-checks/src/main/java/org/sonar/java/checks/naming/BadLocalVariableNameCheck.java
java-checks/src/test/files/checks/DoubleBraceInitializationCheck.java
java-checks/src/test/files/checks/SystemOutOrErrUsageCheck.java
java-checks/src/test/files/checks/WaitInSynchronizeCheck.java
java-checks/src/test/files/checks/naming/BadLocalVariableNameNoncompliant.java
java-frontend/src/main/java/org/sonar/java/se/checks/NullDereferenceCheck.java
java-frontend/src/test/files/JavaCheckVerifierFlows.java
java-frontend/src/test/files/JavaCheckVerifierFlowsSuperfluous.java
java-frontend/src/test/files/se/FlowComputation.java
java-frontend/src/test/files/se/FlowComputationMIT.java
java-frontend/src/test/files/se/MethodInvocationLeadingToNPE.java
java-frontend/src/test/files/se/NPE_reporting.java
java-frontend/src/test/files/se/NullDereferenceCheck.java
java-frontend/src/test/files/se/ObjectsMethodsTest.java
java-frontend/src/test/files/se/PackageAnnotationsNullable.java
java-frontend/src/test/files/se/Reproducer.java
java-frontend/src/test/files/se/SeEngineTest.java
java-frontend/src/test/files/se/XProcExceptionalBranching.java
java-frontend/src/test/files/se/XProcExceptionalBranchingReporting.java
java-frontend/src/test/files/se/XProcMethodBehaviorExplicitException.java
java-frontend/src/test/files/se/XProcReportingWithVarArgs.java
java-frontend/src/test/java/org/sonar/java/se/JavaCheckVerifierTest.java

SONARJAVA-2251 Update rules messages

---

java-checks/src/main/java/org/sonar/java/checks/spring/SpringComponentWithNonAutowiredMembersCheck.java
java-checks/src/test/files/checks/spring/SpringComponentWithNonAutowiredMembersCheck.java

* added @Resource as injection Annotation
* skipped @Inject as imho with @Inject there would be more necessary
checks, like the qualifier in the class etc.
<details>
- [x ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [x ] Unit tests are passing and you provided a unit test for your fix
- [x ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)
</details>

SONARJAVA 2219: Added addional Annotation to spring check

---

sonar-java-plugin/pom.xml

SONARJAVA-2290 Shade and minimize jar

---

java-frontend/src/main/java/org/sonar/java/model/ExpressionUtils.java
java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-frontend/src/main/java/org/sonar/java/se/FlowComputation.java
java-frontend/src/test/files/se/FlowComputation.java
java-frontend/src/test/files/se/FlowComputationCATOF.java
java-frontend/src/test/files/se/FlowComputationMIT.java
java-frontend/src/test/files/se/FlowComputationRelSV.java
java-frontend/src/test/files/se/FlowMessagesBranch.java
java-frontend/src/test/files/se/FlowMessagesParameterDeclaration.java
java-frontend/src/test/files/se/MethodInvocationLeadingToNPE.java
java-frontend/src/test/files/se/MethodInvocationLeadingToNSEE.java
java-frontend/src/test/files/se/NPE_reporting.java
java-frontend/src/test/files/se/NullDereferenceCheck.java
java-frontend/src/test/files/se/PackageAnnotationsNonNull.java
java-frontend/src/test/files/se/PackageAnnotationsNullable.java
java-frontend/src/test/files/se/XProcExceptionalBranchingReporting.java
java-frontend/src/test/files/se/XProcFlowMessages.java
java-frontend/src/test/files/se/XProcReportingWithVarArgs.java
java-frontend/src/test/java/org/sonar/java/se/checks/FlowComputationTest.java

SONARJAVA-2275 Handle flow messages "symbol 'can'/'can not' be null"

---

java-checks/src/main/java/org/sonar/java/checks/spring/SpringComponentWithNonAutowiredMembersCheck.java
java-checks/src/test/files/checks/spring/SpringComponentWithNonAutowiredMembersCheck.java

@m-g-sonar sorry fr so many pull requests, i hope this is now done correctly
Hey guys!
With my last commit i think we did miss on the `@Value` annotation. I added it with this Pull-Request, i think that is it, i checked the JSR-250 and spring annotation, and did not find another field-based injection annotation!
Br simon

SONARJAVA-2219: Spring Annotations - adding missing one

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1123_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S117_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1210_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1258_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S131_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1479_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1698_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2142_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2164_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2201_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2259_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2387_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2757_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3355_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3355_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3423_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3725_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3923_java.html

SONARJAVA-2333 Update rule descriptions

---

java-frontend/src/main/java/org/sonar/java/se/checks/MapComputeIfAbsentOrPresentCheck.java

No reproducer for that one but we faced the problem as it was reported by a user.

SONARJAVA-2599 Prevent class cast exception

---

java-checks/src/main/java/org/sonar/java/checks/DiamondOperatorCheck.java
java-checks/src/test/files/checks/DiamondOperatorCheck_java_7.java
java-checks/src/test/files/checks/DiamondOperatorCheck_java_8.java
java-checks/src/test/files/checks/DiamondOperatorCheck_no_version.java

Duplicates #1850 to trigger internal QA.

Duplicates #1850 to trigger internal QA

---

java-checks/src/main/java/org/sonar/java/checks/CommentRegularExpressionCheck.java
java-checks/src/main/java/org/sonar/java/checks/DisallowedClassCheck.java
java-checks/src/test/java/org/sonar/java/checks/UndocumentedApiCheckTest.java
java-frontend/src/main/java/org/sonar/java/AnalysisError.java
java-frontend/src/main/java/org/sonar/java/IllegalRuleParameterException.java
java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
java-frontend/src/test/java/org/sonar/java/AnalysisErrorTest.java
java-frontend/src/test/java/org/sonar/java/ast/JavaAstScannerTest.java
java-frontend/src/test/java/org/sonar/java/se/Expectations.java
java-frontend/src/test/java/org/sonar/java/se/JavaCheckVerifierTest.java

Include fix of NPE introduced with the previous related tickets.

SONARJAVA-2478 Swallow and log exceptions from checks

---

README.md

SONARJAVA-2648 Update rules count and fix broken links

---

its/ruling/src/test/resources/guava/squid-S1751.json
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/LoopExecutingAtMostOnceCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1751_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1751_java.json
java-checks/src/test/files/checks/LoopExecutingAtMostOnceCheck.java
java-checks/src/test/java/org/sonar/java/checks/LoopExecutingAtMostOnceCheckTest.java

I don't think that this rule should be changed to a "bug". Discussion is open.

SONARJAVA-2668 Adjust behaviour of rule S1751 "Loops with at most once iteration should be refactored"

---

java-checks/src/main/java/org/sonar/java/checks/MethodParametersOrderCheck.java
java-checks/src/test/files/checks/MethodParametersOrderCheck.java

Report secondary location only for the misplace parameters for S2234
( Parameters should be passed in the correct order )

SONARJAVA-2728 : Improve secondary issue reporting for S2234

---

java-frontend/src/main/java/org/sonar/java/UCFGJavaVisitor.java
java-frontend/src/test/java/org/sonar/java/UCFGJavaVisitorTest.java

This change ensures consistency between handling method parameters and local variables.

SONARSEC-107 Translate all primitive types in method calls to constants

---

java-frontend/src/main/java/org/sonar/java/UCFGJavaVisitor.java
java-frontend/src/test/java/org/sonar/java/UCFGJavaVisitorTest.java

constructing __id call for variable declaration should lookup for expressions and not only variable

SONARSEC-156 variable declaration init - lookup expressions

---

java-checks/src/main/java/org/sonar/java/checks/security/SecureCookieCheck.java
java-checks/src/test/files/checks/security/SecureCookieCheck.java

SONARJAVA-2856 S2092: setSecure=false detected when using identifiers

---

java-checks/src/main/java/org/sonar/java/checks/helpers/IdentifierUtils.java
java-checks/src/main/java/org/sonar/java/checks/security/CookieHttpOnlyCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/EmptyDatabasePasswordCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/SecureCookieCheck.java
java-checks/src/test/files/checks/security/CookieHttpOnlyCheck.java
java-checks/src/test/java/org/sonar/java/checks/helpers/IdentifierUtilsTest.java
java-checks/src/test/java/org/sonar/java/checks/helpers/JavaParserHelper.java
java-checks/src/test/java/org/sonar/java/checks/helpers/ReassignmentFinderTest.java

 SONARJAVA-2855 S3330: setHttpOnly=false detected when using identifiers

---

java-checks/src/main/java/org/sonar/java/checks/security/XmlExternalEntityProcessingCheck.java
java-checks/src/test/files/checks/security/XmlExternalEntityProcessingCheck.java

SONARJAVA-2841 S2755 should consider "javax.xml.validation.Validator" and "javax.xml.validation.SchemaFactory"

---

java-frontend/src/main/java/org/sonar/java/se/checks/NonNullSetToNullCheck.java
java-frontend/src/test/files/se/NonNullSetToNullCheck.java

SONARJAVA-2839 S2637 Fix FP in private constructor

---

java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/test/files/checks/ReplaceLambdaByMethodRefCheck.java

SONARJAVA-2763 FP in S1612 on lambda calling a method on a newly created object

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/WireMock.java

Hey there,
I added the WireMockServer.verify() to the assertion checks. Let me know if there is something missing.
Kind regards
Benjamin

S2699 Extend WireMock assertion checks

---

java-checks/src/main/java/org/sonar/java/checks/SpecializedFunctionalInterfacesCheck.java
java-checks/src/test/files/checks/SpecializedFunctionalInterfacesCheck.java

SONARJAVA-2868 : S4276 should not suggest a replacement to the non-existing BooleanConsumer class

---

its/ruling/src/test/resources/jdk6/squid-S2255.json
its/ruling/src/test/resources/sonar-server/squid-S2255.json
java-checks/src/main/java/org/sonar/java/checks/security/CookieShouldNotContainSensitiveDataCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2255_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2255_java.json
java-checks/src/test/files/checks/security/CookieShouldNotContainSensitiveDataCheck.java

SONARJAVA-2889 S2255: Update implementation to detect cookie reading

---

java-frontend/src/main/java/org/sonar/java/bytecode/se/BytecodeEGWalker.java

As noticed in some peachee jobs.

Fix debug log message on method body not found

---

java-frontend/src/test/java/org/sonar/java/UCFGJavaVisitorTest.java

SONARJAVA-2835 was fixed in #2141 (commit 3198d5227)

Delete obsolete comment

---

java-checks/src/main/java/org/sonar/java/checks/ForLoopVariableTypeCheck.java
java-checks/src/test/files/checks/ForLoopVariableTypeCheck.java

* Add support for iteration over arrays
* Fix computation of collection type
* Fix handling of raw collection types

SONARJAVA-2955 Fix implementation of S4838

---

java-frontend/src/main/java/org/sonar/java/resolve/Resolve.java
java-frontend/src/test/files/sym/ImportResolution.java
java-frontend/src/test/java/org/sonar/java/resolve/ImportResolutionTest.java

SONARJAVA-2964 Fix NPE when resolving constant as static import of a generic class

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/xml/AbstractXPathBasedCheck.java
java-checks/src/main/java/org/sonar/java/checks/xml/ejb/InterceptorExclusionsCheck.java
java-checks/src/main/java/org/sonar/java/checks/xml/spring/SingleConnectionFactoryCheck.java
java-checks/src/test/java/org/sonar/java/checks/xml/ejb/InterceptorExclusionsCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/xml/spring/SingleConnectionFactoryCheckTest.java
java-checks/src/test/resources/checks/InterceptorExclusionsCheck/ejb-jar.xml
java-checks/src/test/resources/checks/SingleConnectionFactoryCheck/beans.xml

SONARJAVA-2981 and SONARJAVA-2984 Rewrite rules S3282-S3438

---

external-reports/pom.xml
external-reports/src/main/java/org/sonar/java/externalreport/CheckstyleSensor.java
external-reports/src/main/java/org/sonar/java/externalreport/CheckstyleXmlReportReader.java
external-reports/src/main/java/org/sonar/java/externalreport/PmdSensor.java
external-reports/src/main/java/org/sonar/java/externalreport/PmdXmlReportReader.java
external-reports/src/main/java/org/sonar/java/externalreport/SpotBugsSensor.java
external-reports/src/main/java/org/sonar/java/externalreport/SpotBugsXmlReportReader.java
external-reports/src/test/java/org/sonar/java/externalreport/CheckstyleSensorTest.java
external-reports/src/test/java/org/sonar/java/externalreport/PmdSensorTest.java
external-reports/src/test/java/org/sonar/java/externalreport/SpotBugsSensorTest.java
java-checks/pom.xml
java-frontend/pom.xml
pom.xml

SONARJAVA-2997 Use SafetyFactory to get XMLInputFactory to parse external report

---

java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/xml/struts/FormNameDuplicationCheck.java
java-checks/src/test/java/org/sonar/java/checks/xml/struts/FormNameDuplicationCheckTest.java
java-checks/src/test/resources/checks/FormNameDuplicationCheck/form-validation.xml

SONARJAVA-2986 Rewrite rule S3374

---

java-checks/src/main/java/org/sonar/java/checks/StandardCharsetsConstantsCheck.java
java-checks/src/test/files/checks/StandardCharsetsConstantsCheck.java

Duplicates #2324 to trigger QA.

Duplicates #2324 to trigger QA.

---

java-checks/src/main/java/org/sonar/java/checks/EqualsNotOverriddenInSubclassCheck.java
java-checks/src/test/files/checks/EqualsNotOverriddenInSubclassCheck.java
java-checks/src/test/java/org/sonar/java/checks/EqualsNotOverriddenInSubclassCheckTest.java

Duplicates #2341 to trigger QA and only include contribution from @troosan, slightly reworked.

SONARJAVA-3004 Fix rule S2160

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/Junit4.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/Selenide.java
java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java

Duplicates #2405 to trigger QA.

SONARJAVA-2928 Duplicate of #2405 to trigger QA

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/AssertJ.java

SONARJAVA-3038 S2699 should not raise issue when assertions are in anonymous classes

---

java-checks/pom.xml
java-checks/src/main/java/org/sonar/java/checks/AssertionArgumentOrderCheck.java
java-checks/src/main/java/org/sonar/java/checks/AssertionFailInCatchBlockCheck.java
java-checks/src/main/java/org/sonar/java/checks/AssertionInThreadRunCheck.java
java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/main/java/org/sonar/java/checks/AssertionsWithoutMessageCheck.java
java-checks/src/main/java/org/sonar/java/checks/BooleanLiteralInAssertionsCheck.java
java-checks/src/main/java/org/sonar/java/checks/naming/BadTestClassNameCheck.java
java-checks/src/main/java/org/sonar/java/checks/naming/BadTestMethodNameCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedTestRuleCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2924_java.html
java-checks/src/test/files/checks/AssertionArgumentOrderCheck_JUnit5.java
java-checks/src/test/files/checks/AssertionFailInCatchBlockCheck.java
java-checks/src/test/files/checks/AssertionInThreadRunCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/Junit5.java
java-checks/src/test/files/checks/AssertionsWithoutMessageCheck.java
java-checks/src/test/files/checks/BooleanLiteralInAssertionsCheck.java
java-checks/src/test/files/checks/naming/BadTestClassNameCheck.java
java-checks/src/test/files/checks/naming/BadTestMethodNameCheck.java
java-checks/src/test/files/checks/unused/UnusedTestRuleCheck.java
java-checks/src/test/files/checks/unused/UnusedTestRuleCheck_JUnit5.java
java-checks/src/test/java/org/sonar/java/checks/AssertionArgumentOrderCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/unused/UnusedTestRuleCheckTest.java

SONARJAVA-3034 Support JUnit 5 Jupiter

---

its/performancing/src/test/java/JavaPerformanceTest.java
its/ruling/src/test/java/org/sonar/java/it/JavaRulingTest.java
its/semantic/tests/src/test/java/com/sonar/it/java/semantic/SemanticTest.java

See https://jira.sonarsource.com/browse/SONAR-11670

Remove preview mode from ITs

---

Jenkinsfile

QA: Fix branch detection in Jenkinsfile

---

its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaClasspathTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaComplexityTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaExtensionsTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/SquidTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/SuppressWarningTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/TestUtils.java

Fix ITs after removal of 'sonar.profile' support

---

java-checks/src/main/java/org/sonar/java/checks/ChangeMethodContractCheck.java
java-checks/src/main/java/org/sonar/java/checks/CompareWithEqualsVisitor.java
java-checks/src/main/java/org/sonar/java/checks/EqualsNotOverridenWithCompareToCheck.java
java-checks/src/main/java/org/sonar/java/checks/EqualsOverridenWithHashCodeCheck.java
java-checks/src/main/java/org/sonar/java/checks/MagicNumberCheck.java
java-checks/src/main/java/org/sonar/java/checks/MainInServletCheck.java
java-checks/src/main/java/org/sonar/java/checks/MainMethodThrowsExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/RawExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/SymmetricEqualsCheck.java
java-checks/src/main/java/org/sonar/java/checks/SystemExitCalledCheck.java
java-checks/src/main/java/org/sonar/java/checks/ThrowsSeveralCheckedExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/UtilityClassWithPublicConstructorCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/MethodTreeUtils.java
java-checks/src/main/java/org/sonar/java/checks/security/CommandLineArgumentsCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedMethodParameterCheck.java
java-checks/src/test/java/org/sonar/java/checks/helpers/MethodTreeUtilsTest.java
java-frontend/src/main/java/org/sonar/java/model/declaration/MethodTreeImpl.java
java-frontend/src/test/java/org/sonar/java/model/declaration/MethodTreeImplTest.java

Move some utility methods from MethodTreeImpl into dedicated class

---

external-reports/pom.xml
its/performancing/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
its/semantic/java-debugging-plugin/pom.xml
its/semantic/pom.xml
its/semantic/tests/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jacoco/pom.xml
java-surefire/pom.xml
pom.xml
sonar-jacoco-listeners/pom.xml
sonar-java-plugin/pom.xml

Prepare next development iteration

---

README.md

duplicates https://github.com/SonarSource/sonar-java/pull/2505 for QA

README: Change demo project to a public one

---

java-checks/src/test/files/checks/NonShortCircuitLogicCheck.java
java-checks/src/test/files/checks/PrintStackTraceCalledWithoutArgumentCheck.java
java-checks/src/test/files/checks/StringConcatenationInLoopCheck.java
java-checks/src/test/files/checks/StringLiteralInsideEqualsCheck.java
java-checks/src/test/files/checks/SystemExitCalledCheck.java
java-checks/src/test/files/checks/ToStringUsingBoxingCheck.java
java-checks/src/test/files/checks/VolatileVariablesOperationsCheck.java

According to Java Language Specification expression statement can
be only assignment, method invocation, class instance creation and
pre/post increment/decrement.

Fix syntax errors in test files

---

Jenkinsfile

QA: Update Jenkinsfile lib to 2.1.2

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java

SONARJAVA-3106 Rule S2699: remove logs warning for empty property

---

its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTestSuite.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/SuppressWarningTest.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/TestUtils.java
its/plugin/tests/src/test/java/com/sonar/it/java/suite/UnitTestsTest.java

See https://jira.sonarsource.com/browse/SONAR-8776

SONARJAVA-3158 Remove usage of deprecated APIs in ITs

---

java-checks/src/main/java/org/sonar/java/checks/spring/PersistentEntityUsedAsRequestParameterCheck.java
java-checks/src/test/files/checks/spring/PersistentEntityUsedAsRequestParameterCheck.java

SONARJAVA-3151 Rule S4684 should not raise issue when entity argument is annotated with @PathVariable

---

java-checks/src/main/java/org/sonar/java/checks/DisallowedClassCheck.java
java-checks/src/test/files/checks/DisallowedClassCheck.java
java-checks/src/test/files/checks/DisallowedClassCheckRegex.java

SONARJAVA-3126 S3688: false negative when accessing member of the class

---

java-checks/src/main/java/org/sonar/java/checks/AbstractInSynchronizeChecker.java
java-checks/src/main/java/org/sonar/java/checks/StaticFieldInitializationCheck.java
java-checks/src/test/files/checks/StaticFieldInitializationCheck.java
java-checks/src/test/files/checks/StaticFieldUpateCheck.java
java-checks/src/test/files/checks/ThreadSleepCheck.java
java-checks/src/test/files/checks/WaitInSynchronizeCheck.java

Rule S2276, S2444, S2696, S2273 are impacted by the change.

SONARJAVA-3150 S2276 FP when Tread.sleep call is nested in a lambda

---

java-checks/src/main/java/org/sonar/java/checks/ArrayCopyLoopCheck.java
java-checks/src/test/files/checks/ArrayCopyLoopCheck.java

SONARJAVA-2971 Fix unsafe casts

---

java-checks/src/main/java/org/sonar/java/checks/FieldModifierCheck.java
java-checks/src/main/java/org/sonar/java/checks/ProtectedMemberInFinalClassCheck.java
java-checks/src/test/files/checks/FieldModifier.java
java-checks/src/test/files/checks/ProtectedMemberInFinalClassCheck.java

Let's support all `VisibleForTesting` annotation whatever their package names

SONARJAVA-3122 Support more @VisibleForTesting annotations

---

java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
java-checks/src/test/files/checks/AssertionsInTestsCheck/VertX.java

This is an internal PR of the external #2527 PR
See #2570 for details

S2599 FP vertx asyncAssertSuccess, asyncAssertFailure

---

java-checks/src/test/files/checks/UselessParenthesesCheck.java

According to Java Language Specification 12 expression statement can
be only assignment, method invocation, class instance creation and
pre/post increment/decrement.

Fix syntax error in test file

---

java-jacoco/src/main/java/org/sonar/plugins/jacoco/JaCoCoSensor.java
java-jacoco/src/test/java/org/sonar/plugins/jacoco/JaCoCoSensorTest.java

SONARJAVA-3164 Logs should mention that sonar-jacoco plugin is required to process XML report

---

java-checks/src/main/java/org/sonar/java/checks/SQLInjectionCheck.java
java-checks/src/test/files/checks/SQLInjection.java

SONARJAVA-3166 Support += in S2077

---

java-checks/src/main/java/org/sonar/java/checks/AtLeastOneConstructorCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1258_java.html
java-checks/src/test/files/checks/AtLeastOneConstructorCheck.java

S1258 - more Java EE specific annotations

---

docs/CUSTOM_RULES_101.md

duplicates #2648 to trigger QA, rebased on top of Master.

Fix typo in CUSTOM_RULES_101.md

---

java-checks/src/main/java/org/sonar/java/checks/MissingBeanValidationCheck.java
java-checks/src/test/files/checks/MissingBeanValidationCheck.java

Duplicates https://github.com/SonarSource/sonar-java/pull/2581 to trigger QA.

SONARJAVA-3214 - S5128 should ignore methods from private methods and methods from Constraint Validators

---

java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
java-checks/src/main/java/org/sonar/java/checks/naming/BadTestClassNameCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S3577_java.html
java-checks/src/test/files/checks/naming/BadTestClassNameCheck.java

Rebased duplicate of PR https://github.com/SonarSource/sonar-java/pull/2667, with some extra fixes for code quality.

Duplicates of #2667

---

java-checks/src/main/java/org/sonar/java/checks/synchronization/SynchronizationOnGetClassCheck.java
java-checks/src/test/files/checks/SynchronizationOnGetClassCheck.java
java-checks/src/test/java/org/sonar/java/checks/synchronization/SynchronizationOnGetClassCheckTest.java

Duplicates #2587 in order to trigger QA.
Also add case of synchronize block within enum, which would have cause another NPE.

SONARJAVA-3162 Fix S3067 NPE when synchronizing on getClass in initializer

---

java-checks/src/main/java/org/sonar/java/checks/AbstractClassNoFieldShouldBeInterfaceCheck.java
java-checks/src/test/files/checks/AbstractClassNoFieldShouldBeInterfaceCheck.java

Duplicates #2643 to trigger QA and Quality Gate. And also add support of `@AutoOneOf` annotation.

SONARJAVA-3216

---

java-checks/src/main/java/org/sonar/java/checks/UselessImportCheck.java
java-checks/src/test/files/checks/UselessImportCheck/IntersectionCase.java
java-checks/src/test/java/org/sonar/java/checks/UselessImportCheckTest.java

Duplicates #2650 to trigger QA and Quality Gates.

SONARJAVA-3217 Handle Intersection Types in S1128

---

java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
java-checks/src/test/files/filters/LombokFilter.java

SONARJAVA-3206 FP on S2039 when class is annotated with Lombok @Value

---

java-checks/src/main/java/org/sonar/java/checks/EqualsNotOverriddenInSubclassCheck.java
java-checks/src/test/files/checks/EqualsNotOverriddenInSubclassCheck.java

SONARJAVA-2818 S2160 not detecting when child class has a final equals method

---

java-checks/src/main/java/org/sonar/java/checks/UselessImportCheck.java
java-checks/src/test/files/checks/UselessImportCheck/WithinPackage.java

SONARJAVA-3177 FP on S1128 when import used in class annotations

---

java-checks/src/main/java/org/sonar/java/checks/StringCallsBeyondBoundsCheck.java
java-checks/src/test/files/checks/StringCallsBeyondBoundsCheck.java

SONARJAVA-3188 Fix False Negative in S3039 when using String length()

---

its/ruling/src/test/resources/sonar-server/squid-S1905.json
java-checks/src/main/java/org/sonar/java/checks/RedundantTypeCastCheck.java
java-checks/src/test/files/checks/RedundantTypeCastCheck.java

SONARJAVA-3191 S1905 should also raise issues in method invocation and constructor call arguments

---

java-checks/src/main/java/org/sonar/java/checks/RedundantTypeCastCheck.java
java-checks/src/test/files/checks/RedundantTypeCastCheck.java

SONARJAVA-3191 Fix crash due to unhandled variadic functions

---

java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java

SONARJAVA-2791 Assert correct resolution of most specific method when type is inferred

---

java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java

SONARJAVA-1678 Resolution of super constructor of external inner classes

---

java-checks/src/test/files/checks/RedundantTypeCastCheck.java

SONARJAVA-1616 Fix detection of unchecked conversion is overestimating

---

.github/workflows/dogfood.yml
.github/workflows/nightly.yml

Enable slack notifications

---

java-checks/src/main/java/org/sonar/java/checks/IgnoredReturnValueCheck.java
java-checks/src/test/files/checks/IgnoredReturnValueCheck.java

Duplicates and rebase #2764 to trigger QA.

Duplicates and rebase #2764 to trigger QA

---

java-checks-test-sources/pom.xml

Merge automatic PRs #2829, #2828, #2827, #2826, #2825, #2824, #2823

Update test sources dependencies according to security warnings

---

java-checks/src/main/java/org/sonar/java/checks/NioFileDeleteCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4042_java.html
java-checks/src/test/files/checks/NioFileDeleteCheck.java

Internal PR of the external PR ##2839 of @dpursehouse.
Note: I amended an update of the rule description to match the correct message.

SONARJAVA-3302 S4042 Fix message when using File.delete

---

java-checks-test-sources/pom.xml

Bump jackson-databind in /java-checks-test-sources

---

docs/CUSTOM_RULES_101.md

Related PR on sonar-custom-rules-examples:
https://github.com/SonarSource/sonar-custom-rules-examples/pull/48

SONARJAVA-3307 Migrate SonarJava custom rules tutorial to 6.2 and LTS 7.9

---

java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
java-checks/src/test/files/filters/LombokFilter.java

Duplicates #2873 to trigger all checks.

SONARJAVA-3320 Fix false positives for Lombok's field modifier annotations

---

java-frontend/src/main/java/org/sonar/java/model/GeneratedFile.java
java-frontend/src/main/java/org/sonar/java/model/SmapFile.java
java-frontend/src/test/java/org/sonar/java/model/GeneratedFileTest.java
java-frontend/src/test/java/org/sonar/java/model/SmapFileTest.java
java-jsp/pom.xml
java-jsp/src/main/java/org/sonar/java/jsp/Jasper.java
java-jsp/src/main/java/org/sonar/java/jsp/JasperOptions.java
java-jsp/src/test/java/org/sonar/java/jsp/JasperOptionsTest.java
java-jsp/src/test/java/org/sonar/java/jsp/JasperTest.java
sonar-java-plugin/pom.xml

Current size: 18709446
6.2: 17038520
i.e. we are at +1.7MB for JSP support

SONARJAVA-3325 [JSP] Remove dependency on Ant from Jasper

---

java-jsp/src/test/java/org/sonar/java/jsp/JasperTest.java

there is nothing to fix, because the issue does not occur anymore. Just adding test to assert it. Test fails (with small adaptation) in  rev  https://github.com/SonarSource/sonar-java/tree/24936c9eed88b9886cea36246aae32f6432d2cc9

SONARJAVA-3328 [JSP] Add test of running Jasper in symlinked dir

---

java-checks-test-sources/src/main/java/checks/IgnoredTestsCheck.java
java-checks/src/main/java/org/sonar/java/checks/IgnoredTestsCheck.java

SONARJAVA-3365 S1607: Improved message

---

java-checks/src/main/java/org/sonar/java/checks/AccessibilityChangeCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S1444_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3011_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3011_java.json
java-checks/src/test/files/checks/AccessibilityChangeCheck.java

Change issue type of S3011 and S1444 to code smell

---

docs/CUSTOM_RULES_101.md

* missed code styling for a package
* writhing -> writing

Spelling & formatting

---

its/ruling/pom.xml
its/ruling/src/test/java/org/sonar/java/it/JavaRulingTest.java
its/ruling/src/test/java/org/sonar/java/it/ProfileGenerator.java

Parameters not anymore supported and needed to be renamed:
profile_key => key
rule_key => rule

Fix ruling with SonarQube >= 8 because of bad qualityprofiles/activate_rule parameters

---

java-checks-test-sources/src/main/java/checks/regex/ReluctantQuantifierCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/RedosCheck.java
java-frontend/src/main/java/org/sonar/java/regex/RegexParser.java
java-frontend/src/test/java/org/sonar/java/regex/CharacterBufferTests.java
java-frontend/src/test/java/org/sonar/java/regex/RegexParserTestUtils.java
java-frontend/src/test/java/org/sonar/java/regex/ast/CharacterClassTreeTest.java
java-frontend/src/test/java/org/sonar/java/regex/ast/GroupTreesTest.java
java-frontend/src/test/java/org/sonar/java/regex/ast/PlainCharacterTreeTest.java
java-frontend/src/test/java/org/sonar/java/regex/ast/QuantifierTest.java
java-frontend/src/test/java/org/sonar/java/regex/ast/RegexBaseVisitorTest.java

[Regex] Fix unused import and error message bug and improve code coverage

---

java-frontend/src/main/java/org/sonar/java/bytecode/BytecodeHelper.java
override-dep-licenses.properties
pom.xml

This is a prerequisite for Java 14 support.

SONARJAVA-3270 Upgrade ASM to 8.0.1

---

java-checks-test-sources/src/main/java/checks/regex/RedosCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/RedosCheck.java

Since secondary locations are not supported for security hotspots.

SONARJAVA-3404 Change main issue location and remove secondary location

---

java-checks-test-sources/src/main/java/checks/regex/DuplicatesInCharacterClassCheck.java
java-checks-test-sources/src/main/java/checks/regex/ReluctantQuantifierCheck.java
java-checks-test-sources/src/main/java/checks/regex/UnicodeAwareCharClassesCheckTest.java
java-checks/src/main/java/org/sonar/java/checks/regex/DuplicatesInCharacterClassCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/ReluctantQuantifierCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/UnicodeAwareCharClassesCheck.java
java-frontend/src/main/java/org/sonar/java/regex/RegexParser.java
java-frontend/src/main/java/org/sonar/java/regex/ast/CharacterRangeTree.java
java-frontend/src/test/java/org/sonar/java/regex/RegexParserTestUtils.java
java-frontend/src/test/java/org/sonar/java/regex/ast/RegexBaseVisitorTest.java

Also add support for hex literals for rules S5869 and S5857.

Fix parsing of character ranges involving hex literals

---

java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
java-checks/src/test/files/filters/LombokFilter.java

Please rebase the two commits.

SONARJAVA-3379 and SONARJAVA-3437 FP due to Lombok "@UtilityClass"

---

java-frontend/src/main/java/org/sonar/java/model/JParser.java
java-frontend/src/main/java/org/sonar/java/model/declaration/ClassTreeImpl.java
java-frontend/src/main/java/org/sonar/java/model/declaration/MethodTreeImpl.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/ClassTree.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/MethodTree.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/Tree.java
java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
java-frontend/src/test/java/org/sonar/plugins/java/api/tree/TreeTest.java

Added elements are marked as deprecated because
it is preview feature and might change.

SONARJAVA-3286 Update AST for Java 14 Preview Feature: Records

---

its/ruling/src/test/resources/sonar-server/java-S2095.json
java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
java-frontend/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
java-frontend/src/test/files/se/NonNullSetToNullCheck.java
java-frontend/src/test/files/se/UnclosedResourcesCheck.java

Have a look [at this comment](https://jira.sonarsource.com/browse/SONARJAVA-3311?focusedCommentId=240135&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-240135) for my motivation to make this change.

SONARJAVA-3311 SE should correctly handle new class in catch

---

.github/workflows/release.yml

Update to release action workflow v2

---

java-frontend/src/main/java/org/sonar/java/se/symbolicvalues/RelationalSymbolicValue.java

Cache RelationalSymbolicValue's hashCode (Duplicates #3153)

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S1607_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S1607_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2589_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4818_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S5845_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S5845_java.json
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S5846_java.html
sonarpedia.json

See the ticket for more details.

SONARJAVA-3510 Update metadata before 6.7

---

.github/workflows/release.yml

Add slack notification on central sync error

---

sonar-java-plugin/src/main/resources/static/documentation.md

DOCS remove references to analyzers

---

java-checks-test-sources/src/main/java/checks/NoTestsInProductionFile.java
java-checks-test-sources/src/main/java/checks/TestsInProductionFile.java
java-checks/src/main/java/org/sonar/java/checks/CheckList.java
java-checks/src/main/java/org/sonar/java/checks/TestsInSeparateFolderCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
java-checks/src/main/java/org/sonar/java/checks/naming/BadTestClassNameCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3414_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3414_java.json
java-checks/src/test/java/org/sonar/java/checks/TestsInSeparateFolderCheckTest.java

The main idea is that main sources should not contain any classes with tests.

SONARJAVA-3522 Rule S3414: Tests should be kept in a dedicated source directory

---

java-checks-test-sources/src/main/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/test/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheckTest.java

I checked The main file without semantic. Almost all the fields were reported correctly. The only thing is annotations `@Inject` and `@EJB`. As far as they are not found without semantic, fields are reported as issues. So we have false positive.
Is it ok? or it's better o exclude analysis without semantic at all?

Fix FP for Serializable with initializer

---

java-checks-test-sources/src/main/files/non-compiling/checks/security/CookieHttpOnlyCheck.java
java-checks-test-sources/src/main/files/non-compiling/checks/security/SecureCookieCheck.java
java-checks-test-sources/src/main/java/checks/security/CookieHttpOnlyCheck.java
java-checks-test-sources/src/main/java/checks/security/SecureCookieCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/CookieHttpOnlyCheck.java
java-checks/src/test/java/org/sonar/java/checks/security/CookieHttpOnlyCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/security/SecureCookieCheckTest.java

 SONARJAVA-3500: S3330 supports all Play framework Cookie constructor

---

java-checks-test-sources/src/main/files/non-compiling/checks/ArrayForVarArgCheck.java
java-checks-test-sources/src/main/java/checks/ArrayForVarArgCheck.java
java-checks/src/main/java/org/sonar/java/checks/ArrayForVarArgCheck.java
java-checks/src/test/java/org/sonar/java/checks/ArrayForVarArgCheckTest.java

SONARJAVA-3519 FP on S3878 when the argument before the vararg is also an array

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S899_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S899_java.json

SONARJAVA-3485 Change issue type of S899 to Bug

SONARJAVA-3485 Change issue type of S899 to Bug

---

java-checks-test-sources/src/main/java/checks/OneExpectedRuntimeExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/OneExpectedRuntimeExceptionCheck.java

SONARJAVA-3528 Allow simple mocks as parameter

---

external-reports/src/test/java/org/sonar/java/externalreport/CheckstyleSensorTest.java
external-reports/src/test/java/org/sonar/java/externalreport/SpotBugsSensorTest.java
java-checks/src/test/java/org/sonar/java/checks/regex/AbstractRegexCheckTest.java
java-frontend/src/test/java/org/sonar/java/ast/visitors/SyntaxHighlighterVisitorTest.java
java-frontend/src/test/java/org/sonar/java/cfg/VariableReadExtractorTest.java
java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
java-frontend/src/test/java/org/sonar/java/regex/ast/DisjunctionTreeTest.java
java-frontend/src/test/java/org/sonar/java/se/checks/SyntaxTreeNameFinderTest.java

Fix new code smells in our code due to the addition of a new rule: [RSPEC-5976](https://jira.sonarsource.com/browse/RSPEC-5976)

Use ParameterizedTest instead of duplicating code

---

external-reports/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-test-sources/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
jdt/pom.xml
pom.xml
sonar-java-plugin/pom.xml

Prepare for next development iteration

---

external-reports/src/test/java/org/sonar/java/externalreport/ExternalIssueAssert.java
external-reports/src/test/java/org/sonar/java/externalreport/PmdSensorTest.java

I just found this issue in Sonar java. And have a proposal how to make it more readable.
What do you think about this solution? Doest it look more readable for you?

Fix too many assertions issue

---

java-checks-test-sources/src/main/java/checks/DeprecatedHashAlgorithmCheck.java
java-checks-test-sources/src/main/java/checks/security/DataHashingCheck.java
java-checks/src/main/java/org/sonar/java/checks/AbstractHashAlgorithmChecker.java
java-checks/src/main/java/org/sonar/java/checks/DeprecatedHashAlgorithmCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/DataHashingCheck.java
java-checks/src/test/java/org/sonar/java/checks/DeprecatedHashAlgorithmCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/security/DataHashingCheckTest.java

Update reported message for a security hotspot

SONARJAVA-3414 Rule S4790: its content should be replaced by S2070

---

java-checks-test-sources/src/main/java/checks/spring/SpringRequestMappingMethodCheck.java
java-checks/src/main/java/org/sonar/java/checks/spring/SpringRequestMappingMethodCheck.java

SONARJAVA-3376 S3752: Update reported message

---

its/ruling/src/test/resources/commons-beanutils/java-S1948.json
its/ruling/src/test/resources/guava/java-S1948.json
java-checks-test-sources/src/main/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java

Duplicates #3250 for QA

---

its/plugin/projects/java-extension/pom.xml
its/plugin/projects/java-inner-classes/pom.xml
its/plugin/projects/no_coverage/pom.xml
its/plugin/projects/tests-surefire-suffix/pom.xml
its/plugin/projects/tests-without-main-code/pom.xml
java-checks-test-sources/pom.xml
pom.xml

Duplicates #3247, #3246, #3244, #3243, #3242, #3240, #3239

Update JUnit dependencies to 4.13.1

---

java-checks-test-sources/pom.xml
java-checks-test-sources/src/main/java/checks/tests/AssertionsInTestsCheck/RestAssured2.java
java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2699_java.html
java-checks/src/test/java/org/sonar/java/checks/tests/AssertionsInTestsCheckTest.java

Duplicates and rebase on top of master #3254 to trigger QA.

SONARJAVA-3616 Fix RestAssured 2.x support

---

java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
java-checks/src/test/files/filters/LombokFilter.java

SONARJAVA-3579 FP in S1170 when class is annotated with @lombok.Builder and field with @Default

---

its/ruling/src/test/resources/sonar-server/java-S1612.json
java-checks-test-sources/src/main/files/non-compiling/checks/ReplaceLambdaByMethodRefCheck.java
java-checks-test-sources/src/main/java/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
java-checks/src/test/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheckTest.java

SONARJAVA-3547 Improve rule S1612 to replace casts with method reference

---

java-checks/src/main/java/org/sonar/java/checks/xml/spring/SingleConnectionFactoryCheck.java
java-checks/src/test/resources/checks/SingleConnectionFactoryCheck/beans.xml

Duplicates #3257 to trigger QA.

SONARJAVA-3618 FP on S3438 when "value" is set inside the property tag

---

java-checks/src/main/java/org/sonar/java/checks/AbstractHashAlgorithmChecker.java
java-checks/src/main/java/org/sonar/java/checks/BooleanInversionCheck.java
java-checks/src/main/java/org/sonar/java/checks/CastArithmeticOperandCheck.java
java-checks/src/main/java/org/sonar/java/checks/CollectionImplementationReferencedCheck.java
java-checks/src/main/java/org/sonar/java/checks/CollectionMethodsWithLinearComplexityCheck.java
java-checks/src/main/java/org/sonar/java/checks/CollectionsEmptyConstantsCheck.java
java-checks/src/main/java/org/sonar/java/checks/DeprecatedHashAlgorithmCheck.java
java-checks/src/main/java/org/sonar/java/checks/FilesExistsJDK8Check.java
java-checks/src/main/java/org/sonar/java/checks/ImmediateReverseBoxingCheck.java
java-checks/src/main/java/org/sonar/java/checks/ImmediatelyReturnedVariableCheck.java
java-checks/src/main/java/org/sonar/java/checks/NonShortCircuitLogicCheck.java
java-checks/src/main/java/org/sonar/java/checks/RedundantStreamCollectCheck.java
java-checks/src/main/java/org/sonar/java/checks/ReplaceGuavaWithJava8Check.java
java-checks/src/main/java/org/sonar/java/checks/StandardCharsetsConstantsCheck.java
java-checks/src/main/java/org/sonar/java/checks/SynchronizedClassUsageCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/MapBuilder.java
java-checks/src/main/java/org/sonar/java/checks/regex/UnicodeAwareCharClassesCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/CryptographicKeySizeCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/DataHashingCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertTrueInsteadOfDedicatedAssertCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/JUnit45MethodAnnotationCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/JUnit4AnnotationsCheck.java
java-frontend/src/main/java/org/sonar/java/collections/MapBuilder.java
java-frontend/src/test/java/org/sonar/java/collections/MapBuilderTest.java

SONARJAVA-2154 Remove usage of ImmutableMap from java-checks module

---

java-checks/src/main/java/org/sonar/java/checks/CORSCheck.java
java-checks/src/main/java/org/sonar/java/checks/CollectionMethodsWithLinearComplexityCheck.java
java-checks/src/main/java/org/sonar/java/checks/EscapedUnicodeCharactersCheck.java
java-checks/src/main/java/org/sonar/java/checks/IgnoredReturnValueCheck.java
java-checks/src/main/java/org/sonar/java/checks/JacksonDeserializationCheck.java
java-checks/src/main/java/org/sonar/java/checks/MainInServletCheck.java
java-checks/src/main/java/org/sonar/java/checks/PseudoRandomCheck.java
java-checks/src/main/java/org/sonar/java/checks/PublicStaticMutableMembersCheck.java
java-checks/src/main/java/org/sonar/java/checks/RawExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/ReturnEmptyArrayNotNullCheck.java
java-checks/src/main/java/org/sonar/java/checks/StringBufferAndBuilderWithCharCheck.java
java-checks/src/main/java/org/sonar/java/checks/ToStringUsingBoxingCheck.java
java-checks/src/main/java/org/sonar/java/checks/TrailingCommentCheck.java
java-checks/src/main/java/org/sonar/java/checks/WrongAssignmentOperatorCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/Javadoc.java
java-checks/src/main/java/org/sonar/java/checks/naming/KeywordAsIdentifierCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/UnicodeAwareCharClassesCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/DataHashingCheck.java
java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableContract.java
java-checks/src/main/java/org/sonar/java/checks/synchronization/ValueBasedObjectUsedForLockCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertionsWithoutMessageCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedTestRuleCheck.java
java-checks/src/main/java/org/sonar/java/filters/EclipseI18NFilter.java
java-checks/src/main/java/org/sonar/java/filters/GoogleAutoFilter.java
java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
java-checks/src/test/java/org/sonar/java/checks/CheckListTest.java
java-checks/src/test/java/org/sonar/java/filters/BaseTreeVisitorIssueFilterTest.java
java-frontend/src/main/java/org/sonar/java/collections/SetUtils.java
java-frontend/src/test/java/org/sonar/java/collections/SetUtilsTest.java

I've changed Set -> List in few places, where we're not searching element but iterating over them and in case of 2 elements.

SONARJAVA-2154 Remove usages of ImmutableSet from java-checks module

---

java-checks-test-sources/src/main/java/checks/regex/ReluctantQuantifierCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/ReluctantQuantifierCheck.java

SONARJAVA-3482 Support character classes as operand to reluctant quantifier in rule S5857

---

sonar-java-plugin/pom.xml
sonar-java-plugin/src/main/java/org/sonar/plugins/java/Java.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaPlugin.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaRulesDefinition.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSonarWayProfile.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/XmlFileSensor.java

SONARJAVA-2154 Remove usages of guava from sonar-java-plugin module

---

java-checks-test-sources/src/main/java/checks/TooManyParametersCheck.java
java-checks-test-sources/src/main/java/checks/TooManyParametersCustom.java
java-checks/src/main/java/org/sonar/java/checks/TooManyParametersCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S107_java.html
java-checks/src/test/java/org/sonar/java/checks/TooManyParametersCheckTest.java

SONARJAVA-3470 Fix FP rule S107 by adding more ignored annotations

---

java-checks-test-sources/src/main/files/non-compiling/checks/ServletInstanceFieldCheck.java
java-checks-test-sources/src/main/java/checks/ServletInstanceFieldCheck.java
java-checks/src/main/java/org/sonar/java/checks/ServletInstanceFieldCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2226_java.html
java-checks/src/test/java/org/sonar/java/checks/ServletInstanceFieldCheckTest.java

SONARJAVA-3599 FP in S2226 for non final Servlet fields initialized in init() method without parameters

---

its/ruling/src/test/resources/sonar-server/java-S3824.json
java-checks-test-sources/src/main/java/symbolicexecution/checks/MapComputeIfAbsentOrPresentCheck.java
java-frontend/src/main/java/org/sonar/java/se/checks/MapComputeIfAbsentOrPresentCheck.java

SONARJAVA-3130 Fix FP when the value put in map is null literal

---

java-checks-test-sources/src/main/java/checks/regex/UnusedGroupNamesCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/AbstractRegexCheckTrackingMatchers.java

SONARJAVA-3567 Fix FP introduced to S5860 by AbstractRegexCheckTrackingMatchers

---

java-checks/src/main/java/org/sonar/java/checks/ForLoopIncrementAndUpdateCheck.java
java-checks/src/main/java/org/sonar/java/checks/IdenticalOperandOnBinaryExpressionCheck.java
java-checks/src/main/java/org/sonar/java/checks/SyncGetterAndSetterCheck.java
java-checks/src/main/java/org/sonar/java/checks/spring/SpringIncompatibleTransactionalCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertionArgumentOrderCheck.java
java-frontend/src/main/java/org/sonar/java/se/checks/InvariantReturnCheck.java
java-frontend/src/test/files/se/InvariantReturnCheck.java

SONARJAVA-3581 S1994: Add a message on the secondary location
SONARJAVA-3582 S2886: Add a message on the secondary location
SONARJAVA-3584 S1764: Add a message on secondary locations
SONARJAVA-3583 S3516: Add a message on the secondary location
SONARJAVA-3589 S2229: Add a message on secondary locations
SONARJAVA-3590 S3415: Add a message on secondary locations

Add a message on the secondary locations for 6 rules

---

java-checks/src/main/java/org/sonar/java/checks/LoggedRethrownExceptionsCheck.java
java-checks/src/main/java/org/sonar/java/checks/SeveralBreakOrContinuePerLoopCheck.java
java-checks/src/main/java/org/sonar/java/checks/SpecializedFunctionalInterfacesCheck.java
java-checks/src/main/java/org/sonar/java/checks/SpringConstructorInjectionCheck.java
java-checks/src/main/java/org/sonar/java/checks/StaticFieldUpdateInConstructorCheck.java
java-checks/src/main/java/org/sonar/java/checks/SunPackagesUsedCheck.java

SONARJAVA-3596 S4276: Add a message on secondary locations
SONARJAVA-3595 S4288: Add a message on secondary locations
SONARJAVA-3594 S135: Add a message on secondary locations
SONARJAVA-3593 S3010: Add a message on secondary locations
SONARJAVA-3592 S1191: Add a message on secondary locations
SONARJAVA-3591 S2139: Add a message on secondary locations

Add a message on secondary locations - batch 2

---

java-frontend/src/main/java/org/sonar/java/exceptions/package-info.java
java-frontend/src/main/java/org/sonar/java/se/AlwaysTrueOrFalseExpressionCollector.java

Fix quality flow after removing guava base package

---

java-checks-test-sources/src/main/files/non-compiling/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks-test-sources/src/main/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java

SONARJAVA-3467 FP on S1948 when using both field and setter/constructor injection

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2384_java.json

SONARJAVA-3638 Rule S2384: change rule type to Code-Smell

---

java-frontend/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java

Fix quality flaw: remove unused method

---

java-frontend/src/main/java/org/sonar/java/ast/visitors/SubscriptionVisitor.java

Deprecate "hasSemantic" method

---

java-checks-test-sources/src/main/files/non-compiling/checks/SwitchInsteadOfIfSequenceCheck.java
java-checks-test-sources/src/main/files/non-compiling/checks/TextBlockToString.java
java-checks-test-sources/src/main/files/non-compiling/checks/regex/EmptyLineRegexCheck.java
java-checks-test-sources/src/main/java/checks/StringToString.java
java-checks-test-sources/src/main/java/checks/SwitchInsteadOfIfSequenceCheck.java
java-checks/src/main/java/org/sonar/java/checks/ControlCharacterInLiteralCheck.java
java-checks/src/main/java/org/sonar/java/checks/StringToStringCheck.java
java-checks/src/main/java/org/sonar/java/checks/SwitchInsteadOfIfSequenceCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/EmptyLineRegexCheck.java
java-checks/src/test/java/org/sonar/java/checks/StringToStringCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/SwitchInsteadOfIfSequenceCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/regex/EmptyLineRegexCheckTest.java
java-frontend/src/main/java/org/sonar/java/AnalyzerMessage.java
java-frontend/src/main/java/org/sonar/java/ast/visitors/SyntaxHighlighterVisitor.java
java-frontend/src/main/java/org/sonar/java/model/JParser.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/LiteralTree.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/Tree.java
java-frontend/src/test/java/org/sonar/java/AnalyzerMessageTest.java
java-frontend/src/test/java/org/sonar/java/model/JavaTreeModelTest.java
java-frontend/src/test/java/org/sonar/plugins/java/api/tree/TreeTest.java

Should be rebased.
Firstly, I thought that this ticket is also regarding rules. So I started adding support in rules. I think if we do "rebase & merge" it's fine to leave it here.
For the convenience it's better to review by commits.

SONARJAVA-3658 Support TEXT_BLOCKs

---

java-checks-test-sources/src/main/files/non-compiling/checks/EscapedUnicodeCharactersTextBlocksCheck.java
java-checks/src/main/java/org/sonar/java/checks/EscapedUnicodeCharactersCheck.java
java-checks/src/test/java/org/sonar/java/checks/EscapedUnicodeCharactersCheckTest.java

Waits for https://github.com/SonarSource/sonar-java/pull/3399 to be merged

SONARJAVA-3665 Add support of Text Blocks in S2973 (Escaped unicode characters)

---

java-frontend/src/test/java/org/sonar/java/ExecutionTimeReportTest.java

SONARJAVA-3563 Fix test failure when logs contain "0/0 source files have been analyzed"

---

java-checks-test-sources/src/main/files/non-compiling/checks/InterruptedExceptionCheck.java
java-checks-test-sources/src/main/java/checks/InterruptedExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/InterruptedExceptionCheck.java
java-checks/src/test/java/org/sonar/java/checks/InterruptedExceptionCheckTest.java

SONARJAVA-3662 Improve rule S2142 to check methods called inside catch block

---

java-checks-test-sources/src/main/files/non-compiling/checks/ControlCharacterInLiteralCheck.java
java-checks/src/main/java/org/sonar/java/checks/ControlCharacterInLiteralCheck.java

SONARJAVA-3667 Improve S2479 to support non-indent tabs in Text blocks

---

java-checks-test-sources/src/main/java/checks/SQLInjection.java
java-checks/src/main/java/org/sonar/java/checks/SQLInjectionCheck.java

SONARJAVA-3660 S2077 update message for primary and secondary locations

---

java-checks-test-sources/src/main/files/non-compiling/checks/security/UnpredictableSaltCheck.java
java-checks-test-sources/src/main/java/checks/security/UnpredictableSaltCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/UnpredictableSaltCheck.java

SONARJAVA-2929 Rule S2053: Report issues only on PBEKeySpec

---

its/ruling/src/test/resources/eclipse-jetty/java-S2142.json
java-checks-test-sources/src/main/files/non-compiling/checks/InterruptedExceptionCheck.java
java-checks-test-sources/src/main/java/checks/InterruptedExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/InterruptedExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/MethodTreeUtils.java
java-checks/src/main/java/org/sonar/java/checks/tests/AbstractOneExpectedExceptionRule.java
java-checks/src/main/java/org/sonar/java/checks/tests/OneExpectedCheckedExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/OneExpectedRuntimeExceptionCheck.java

Small precision: 
I decided to only support "InterruptedException" and not "ThreadDeath" because it is an (unchecked) error, I don't expect it to catch anything more than what is currently detected.

SONARJAVA-2745 FN on S2142: no issue raised when catching the generic Exception

---

.gitignore
java-symbolic-execution/src/main/java/org/sonar/java/se/NullableAnnotationUtils.java
java-symbolic-execution/src/test/files/se/annotations/NullableAnnotationUtils_global.java
java-symbolic-execution/src/test/java/org/sonar/java/se/NullableAnnotationUtilsTest.java

Duplicates #3465 to trigger QA.

SONARJAVA-3710 Include Eclipse’s NonNullByDefault annotation on nonNullFields check

---

java-checks-test-sources/src/main/java/checks/BoxedBooleanExpressionsCheck.java
java-checks/src/main/java/org/sonar/java/checks/BoxedBooleanExpressionsCheck.java

SONARJAVA-3570 S5411: Relax rule when test is done in related branch

---

java-checks-test-sources/src/main/java/checks/regex/RedosCheck.java
java-checks-test-sources/src/main/java/checks/regex/RedosCheckJava8.java
java-checks/src/main/java/org/sonar/java/checks/helpers/AbstractAutomataChecker.java
java-checks/src/main/java/org/sonar/java/checks/regex/RedosCheck.java
java-checks/src/test/java/org/sonar/java/checks/helpers/OrderedAutomataPairCacheTest.java
java-checks/src/test/java/org/sonar/java/checks/helpers/OrderedAutomataPairTest.java

SONARJAVA-3733 ReDoS: Don't call cubic and worse runtimes quadratic

---

java-frontend/src/main/java/org/sonar/java/ExecutionTimeReport.java
java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
java-frontend/src/test/java/org/sonar/java/ExecutionTimeReportTest.java

SONARJAVA-3715: Add size of file to slowest files analyzed output

---

java-checks-test-sources/src/main/files/non-compiling/checks/regex/SingleCharacterAlternationWithTextBlocks.java
java-checks/src/main/java/org/sonar/java/checks/regex/AbstractRegexCheck.java
java-checks/src/test/java/org/sonar/java/checks/regex/SingleCharacterAlternationCheckTest.java
java-frontend/src/main/java/org/sonar/java/model/ExpressionUtils.java
java-frontend/src/main/java/org/sonar/java/regex/JavaAnalyzerRegexSource.java
java-frontend/src/test/java/org/sonar/java/regex/JavaAnalyzerRegexSourceTest.java
java-frontend/src/test/java/org/sonar/java/regex/RegexParserTestUtils.java

Needs SONARJAVA-3732 to be merged first

SONARJAVA-3666 Add text block support for regex rules

---

java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/JavaCheckVerifier.java
java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/MultipleFilesJavaCheckVerifier.java

Fix javadoc link on java-checks-testkit

---

sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSonarWayProfile.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaRulesDefinitionTest.java

Fix performance issue when loading rules from quality profile

---

java-checks/src/main/java/org/sonar/java/checks/security/EncryptionAlgorithmCheck.java

Fix quality flaw: fix regex

---

.cirrus.yml
.github/workflows/release.yml

Parent pom already updated in #3574.

Update release workflow to V3

---

java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S6104_java.html

Duplicates #3580 to trigger QA.

Fix spelling in rule documentation

---

java-checks-test-sources/src/main/java/checks/regex/AbstractRegexCheck.java
java-checks-test-sources/src/main/java/checks/regex/RegexStackOverflowCheckWithLowStackConsumption.java
java-checks/src/main/java/org/sonar/java/checks/regex/AbstractRegexCheck.java

Should only be merged after SONARJAVA-3841

SONARJAVA-3840 Regex rules should support concatenating pattern objects 

---

its/ruling/src/test/resources/sonar-server/java-S5838.json
java-checks-test-sources/src/main/java/checks/AssertJChainSimplificationCheckTest.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertJChainSimplificationIndex.java

Duplicates #3619 and #3620 to trigger QA.

SONARJAVA-3858 S5838 should support "length()"/"size()" followed by "isPositive()" simplification

---

pom.xml

This reverts commit 4b85e88c34a956fd11c3bacb78c0bc7f85cea10b.

Revert "Skip Sonar analysis temporarily"

---

java-checks-test-sources/src/main/java/checks/DateFormatWeekYearCheck.java
java-checks/src/main/java/org/sonar/java/checks/DateFormatWeekYearCheck.java

SONARJAVA-3876: Fix IndexOutOfBoundsException in S3986

---

java-checks-test-sources/src/main/java/checks/AccessibilityChangeCheckWithRecordSupport.java
java-checks-test-sources/src/main/java/checks/AccessibilityChangeOnRecordsCheck.java

Re-opening this ticket to leave more meaningful comments to the test source files.
This should help future developers when verifying why S6216 reports issues on test files for S3011.

SONARJAVA-3768 Change comments in test source files for easier verification

---

java-checks-test-sources/src/main/java/checks/PseudoRandomCheck.java
java-checks/src/main/java/org/sonar/java/checks/PseudoRandomCheck.java

Also fix an FN when a random method is imported statically

SONARJAVA-3901 FP in S2245 (PseudeRandomCheck) when passing a SecureRandom object as parameter

---

java-checks-test-sources/src/main/java/android/app/Activity.java
java-checks-test-sources/src/main/java/android/content/ContextWrapper.java
java-checks-test-sources/src/main/java/android/view/ContextThemeWrapper.java
java-checks-test-sources/src/main/java/checks/security/AndroidBroadcastingCheck.java
java-checks-test-sources/src/main/java/checks/security/AndroidExternalStorage.java
java-checks-test-sources/src/main/java/checks/security/ReceivingIntentsCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/AndroidBroadcastingCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/AndroidExternalStorageCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/ReceivingIntentsCheck.java

Targets 3 rules: 
- S5322
- S5320
- S5324

SONARJAVA-4032, SONARJAVA-4033, SONARJAVA-4038: consider subclasses of Android Context

---

java-checks-test-sources/pom.xml
java-checks-test-sources/src/main/java/checks/tests/AssertionsInTestsCheck/Spring.java
java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2699_java.html

https://github.com/SonarSource/rspec/pull/582 should also be merged.

SONARJAVA-4047 S2699: Fix FP with andExpectAll introduced in recent version of Spring Test

---

java-checks/src/main/java/org/sonar/java/checks/spring/RequestMappingMethodPublicCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3751_java.html
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3751_java.json
java-checks/src/test/files/checks/spring/RequestMappingMethodPublicCheck.java

Duplicates #3835 to trigger CI.

SONARJAVA-4073 S3751 should accept protected and package scope modifiers

---

.cirrus.yml
wss-unified-agent.config

Add whitesource to build pipeline

---

java-checks-test-sources/src/main/files/non-compiling/symbolicexecution/checks/LocksNotUnlockedCheck.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/DivisionByZeroCheck.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/InvariantReturnCheck.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/LocksNotUnlockedCheck.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/LocksNotUnlockedCheckCache.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/MethodInvocationLeadingToDivisionByZero.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/NoWayOutLoopCheck.java
java-checks-test-sources/src/main/java/symbolicexecution/checks/RedundantAssignmentsCheck.java
java-symbolic-execution/src/test/java/org/sonar/java/se/checks/DivisionByZeroCheckTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/checks/InvariantReturnCheckTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/checks/LocksNotUnlockedCheckTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/checks/NoWayOutLoopCheckTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/checks/RedundantAssignmentsCheckTest.java

During my investigation on SE, I ended up cleaning a bit the test code.

Move test files to compiled module for SE rules

---

docs/java-custom-rules-example/README.md
docs/java-custom-rules-example/pom.xml
docs/java-custom-rules-example/pom_SQ_7_9_LTS.xml
docs/java-custom-rules-example/pom_SQ_8_9_LTS.xml

Relates to https://jira.sonarsource.com/browse/PACKMP-13
* Update maven-packaging-plugin
* Shade dependencies

SONARJAVA-4115 Update custom rules examples

---

java-checks-test-sources/src/main/java/checks/JacksonDeserializationCheck.java
java-checks/src/main/java/org/sonar/java/checks/JacksonDeserializationCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4544_java.html
java-checks/src/test/java/org/sonar/java/checks/JacksonDeserializationCheckTest.java

Related PR on rspec project: https://github.com/SonarSource/rspec/pull/682

SONARJAVA-4055 S4544 should raise on Interface in addition to Class

---

external-reports/src/test/java/org/sonar/java/externalreport/CheckstyleSensorTest.java
external-reports/src/test/java/org/sonar/java/externalreport/PmdSensorTest.java
external-reports/src/test/java/org/sonar/java/externalreport/SpotBugsSensorTest.java
java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/ExpectationsTest.java
java-checks/src/test/java/org/sonar/java/checks/CheckListTest.java
java-checks/src/test/java/org/sonar/java/checks/RulesSanityTest.java
java-surefire/src/test/java/org/sonar/plugins/surefire/SurefireExtensionsTest.java
java-surefire/src/test/java/org/sonar/plugins/surefire/data/SurefireStaxHandlerTest.java
java-surefire/src/test/java/org/sonar/plugins/surefire/data/UnitTestClassReportTest.java
java-surefire/src/test/java/org/sonar/plugins/surefire/data/UnitTestIndexTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/ExplodedGraphWalkerTest.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSonarWayProfileTest.java

Improvements in S5838 (SONARJAVA-4058) now detect new issues, the goal of this PR is to fix them.

Fix quality flaw: simplify AssertJ assertions

---

its/ruling/src/test/resources/eclipse-jetty/java-S1450.json
its/ruling/src/test/resources/sonar-server/java-S1450.json
java-checks/src/main/java/org/sonar/java/checks/PrivateFieldUsedLocallyCheck.java
java-checks/src/test/files/checks/PrivateFieldUsedLocallyCheck.java

This PR should solve both SONARJAVA-4142 and SONARJAVA-4129.

SONARJAVA-4142 SONARJAVA-4129 Refactor enclosing method logic in S1450

---

docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-test-sources/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/pom.xml
jdt/pom.xml
pom.xml
sonar-java-plugin/pom.xml

@m-g-sonar I tried to rename the version in the activity panel of Next, as suggested by the new release process, but I'm unsure I have the right to do this.

Prepare for next development iteration 7.12.0

---

java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifier.java
java-checks/src/test/java/org/sonar/java/checks/RunFinalizersCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/SanityTest.java
java-checks/src/test/java/org/sonar/java/checks/helpers/JParserTestUtils.java
java-checks/src/test/java/org/sonar/java/filters/AnyRuleIssueFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/BaseTreeVisitorIssueFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/FilterVerifier.java
java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
java-frontend/src/main/java/org/sonar/java/model/JParserConfig.java
java-frontend/src/main/java/org/sonar/java/model/JavaVersionImpl.java
java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
java-frontend/src/main/java/org/sonar/java/testing/VisitorsBridgeForTests.java
java-frontend/src/main/java/org/sonar/plugins/java/api/JavaVersion.java
java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
java-frontend/src/test/java/org/sonar/java/ast/JavaAstScannerTest.java
java-frontend/src/test/java/org/sonar/java/model/JParserConfigTest.java
java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
java-frontend/src/test/java/org/sonar/java/model/JParserTest.java
java-frontend/src/test/java/org/sonar/java/model/JParserTestUtils.java
java-frontend/src/test/java/org/sonar/java/model/JavaVersionImplTest.java
java-frontend/src/test/java/org/sonar/java/model/VisitorsBridgeTest.java
java-frontend/src/test/java/org/sonar/java/testing/VisitorsBridgeForTestsTest.java
java-frontend/src/test/java/org/sonar/plugins/java/api/IssuableSubscriptionVisitorTest.java
java-symbolic-execution/src/test/java/org/sonar/java/se/utils/JParserTestUtils.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java

… for java version >= maximum supported version

SONARJAVA-4214 Compiler flag "enablePreviewFeatures" should be enabled

---

java-checks/src/main/java/org/sonar/java/checks/helpers/RegexTreeHelper.java
java-checks/src/main/java/org/sonar/java/checks/regex/CanonEqFlagInRegexCheck.java
java-checks/src/main/java/org/sonar/java/checks/regex/GraphemeClustersInClassesCheck.java
java-checks/src/test/java/org/sonar/java/checks/regex/GraphemeClustersInClassesCheckTest.java
pom.xml

The implementation is in fact almost the same, it's just that the helper class code has been moved around.

SONARJAVA-4160 Refactor S5868 using sonar-analyzer-commons

---

java-checks/src/main/java/org/sonar/java/checks/regex/RegexComplexityCheck.java
java-checks/src/test/java/org/sonar/java/checks/regex/RegexComplexityCheckTest.java
pom.xml

I had to modify/improve the code in Analyzer Commons. Please review the PR on the Commons side first: https://github.com/SonarSource/sonar-analyzer-commons/pull/226.

SONARJAVA-4155 Refactor S5843 using sonar-analyzer-commons

---

java-frontend/src/main/java/org/sonar/java/SonarComponents.java
java-frontend/src/main/java/org/sonar/java/model/DefaultModuleScannerContext.java
java-frontend/src/main/java/org/sonar/plugins/java/api/ModuleScannerContext.java
java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
java-frontend/src/test/java/org/sonar/java/model/DefaultInputFileScannerContextTest.java
java-frontend/src/test/java/org/sonar/java/model/DefaultJavaFileScannerContextTest.java
java-frontend/src/test/java/org/sonar/java/model/DefaultModuleScannerContextTest.java

Improve naming of API endpoint to retrieve the project-level working directory and add API endpoint to get the module key

SONARJAVA-4248 Improve public API w.r.t. working directory and module key.

---

its/ruling/src/test/resources/guava/java-S2272.json
java-checks-test-sources/src/main/java/checks/IteratorNextExceptionCheck.java
java-checks/src/main/java/org/sonar/java/checks/IteratorNextExceptionCheck.java

SONARJAVA-4330 Rule S2722: Update method invokation matching condition

---

.cirrus.yml

BUILD-1927 Migrate CirrusCI to AWS

---

java-checks-test-sources/src/main/java/checks/spring/s4605/componentScan/ComponentScan.java
java-checks-test-sources/src/main/java/checks/spring/s4605/componentScan/packageC/ComponentC.java
java-checks-test-sources/src/main/java/checks/spring/s4605/springBootApplication/Ko/Ko.java
java-checks-test-sources/src/main/java/checks/spring/s4605/springBootApplication/fourthApp/controller/Controller.java
java-checks-test-sources/src/main/java/checks/spring/s4605/springBootApplication/thirdApp/controller/Controller.java
java-checks/src/main/java/org/sonar/java/checks/spring/SpringBeansShouldBeAccessibleCheck.java

`@ComponentScan` was incorrectly spelled @ComponentsScan

SONARJAVA-4257  Fix typo in S4605 message

---

.cirrus.yml

BUILD-2026 Remove the suffix of CirrusCI role and K8s Cluster name

---

its/ruling/src/test/resources/commons-beanutils/java-S3776.json
java-checks/src/main/java/org/sonar/java/checks/CognitiveComplexityMethodCheck.java
java-checks/src/main/java/org/sonar/java/checks/MethodComplexityCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3776.html
java-checks/src/test/files/checks/CognitiveComplexityMethodCheckMax0.java

Fix S3776 and update S1541.
Also update the rule description (https://github.com/SonarSource/rspec/pull/1361).

SONARJAVA-4335 S3776 should Ignore equals() and hashCode() methods similarly to S1541

---

java-frontend/src/main/java/org/sonar/java/DefaultJavaResourceLocator.java
java-frontend/src/main/java/org/sonar/plugins/java/api/JavaResourceLocator.java
java-frontend/src/test/java/org/sonar/java/DefaultJavaResourceLocatorTest.java
sonar-java-plugin/src/main/resources/static/documentation.md
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java

Originally proposed in #4177 by @gtoison

SONARJAVA-4348 Export test classpath and binaries in the API

---

.cirrus.yml
.github/workflows/dogfood.yml
.github/workflows/release.yml

BUILD-2113 Use Vault

---

its/ruling/src/test/resources/guava/java-S3553.json
its/ruling/src/test/resources/sonar-server/java-S3553.json
java-checks-test-sources/src/main/java/checks/OptionalAsParameterCheck.java
java-checks/src/main/java/org/sonar/java/checks/OptionalAsParameterCheck.java
java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S3553.html

Don't flag Optional uses as parameter types when the method is overriding

SONARJAVA-4403 Add exception to S3553

---

java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
java-checks/src/test/java/org/sonar/java/checks/MissingPackageInfoCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/UselessPackageInfoCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/helpers/HashCacheTestHelper.java
java-checks/src/test/java/org/sonar/java/checks/security/ExcessiveContentRequestCheckTest.java
java-checks/src/test/java/org/sonar/java/checks/spring/SpringBeansShouldBeAccessibleCheckTest.java
java-frontend/src/main/java/org/sonar/java/SonarComponents.java
java-frontend/src/main/java/org/sonar/java/caching/ContentHashCache.java
java-frontend/src/main/java/org/sonar/java/caching/FileHashingUtils.java
java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
java-frontend/src/test/java/org/sonar/java/caching/ContentHashCacheTest.java
java-frontend/src/test/java/org/sonar/java/model/VisitorsBridgeTest.java

cherry-picking commit [e985f2c](https://github.com/SonarSource/sonar-java/commit/e985f2c7431e1c87421a0443e943ec8e80fa05e8) for ticket [SONARJAVA-4396](https://sonarsource.atlassian.net/browse/SONARJAVA-4396)
[SONARJAVA-4396]: https://sonarsource.atlassian.net/browse/SONARJAVA-4396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4396 Incremental analysis fix (#4317)

---

java-checks-test-sources/src/main/java/checks/SystemOutOrErrUsageCheck.java
java-checks/src/main/java/org/sonar/java/checks/SystemOutOrErrUsageCheck.java
java-checks/src/test/files/checks/SystemOutOrErrUsageCheck.java
java-checks/src/test/java/org/sonar/java/checks/SystemOutOrErrUsageCheckTest.java

Now, we log differently System.err and System.out.

SONARJAVA-4574 update issue message for rule S106

---

java-checks/src/main/java/org/sonar/java/checks/AnonymousClassShouldBeLambdaCheck.java
java-checks/src/main/java/org/sonar/java/checks/ArrayForVarArgCheck.java
java-checks/src/main/java/org/sonar/java/checks/CallOuterPrivateMethodCheck.java
java-checks/src/main/java/org/sonar/java/checks/CollectionInappropriateCallsCheck.java
java-checks/src/main/java/org/sonar/java/checks/ConfusingVarargCheck.java
java-checks/src/main/java/org/sonar/java/checks/ConstructorCallingOverridableCheck.java
java-checks/src/main/java/org/sonar/java/checks/DiamondOperatorCheck.java
java-checks/src/main/java/org/sonar/java/checks/RedundantAbstractMethodCheck.java
java-checks/src/main/java/org/sonar/java/checks/RedundantThrowsDeclarationCheck.java
java-checks/src/main/java/org/sonar/java/checks/SynchronizedOverrideCheck.java
java-checks/src/main/java/org/sonar/java/checks/ThreadAsRunnableArgumentCheck.java
java-checks/src/main/java/org/sonar/java/checks/VarCanBeUsedCheck.java
java-checks/src/main/java/org/sonar/java/checks/tests/NoTestInTestClassCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedMethodParameterCheck.java
java-frontend/src/main/java/org/sonar/java/model/JInitializerBlockSymbol.java
java-frontend/src/main/java/org/sonar/java/model/JMethodSymbol.java
java-frontend/src/main/java/org/sonar/java/model/JUtils.java
java-frontend/src/main/java/org/sonar/java/model/Symbols.java
java-frontend/src/main/java/org/sonar/plugins/java/api/semantic/Symbol.java
java-frontend/src/test/java/org/sonar/java/model/JMethodSymbolTest.java
java-frontend/src/test/java/org/sonar/java/model/JSymbolTest.java
java-frontend/src/test/java/org/sonar/java/model/JUtilsTest.java
java-frontend/src/test/java/org/sonar/java/model/declaration/MethodTreeImplTest.java
java-symbolic-execution/src/main/java/org/sonar/java/se/FlowComputation.java
java-symbolic-execution/src/main/java/org/sonar/java/se/checks/ParameterNullnessCheck.java
java-symbolic-execution/src/main/java/org/sonar/java/se/xproc/BehaviorCache.java
java-symbolic-execution/src/test/java/org/sonar/java/se/ExplodedGraphWalkerTest.java
sonar-java-plugin/src/main/resources/static/documentation.md

SONARJAVA-4700 Update API with methods from JUtils

---

docs/CUSTOM_RULES_101.md
docs/java-custom-rules-example/pom.xml
docs/java-custom-rules-example/pom_SQ_9_9_LTS.xml
its/plugin/plugins/java-extension-plugin/pom.xml
pom.xml
sonar-java-plugin/pom.xml

Update maven packaging plugin, along with the custom rules documentation describing its usage.

SONARJAVA-4740 Support on-demand analyzer downloading

---

java-checks-test-sources/default/src/main/java/symbolicexecution/behaviorcache/CollectionUtilsIsEmpty.java
java-symbolic-execution/src/main/resources/org/sonar/java/se/xproc/org.apache.commons.collections.json
java-symbolic-execution/src/test/java/org/sonar/java/se/xproc/BehaviorCacheTest.java

Internal copy of external PR #4507 from @rguihard

SONARJAVA-4598 - FP on S2259 when CollectionUtils and MapUtils are used from commons3

---

java-checks-test-sources/default/src/main/java/android/hardware/Sensor.java
java-checks-test-sources/default/src/main/java/checks/UseMotionSensorWithoutGyroscopeCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/UseMotionSensorWithoutGyroscopeCheck.java
java-checks/src/test/java/org/sonar/java/checks/UseMotionSensorWithoutGyroscopeCheckTest.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/CheckList.java
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6923.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6923.json

SONARJAVA-4854 Implement S6923: Motion Sensor should not use gyroscope

---

java-checks-test-sources/default/src/main/java/checks/PrintfMisuseCheck.java
java-checks/src/main/java/org/sonar/java/checks/AbstractPrintfChecker.java
java-checks/src/main/java/org/sonar/java/checks/PrintfMisuseCheck.java
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S3457.html

SONARJAVA-4857: FP in S3457 on certain java.util.logging strings with single quotes

---

java-frontend/src/main/java/org/sonar/java/model/JParser.java
java-frontend/src/main/java/org/sonar/java/model/pattern/RecordPatternTreeImpl.java
java-frontend/src/main/java/org/sonar/plugins/java/api/tree/RecordPatternTree.java
java-frontend/src/test/java/org/sonar/java/model/pattern/RecordPatternTreeImplTest.java

SONARJAVA-4909 Missing parentheses in the children() method of RecordPatternTreeImpl

---

java-checks-test-sources/default/src/main/java/checks/CollectorsToListCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/CollectorsToListCheck.java

SONARJAVA-4912 S6204 Change rule definition

---

java-checks/src/main/java/org/sonar/java/checks/SwitchAtLeastThreeCasesCheck.java
java-checks/src/test/files/checks/SwitchAtLeastThreeCasesCheck.java

SONARJAVA-4904 FP on S1301 when using switch statement with type patterns

---

java-checks/src/main/java/org/sonar/java/checks/SwitchAtLeastThreeCasesCheck.java

SONARJAVA-4904 S1301 Fix unused variable

---

java-checks-test-sources/default/src/main/java/checks/RecordPatternInsteadOfFieldAccessCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/RecordPatternInsteadOfFieldAccessCheck.java

SONARJAVA-4837 Fix FP on records with no components

---

java-checks-test-sources/default/src/main/java/checks/RecordPatternInsteadOfFieldAccessCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/RecordPatternInsteadOfFieldAccessCheck.java

SONARJAVA-4837 S6878 Fix FP on record methods

---

java-checks/src/main/java/org/sonar/java/checks/RedundantJumpCheck.java
java-checks/src/test/files/checks/RedundantJumpCheck.java

Fix S3626 looping on CFG block circles

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S5693.json
java-checks-test-sources/default/src/main/java/checks/security/ExcessiveContentRequestCheck/ExcessiveContentRequestCheck_max8000000.java
java-checks/src/main/java/org/sonar/java/checks/security/ExcessiveContentRequestCheck.java

SONARJAVA-4885 S5693 add support for .setMaxFileSize(DataSize.of)

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S5804.json
java-checks-test-sources/default/pom.xml
java-checks-test-sources/default/src/main/java/checks/security/UserEnumerationCheck.java
java-checks/src/main/java/org/sonar/java/checks/security/UserEnumerationCheck.java

SONARJAVA-4880 S5804: Support detection of User Enumeration for Spring

---

its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
its/autoscan/src/test/resources/autoscan/diffs/diff_S1068.json
java-checks-test-sources/default/src/main/java/checks/unused/UnusedPrivateFieldLombok.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedPrivateFieldCheck.java
java-checks/src/test/java/org/sonar/java/checks/unused/UnusedPrivateFieldCheckTest.java

SONARJAVA-4933 S1068 add support for lombok class annotations

---

java-jsp/src/main/java/org/sonar/java/jsp/Jasper.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java

This PR fixes [the first comment on SONARJAVA-4934](https://sonarsource.atlassian.net/browse/SONARJAVA-4934?focusedCommentId=600712)

SONARJAVA-4934 JavaSensor should be executed on jsp files even without java files

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S2699.json
java-checks-test-sources/default/pom.xml
java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/SpringBootSanityJ4Test.java
java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/SpringBootSanityTestSample.java
java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertionsInTestsCheck.java
java-checks/src/test/java/org/sonar/java/checks/tests/AssertionsInTestsCheckTest.java

SONARJAVA-4944 S2699 should not raise on SpringBoot empty sanity test

---

java-checks/src/main/java/org/sonar/java/filters/BaseTreeVisitorIssueFilter.java

[NO JIRA] Fix code smell

---

docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[NO JIRA] Prepare for next development iteration 8.0.0-SNAPSHOT

---

docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[NO JIRA] Prepare next development iteration 8.1.0-SNAPSHOT

---

docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

SONARJAVA-5032 Prepare release to patch SE plugin artifact naming

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[NO JIRA] Prepare next development iteration 8.2.0

---

java-checks-test-sources/default/src/main/java/checks/CollectorsToListCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/CollectorsToListCheck.java

SONARJAVA-4950 Fix S6204 IndexOutOfBoundsException when lombok.val is used

---

java-checks-test-sources/default/src/main/java/checks/OneDeclarationPerLineCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/OneDeclarationPerLineCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/QuickFixHelper.java
java-frontend/src/main/java/org/sonar/java/model/JavaTree.java
java-frontend/src/test/java/org/sonar/java/model/JavaTreeModelTest.java

SONARJAVA-5080 S1659: Quickfix breaks syntax when multiple arrays are declared

---

java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/CheckOtherwiseString/IssueStringMyObject.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/CheckOtherwiseString/IssueStringService.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/CheckOtherwiseString/VisibleForTesting.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/IssueMyObject.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/IssueService.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/MyObject.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/Service.java
java-checks-test-sources/default/src/main/java/checks/VisibleForTestingProtectedUsageCheck/VisibleForTesting.java
java-checks/src/main/java/org/sonar/java/checks/VisibleForTestingUsageCheck.java
java-checks/src/test/java/org/sonar/java/checks/VisibleForTestingUsageCheckTest.java

When using (otherwise = androidx.annotation.VisibleForTesting.PROTECTED).

SONARJAVA-5115 FP in S5803: when using (VisibleForTesting.PROTECTED)

---

sonar-java-plugin/src/main/resources/static/documentation.md

SONARJAVA-5020 Clarify documentation about sonar.java.skipUnchanged

---

java-checks-test-sources/default/src/main/java/checks/SingleIfInsteadOfPatternMatchGuardCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/CollapsibleIfCandidateCheck.java
java-checks/src/main/java/org/sonar/java/checks/SingleIfInsteadOfPatternMatchGuardCheck.java
java-checks/src/main/java/org/sonar/java/checks/helpers/QuickFixHelper.java
java-checks/src/test/java/org/sonar/java/checks/helpers/QuickFixHelperTest.java

SONARJAVA-4961 Fix S6916 quickfix parenthesis on conditional expressions

---

java-jsp/pom.xml

Remove vulnerable dependency tomcat-embed-jasper

---

docs/CUSTOM_RULES_101.md
docs/java-custom-rules-example/pom_SQ_10_6_LATEST.xml

[NO JIRA] Update targeted SQ and SonarJava plugin versions for CustomRules101

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[SONARJAVA-5154](https://sonarsource.atlassian.net/browse/SONARJAVA-5154)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last …

SONARJAVA-5154 Add Jira integration

---

.cirrus.star

[SONARJAVA-5161](https://sonarsource.atlassian.net/browse/SONARJAVA-5161)
[SONARJAVA-5161]: https://sonarsource.atlassian.net/browse/SONARJAVA-5161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5161 Upgrade cirrus-modules to v3

---

.github/workflows/ToggleLockBranch.yml

[SONARJAVA-5170](https://sonarsource.atlassian.net/browse/SONARJAVA-5170)
To review - make sure that 
* there's only one file
* the file is the same as [ToggleLockBranch.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/ToggleLockBranch.yml)
* The slack channel on the last line is correct for this repo
[SONARJAVA-5170]: https://sonarsource.atlassian.net/browse/SONARJAVA-5170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5170 Add ToggleLockBranch.yml

---

.github/workflows/mark-prs-stale.yml

[SONARJAVA-5168](https://sonarsource.atlassian.net/browse/SONARJAVA-5168)
[SONARJAVA-5168]: https://sonarsource.atlassian.net/browse/SONARJAVA-5168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5168 Add automation to mark and close stale PRs

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5183](https://sonarsource.atlassian.net/browse/SONARJAVA-5183)
[SONARJAVA-5183]: https://sonarsource.atlassian.net/browse/SONARJAVA-5183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5183 Prepare for next development iteration 8.7.0-SNAPSHOT

---

java-frontend/src/main/java/org/sonar/java/SonarComponents.java
java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java

[SONARJAVA-4983](https://sonarsource.atlassian.net/browse/SONARJAVA-4983)
[SONARJAVA-4983]: https://sonarsource.atlassian.net/browse/SONARJAVA-4983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4983 improve logging for partial analysis

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5225](https://sonarsource.atlassian.net/browse/SONARJAVA-5225)
[SONARJAVA-5225]: https://sonarsource.atlassian.net/browse/SONARJAVA-5225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5225 Prepare next development iteration 8.8

---

its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
its/autoscan/src/test/resources/autoscan/diffs/diff_S1874.json
its/autoscan/src/test/resources/autoscan/diffs/diff_S2245.json
its/autoscan/src/test/resources/autoscan/diffs/diff_S2440.json
java-checks-test-sources/default/pom.xml
java-checks-test-sources/default/src/main/java/checks/PseudoRandomCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/PseudoRandomCheck.java

[SONARJAVA-5134](https://sonarsource.atlassian.net/browse/SONARJAVA-5134)
[SONARJAVA-5134]: https://sonarsource.atlassian.net/browse/SONARJAVA-5134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5134 S2245 considers RandomStringUtils.secure|secureStrong as safe

---

java-checks/src/test/files/filters/LombokFilterWithoutSemantic.java
java-checks/src/test/java/org/sonar/java/filters/EclipseI18NFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/FilterVerifier.java
java-checks/src/test/java/org/sonar/java/filters/FilterVerifierTest.java
java-checks/src/test/java/org/sonar/java/filters/GeneratedCodeFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/GoogleAutoFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/LombokFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/SpringFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/SuppressWarningFilterTest.java

[SONARJAVA-5241](https://sonarsource.atlassian.net/browse/SONARJAVA-5241)
https://sonarsource.atlassian.net/browse/SONARJAVA-4973
[SONARJAVA-5241]: https://sonarsource.atlassian.net/browse/SONARJAVA-5241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5241 Fix Lombok FPs in automatic analysis

---

java-checks-test-sources/default/src/main/java/checks/HardcodedURICheckSample.java
java-checks/src/main/java/org/sonar/java/checks/HardcodedURICheck.java

[SONARJAVA-5149](https://sonarsource.atlassian.net/browse/SONARJAVA-5149)
Part of 
[SONARJAVA-5149]: https://sonarsource.atlassian.net/browse/SONARJAVA-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5149 report issues with path delimiters in variable declaration

---

sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1075.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S115.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1190.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1451.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1751.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1948.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2077.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S3749.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S3981.json
sonarpedia.json

[SONARJAVA-5523](https://sonarsource.atlassian.net/browse/SONARJAVA-5523)

SONARJAVA-5523 Update rule metadata

---

sonarpedia.json

[SONARJAVA-5268](https://sonarsource.atlassian.net/browse/SONARJAVA-5268)
[SONARJAVA-5268]: https://sonarsource.atlassian.net/browse/SONARJAVA-5268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5268 Update rule metadata

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5270](https://sonarsource.atlassian.net/browse/SONARJAVA-5270)
[SONARJAVA-5270]: https://sonarsource.atlassian.net/browse/SONARJAVA-5270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5270 Prepare for next development iteration 8.10.0-SNAPSHOT

---

.cirrus.yml

[SONARJAVA-5272](https://sonarsource.atlassian.net/browse/SONARJAVA-5272)
[SONARJAVA-5272]: https://sonarsource.atlassian.net/browse/SONARJAVA-5272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5272 Increase CI memory to support new SQS version and prevent OOMKilled

---

its/plugin/tests/src/test/java/com/sonar/it/java/suite/SonarLintTest.java
pom.xml

[SONARJAVA-5299](https://sonarsource.atlassian.net/browse/SONARJAVA-5299)
[SONARJAVA-5299]: https://sonarsource.atlassian.net/browse/SONARJAVA-5299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5299 Upgrade SonarLintTest ITs to use sonarlint-plugin-api 10.13

---

its/plugin/tests/src/test/java/com/sonar/it/java/suite/SonarLintTest.java

[SONARJAVA-5299](https://sonarsource.atlassian.net/browse/SONARJAVA-5299)
[SONARJAVA-5299]: https://sonarsource.atlassian.net/browse/SONARJAVA-5299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5299 Fix issues from review

---

java-frontend/src/main/java/org/sonar/java/model/JavaVersionImpl.java
java-frontend/src/test/java/org/sonar/java/model/JParserConfigTest.java
java-frontend/src/test/java/org/sonar/java/model/JavaVersionImplTest.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java

[SONARJAVA-5297](https://sonarsource.atlassian.net/browse/SONARJAVA-5297)
[SONARJAVA-5297]: https://sonarsource.atlassian.net/browse/SONARJAVA-5297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5297 Refactor JavaVersionImpl.fromStrings()

---

java-surefire/src/main/java/org/sonar/plugins/surefire/SurefireExtensions.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/ExternalReportExtensions.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaPlugin.java

[SONARJAVA-5309](https://sonarsource.atlassian.net/browse/SONARJAVA-5309)
[SONARJAVA-5309]: https://sonarsource.atlassian.net/browse/SONARJAVA-5309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5309 Replace deprecated Qualifiers API

---

its/ruling/src/test/resources/guava/java-S125.json
java-checks-test-sources/default/src/main/java/checks/CommentedCode.java
java-checks/src/main/java/org/sonar/java/checks/CommentedOutCodeLineCheck.java

[SONARJAVA-5273](https://sonarsource.atlassian.net/browse/SONARJAVA-5273)
[SONARJAVA-5273]: https://sonarsource.atlassian.net/browse/SONARJAVA-5273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5273 FP for S125 for Apache 2.0 license header

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S6809.json
java-checks-test-sources/default/src/main/java/checks/spring/AsyncMethodsCalledViaThisCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/spring/AsyncMethodsCalledViaThisCheck.java

[SONARJAVA-5327](https://sonarsource.atlassian.net/browse/SONARJAVA-5327)
[SONARJAVA-5327]: https://sonarsource.atlassian.net/browse/SONARJAVA-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5327 S6809 support @Cacheable methods

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S5838.json
its/ruling/src/test/resources/sonar-server/java-S5838.json
java-checks-test-sources/default/src/test/java/checks/tests/AssertJChainSimplificationCheckTest.java
java-checks-test-sources/default/src/test/java/checks/tests/AssertJChainSimplificationCheckTest_QuickFix.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertJChainSimplificationIndex.java

[SONARJAVA-4954](https://sonarsource.atlassian.net/browse/SONARJAVA-4954)
[SONARJAVA-4954]: https://sonarsource.atlassian.net/browse/SONARJAVA-4954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4954 FP in S5838: Don't report when there may be ambiguity

---

java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java

[SONARJAVA-5334](https://sonarsource.atlassian.net/browse/SONARJAVA-5334)
Remove unused import.
[SONARJAVA-5334]: https://sonarsource.atlassian.net/browse/SONARJAVA-5334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5334 Fix quality flaw

---

java-frontend/src/main/java/org/sonar/plugins/java/api/IssuableSubscriptionVisitor.java
java-frontend/src/test/java/org/sonar/plugins/java/api/IssuableSubscriptionVisitorTest.java
java-frontend/src/test/resources/IssuableSubscriptionClass.java
sonar-java-plugin/src/main/resources/static/documentation.md

[SONARJAVA-5335](https://sonarsource.atlassian.net/browse/SONARJAVA-5335)
[SONARJAVA-5335]: https://sonarsource.atlassian.net/browse/SONARJAVA-5335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5335 Add IssuableSubscriptionVisitor#reportIssue(startTree, endTree, msg, flow, cost) API

---

README.md

[SONARJAVA-5332](https://sonarsource.atlassian.net/browse/SONARJAVA-5332)
[SONARJAVA-5332]: https://sonarsource.atlassian.net/browse/SONARJAVA-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5332 Update links and references in README

---

README.md

[SONARJAVA-5332](https://sonarsource.atlassian.net/browse/SONARJAVA-5332)
[SONARJAVA-5332]: https://sonarsource.atlassian.net/browse/SONARJAVA-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5332 Update README link to point at sonarsource.com

---

its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
its/autoscan/src/test/resources/autoscan/diffs/diff_S1068.json
java-checks-test-sources/default/src/main/java/checks/unused/UnusedPrivateFieldCheck.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedPrivateFieldCheck.java
java-checks/src/test/java/org/sonar/java/checks/unused/UnusedPrivateFieldCheckTest.java

[SONARJAVA-5336](https://sonarsource.atlassian.net/browse/SONARJAVA-5336)
[SONARJAVA-5336]: https://sonarsource.atlassian.net/browse/SONARJAVA-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5336 S1068 Fix FP with @Getter and @Setter annotations in automatic analysis

---

java-checks-test-sources/default/src/main/java/checks/spring/CacheAnnotationsShouldOnlyBeAppliedToConcreteClassesCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/spring/CacheAnnotationsShouldOnlyBeAppliedToConcreteClassesCheck.java

[SONARJAVA-5318](https://sonarsource.atlassian.net/browse/SONARJAVA-5318)
[SONARJAVA-5318]: https://sonarsource.atlassian.net/browse/SONARJAVA-5318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5318 modify S7180 to not raise in interface annotated with spring data repository

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S6856.json
java-checks-test-sources/default/src/main/java/checks/spring/MissingPathVariableAnnotationCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/spring/MissingPathVariableAnnotationCheck.java

[SONARJAVA-5324](https://sonarsource.atlassian.net/browse/SONARJAVA-5324)
[SONARJAVA-5324]: https://sonarsource.atlassian.net/browse/SONARJAVA-5324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5324 FP, modify S6856 to support PatchMapping annotation

---

sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S4426.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5332.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6293.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6809.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S6856.html
sonarpedia.json

[SONARJAVA-5254](https://sonarsource.atlassian.net/browse/SONARJAVA-5254)
[SONARJAVA-5254]: https://sonarsource.atlassian.net/browse/SONARJAVA-5254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5254 Update RSPEC before 8.10 release

---

external-reports/src/main/resources/org/sonar/l10n/java/rules/spotbugs/spotbugs-rules.json

[SONARJAVA-5342](https://sonarsource.atlassian.net/browse/SONARJAVA-5342)
[SONARJAVA-5342]: https://sonarsource.atlassian.net/browse/SONARJAVA-5342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5342 Update spotbugs rules

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5345](https://sonarsource.atlassian.net/browse/SONARJAVA-5345)
[SONARJAVA-5345]: https://sonarsource.atlassian.net/browse/SONARJAVA-5345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5345 Prepare for next development iteration 8.11.0-SNAPSHOT

---

java-jsp/pom.xml

[SONARJAVA-5357](https://sonarsource.atlassian.net/browse/SONARJAVA-5357)
Part of 
[SONARJAVA-5357]: https://sonarsource.atlassian.net/browse/SONARJAVA-5357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5357 bump tomcat-embed-jasper to 9.0.100

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5372](https://sonarsource.atlassian.net/browse/SONARJAVA-5372)
[SONARJAVA-5372]: https://sonarsource.atlassian.net/browse/SONARJAVA-5372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5372 Prepare next development iteration 8.9.2-SNAPSHOT

---

java-checks-test-sources/default/src/main/java/checks/DateFormatWeekYearCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/DateFormatWeekYearCheck.java

[SONARJAVA-5375](https://sonarsource.atlassian.net/browse/SONARJAVA-5375)
[SONARJAVA-5375]: https://sonarsource.atlassian.net/browse/SONARJAVA-5375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5375 S3986 Update the message to use the year instead of the week year.

---

java-frontend/src/main/java/org/sonar/java/classpath/DependencyVersionInference.java
java-frontend/src/main/java/org/sonar/java/classpath/Version.java
java-frontend/src/main/java/org/sonar/java/model/DefaultModuleScannerContext.java
java-frontend/src/test/java/org/sonar/java/classpath/DependencyVersionInferenceTest.java
java-frontend/src/test/java/org/sonar/java/model/DefaultModuleScannerContextTest.java

[SONARJAVA-5391](https://sonarsource.atlassian.net/browse/SONARJAVA-5391)
Part of

SONARJAVA-5391 Add implementations to infer library versions by name or using MANIFEST

---

.github/workflows/PullRequestClosed.yml

[SONARJAVA-5393](https://sonarsource.atlassian.net/browse/SONARJAVA-5393)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SONARJAVA-5393]: https://sonarsource.atlassian.net/browse/SONARJAVA-5393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5393 Autoclose issues created by Jira integration

---

java-checks/src/main/java/org/sonar/java/filters/GeneratedCodeFilter.java
java-checks/src/test/files/filters/GeneratedCodeFilter.java

[SONARJAVA-5404](https://sonarsource.atlassian.net/browse/SONARJAVA-5404)
[SONARJAVA-5404]: https://sonarsource.atlassian.net/browse/SONARJAVA-5404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5404 GeneratedCodeFilter should support jakarta annotations

---

java-checks-test-sources/default/src/main/java/checks/TooManyParametersCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/TooManyParametersCheck.java

[SONARJAVA-4567](https://sonarsource.atlassian.net/browse/SONARJAVA-4567)
[SONARJAVA-4567]: https://sonarsource.atlassian.net/browse/SONARJAVA-4567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4567 S107 allow long argument lists with @lombok.Builder and Spring @Autowired

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5415](https://sonarsource.atlassian.net/browse/SONARJAVA-5415)
Part of 
[SONARJAVA-5415]: https://sonarsource.atlassian.net/browse/SONARJAVA-5415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5415 Prepare next development iteration

---

its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
its/autoscan/src/test/resources/autoscan/diffs/diff_S1128.json
its/autoscan/src/test/resources/autoscan/diffs/diff_S6204.json

[SONARJAVA-5452](https://sonarsource.atlassian.net/browse/SONARJAVA-5452)
no real difference
Part of 
[SONARJAVA-5452]: https://sonarsource.atlassian.net/browse/SONARJAVA-5452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5452 update autoscan differences

---

.cirrus.yml
.cirrus/Dockerfile.jdk17AndLatest
.cirrus/install-latest-java-on-windows.ps1
its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
its/autoscan/src/test/resources/autoscan/diffs/diff_S5738.json
java-checks-test-sources/aws/src/main/java/checks/aws/AwsReusableResourcesInitializedOnceCheckSample.java
java-checks-test-sources/default/pom.xml
java-checks-test-sources/default/src/main/java/checks/DisallowedThreadGroupCheck.java
java-checks-test-sources/java-17/src/main/java/checks/DisallowedThreadGroupCheck.java
java-checks-test-sources/spring-3.2/pom.xml
java-frontend/src/main/java/org/sonar/java/model/JavaVersionImpl.java
java-frontend/src/main/java/org/sonar/plugins/java/api/JavaVersion.java
java-frontend/src/test/java/org/sonar/java/CommonsCollectionsTest.java
java-frontend/src/test/java/org/sonar/java/model/JavaVersionImplTest.java
java-symbolic-execution/java-symbolic-execution-plugin/src/test/java/org/sonar/java/se/ExplodedGraphWalkerTest.java

[SONARJAVA-5456](https://sonarsource.atlassian.net/browse/SONARJAVA-5456)
[SONARJAVA-5456]: https://sonarsource.atlassian.net/browse/SONARJAVA-5456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5456 Set max supported java version to 23 and build with java 23

---

sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S104.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S110.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1200.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1217.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1313.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S138.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1448.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S1541.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2972.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S3776.json
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5332.html
sonarpedia.json

[SONARJAVA-5479](https://sonarsource.atlassian.net/browse/SONARJAVA-5479)
[SONARJAVA-5479]: https://sonarsource.atlassian.net/browse/SONARJAVA-5479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5479 Update rules metadata

---

java-checks/src/main/java/org/sonar/java/checks/BoxedBooleanExpressionsCheck.java

[SONARJAVA-5484](https://sonarsource.atlassian.net/browse/SONARJAVA-5484)
[SONARJAVA-5484]: https://sonarsource.atlassian.net/browse/SONARJAVA-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5484 Address FIXME comment about the use of IdentityHashMap

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S1481.json
java-checks-test-sources/default/src/main/java/checks/unused/UnusedLocalVariableCheck.java
java-checks-test-sources/default/src/main/java/checks/unused/UnusedLocalVariableCheck_java22.java
java-checks-test-sources/default/src/main/java/checks/unused/UnusedLocalVariableCheck_withLambda.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedLocalVariableCheck.java
java-checks/src/test/java/org/sonar/java/checks/unused/UnusedLocalVariableCheckTest.java

[SONARJAVA-5485](https://sonarsource.atlassian.net/browse/SONARJAVA-5485)
[SONARJAVA-5485]: https://sonarsource.atlassian.net/browse/SONARJAVA-5485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5485 S1481: Report on unnamed variables in try with resources

---

java-checks/src/main/java/org/sonar/java/checks/helpers/UnresolvedIdentifiersVisitor.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedLocalVariableCheck.java

[SONARJAVA-5504](https://sonarsource.atlassian.net/browse/SONARJAVA-5504)
[SONARJAVA-5504]: https://sonarsource.atlassian.net/browse/SONARJAVA-5504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5504 Some documentation to explain the behavior of the UnusedLocalVariableCheck in unresolved variable cases

---

pom.xml

[SONARJAVA-5486](https://sonarsource.atlassian.net/browse/SONARJAVA-5486)
[SONARJAVA-5486]: https://sonarsource.atlassian.net/browse/SONARJAVA-5486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5486 Bump orchestrator version to 5.5

---

README.md

[SONARJAVA-5511](https://sonarsource.atlassian.net/browse/SONARJAVA-5511)
There were some incorrectness concerning java-checks-test-sources.
[SONARJAVA-5511]: https://sonarsource.atlassian.net/browse/SONARJAVA-5511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5511 Update required Java version and test source folder in README

---

sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2053.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2092.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2184.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2226.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2254.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2612.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2647.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2696.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2885.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2886.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S3330.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S4502.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S4830.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5332.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5344.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5443.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5445.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5527.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5547.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5876.html
sonarpedia.json

[SONARJAVA-5521](https://sonarsource.atlassian.net/browse/SONARJAVA-5521)
Part of 
[SONARJAVA-5521]: https://sonarsource.atlassian.net/browse/SONARJAVA-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5521 Update rules metadata

---

.github/workflows/PrepareNextIteration.yml

[SONARJAVA-5514](https://sonarsource.atlassian.net/browse/SONARJAVA-5514)
[SONARJAVA-5514]: https://sonarsource.atlassian.net/browse/SONARJAVA-5514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5514 Create GitHub action for updating the next development iteration.

---

java-checks-test-sources/default/src/main/java/checks/RedundantRecordMethodsCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/RedundantRecordMethodsCheck.java
java-checks/src/test/java/org/sonar/java/checks/RedundantRecordMethodsCheckTest.java

[SONARJAVA-4481](https://sonarsource.atlassian.net/browse/SONARJAVA-4481)
[SONARJAVA-4481]: https://sonarsource.atlassian.net/browse/SONARJAVA-4481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4481 S6207: Fix FP when a constructor in a record is annotated

---

java-checks-test-sources/default/src/main/java/checks/RedundantRecordMethodsCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/RedundantRecordMethodsCheck.java

[SONARJAVA-4334](https://sonarsource.atlassian.net/browse/SONARJAVA-4334)
With the changes in this PR, we more precisely keep track of which component was assigned to what parameter and whether the parameter was changed by the execution of the constructor.
[SONARJAVA-4334]: https://sonarsource.atlassian.net/browse/SONARJAVA-4334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4334 Fix FP in S6207, in case where parameter was changed in constructor

---

java-checks/src/main/java/org/sonar/java/checks/VariableDeclarationScopeCheck.java
java-checks/src/test/files/checks/VariableDeclarationScopeCheck.java

[SONARJAVA-4964](https://sonarsource.atlassian.net/browse/SONARJAVA-4964)
[SONARJAVA-4964]: https://sonarsource.atlassian.net/browse/SONARJAVA-4964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4964 Fix FP by handling case of Unknown symbol referencing declared variable

---

its/ruling/src/test/resources/commons-beanutils/java-S2384.json
its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S2384.json
its/ruling/src/test/resources/eclipse-jetty/java-S2384.json
its/ruling/src/test/resources/guava/java-S2384.json
its/ruling/src/test/resources/sonar-server/java-S2384.json
java-checks-test-sources/default/src/main/java/checks/MutableMembersUsageCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/MutableMembersUsageCheck.java

[SONARJAVA-4473](https://sonarsource.atlassian.net/browse/SONARJAVA-4473)
To reduce false positives, we only consider non-private methods.
[SONARJAVA-4473]: https://sonarsource.atlassian.net/browse/SONARJAVA-4473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4473 fix FP in S2384 when mutable value is stored by private methods or constructors

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S2699.json
java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/ForeignNonAssertingContextConsumer.java
java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/SpringBootAppContextRunnerSample.java
java-checks/src/main/java/org/sonar/java/checks/tests/AssertionsInTestsCheck.java
java-checks/src/test/java/org/sonar/java/checks/tests/AssertionsInTestsCheckTest.java

[SONARJAVA-5480](https://sonarsource.atlassian.net/browse/SONARJAVA-5480)
Part of 
[SONARJAVA-5480]: https://sonarsource.atlassian.net/browse/SONARJAVA-5480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5480 S2699 recognizes SpringBoot AssertableApplicationContext

---

wss-unified-agent.config

[SONARJAVA-5541](https://sonarsource.atlassian.net/browse/SONARJAVA-5541)
[SONARJAVA-5541]: https://sonarsource.atlassian.net/browse/SONARJAVA-5541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5541 Ignore its/plugin/projects in Mend scan

---

its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S2384.json
its/ruling/src/test/resources/eclipse-jetty/java-S2384.json
its/ruling/src/test/resources/guava/java-S2384.json
its/ruling/src/test/resources/sonar-server/java-S2384.json
java-checks-test-sources/default/src/main/java/checks/MutableMembersUsageCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/MutableMembersUsageCheck.java
java-checks/src/test/java/org/sonar/java/checks/MutableMembersUsageCheckTest.java

[SONARJAVA-4473](https://sonarsource.atlassian.net/browse/SONARJAVA-4473)
This is to be more precise and avoid false positives where the storage only happens in private methods, and calls to this private methods by public ones are protected in some way.
[SONARJAVA-4473]: https://sonarsource.atlassian.net/browse/SONARJAVA-4473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4473 Check that mutable member storage is reachable by public calls

---

java-checks-test-sources/default/src/main/java/checks/DefaultInitializedFieldCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
java-frontend/src/main/java/org/sonar/java/model/LiteralUtils.java
java-frontend/src/test/java/org/sonar/java/model/LiteralUtilsTest.java

[SONARJAVA-5524](https://sonarsource.atlassian.net/browse/SONARJAVA-5524)
Part of 
[SONARJAVA-5524]: https://sonarsource.atlassian.net/browse/SONARJAVA-5524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5522 DefaultInitializedFieldCheck handles underscores in float/double

---

java-checks-test-sources/default/src/main/java/checks/DefaultInitializedFieldCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
java-frontend/src/main/java/org/sonar/java/model/LiteralUtils.java
java-frontend/src/test/java/org/sonar/java/model/LiteralUtilsTest.java

[SONARJAVA-5522](https://sonarsource.atlassian.net/browse/SONARJAVA-5522)
This reverts commit 51b1dde04cc28fdacb1a9359671da30de269606c.
Part of 
[SONARJAVA-5522]: https://sonarsource.atlassian.net/browse/SONARJAVA-5522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "SONARJAVA-5522 DefaultInitializedFieldCheck handles underscores in float/double (#5116)"

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S1874.json
java-checks-test-sources/default/src/main/java/checks/DefaultEncodingUsageCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/DefaultEncodingUsageCheck.java

[SONARJAVA-5552](https://sonarsource.atlassian.net/browse/SONARJAVA-5552)
[SONARJAVA-5552]: https://sonarsource.atlassian.net/browse/SONARJAVA-5552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5552 Fix FN in S1943 on method references.

---

its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S1854.json
its/ruling/src/test/resources/eclipse-jetty/java-S1854.json
java-checks-test-sources/default/src/main/java/checks/DeadStoreCheckBrokenSemantic.java
java-checks-test-sources/default/src/main/java/checks/DeadStoreCheckSample.java
java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/CheckVerifier.java
java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifier.java
java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/JavaCheckVerifier.java
java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifierTest.java
java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/JavaCheckVerifierTest.java
java-checks/src/main/java/org/sonar/java/checks/DeadStoreCheck.java
java-checks/src/test/java/org/sonar/java/checks/DeadStoreCheckTest.java
java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
java-frontend/src/test/java/org/sonar/java/ast/JavaAstScannerTest.java
java-symbolic-execution/java-symbolic-execution-plugin/src/test/java/org/sonar/java/se/SECheckVerifier.java

[SONARJAVA-5482](https://sonarsource.atlassian.net/browse/SONARJAVA-5482)
Part of 
[SONARJAVA-5482]: https://sonarsource.atlassian.net/browse/SONARJAVA-5482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5482 stop raising issues if variable or identifier symbol is unknown

---

java-checks-test-sources/default/src/main/java/checks/MissingDeprecatedCheckMarkdownSample.java
java-checks/src/test/java/org/sonar/java/checks/MissingDeprecatedCheckTest.java

[SONARJAVA-5445](https://sonarsource.atlassian.net/browse/SONARJAVA-5445)
[SONARJAVA-5445]: https://sonarsource.atlassian.net/browse/SONARJAVA-5445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5445 S1123 Add tests for markdown JavaDoc

---

java-checks-test-sources/default/src/main/java/checks/CommentedCode.java

[SONARJAVA-5377](https://sonarsource.atlassian.net/browse/SONARJAVA-5377)
[SONARJAVA-5377]: https://sonarsource.atlassian.net/browse/SONARJAVA-5377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5377 S125 Add tests with Markdown comments

---

.github/workflows/UpdateRuleMetadata.yml

[SONARJAVA-5563](https://sonarsource.atlassian.net/browse/SONARJAVA-5563)
SONARJAVA-5563
[SONARJAVA-5563]: https://sonarsource.atlassian.net/browse/SONARJAVA-5563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5563 Use the latest version of com.sonarsource.rule-api:rule-api in the UpdateRuleMetadata GitHub action

---

java-checks-test-sources/default/src/main/java/checks/DefaultInitializedFieldCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
java-frontend/src/main/java/org/sonar/java/model/LiteralUtils.java
java-frontend/src/test/java/org/sonar/java/model/LiteralUtilsTest.java

[SONARJAVA-5522](https://sonarsource.atlassian.net/browse/SONARJAVA-5522)
Part of 
[SONARJAVA-5522]: https://sonarsource.atlassian.net/browse/SONARJAVA-5522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5522 Let DefaultInitializedFieldCheck handle underscores in float/double literals [DO NOT squash]

---

java-checks/src/main/java/org/sonar/java/checks/MutableMembersUsageCheck.java

[SONARJAVA-5567](https://sonarsource.atlassian.net/browse/SONARJAVA-5567)
[SONARJAVA-5567]: https://sonarsource.atlassian.net/browse/SONARJAVA-5567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5567 Fix failing Quality Gate: remove unused field.

---

java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S2095.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S2189.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S2689.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S2755.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S3516.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S3546.json
java-symbolic-execution/java-symbolic-execution-plugin/src/main/resources/org/sonar/l10n/java/rules/javase/S6373.json
java-symbolic-execution/sonarpedia.json
sonarpedia.json

[SONARJAVA-5352](https://sonarsource.atlassian.net/browse/SONARJAVA-5352)
[SONARJAVA-5352]: https://sonarsource.atlassian.net/browse/SONARJAVA-5352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5352 Fix discrepancies between MQR and severity for Java rules

---

.github/workflows/UpdateRuleMetadata.yml

[SONARJAVA-5574](https://sonarsource.atlassian.net/browse/SONARJAVA-5574)
[SONARJAVA-5574]: https://sonarsource.atlassian.net/browse/SONARJAVA-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5574 Fix UpdateRuleMetadata GitHub action to also update the sonar-java-symbolic-execution-plugin rules

---

java-checks/src/main/java/org/sonar/java/checks/RedundantJumpCheck.java
java-checks/src/test/files/checks/RedundantJumpCheck.java

[SONARJAVA-5630](https://sonarsource.atlassian.net/browse/SONARJAVA-5630)
[SONARJAVA-5630]: https://sonarsource.atlassian.net/browse/SONARJAVA-5630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5630 Check that iterator contains a next element before calling next

---

java-checks-test-sources/default/src/main/java/checks/unused/UnusedStringBuilderCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/unused/UnusedStringBuilderCheck.java

[SONARJAVA-5598](https://sonarsource.atlassian.net/browse/SONARJAVA-5598)
[SONARJAVA-5598]: https://sonarsource.atlassian.net/browse/SONARJAVA-5598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5598 S3063: Fix additional FPs on charAt, methodRef, and arrays

---

java-frontend/pom.xml

[SONARJAVA-5615](https://sonarsource.atlassian.net/browse/SONARJAVA-5615)
[SONARJAVA-5615]: https://sonarsource.atlassian.net/browse/SONARJAVA-5615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5615 Update jdt-package version to 1.6.0.160

---

check-list/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/projects/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5651](https://sonarsource.atlassian.net/browse/SONARJAVA-5651)
[SONARJAVA-5651]: https://sonarsource.atlassian.net/browse/SONARJAVA-5651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5651 org.sonarsource.java:java-extension-plugin should comply with maven central requirements

---

java-frontend/src/main/java/org/sonar/java/BatchGenerator.java
java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
java-frontend/src/test/java/org/sonar/java/BatchGeneratorTest.java
java-frontend/src/test/java/org/sonar/java/InputFileUtils.java
java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java

[SONARJAVA-5655](https://sonarsource.atlassian.net/browse/SONARJAVA-5655)
[SONARJAVA-5655]: https://sonarsource.atlassian.net/browse/SONARJAVA-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5655 Extract BatchGenerator into a top-level class.

---

java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifier.java
java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/JavaCheckVerifier.java
java-checks/src/test/java/org/sonar/java/checks/ParsingErrorCheckTest.java
java-checks/src/test/java/org/sonar/java/filters/AnyRuleIssueFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/BaseTreeVisitorIssueFilterTest.java
java-checks/src/test/java/org/sonar/java/filters/FilterVerifier.java
java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
java-frontend/src/main/java/org/sonar/java/testing/VisitorsBridgeForTests.java
java-frontend/src/test/java/org/sonar/java/testing/VisitorsBridgeForTestsTest.java
java-frontend/src/test/java/org/sonar/plugins/java/api/IssuableSubscriptionVisitorTest.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/SanityTest.java

[SONARJAVA-5659](https://sonarsource.atlassian.net/browse/SONARJAVA-5659)
[SONARJAVA-5659]: https://sonarsource.atlassian.net/browse/SONARJAVA-5659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5659 Make inAndroidContext final

---

java-checks-aws/src/main/resources/org/sonar/java/checks/security/S6437-methods.json
java-checks-aws/src/test/java/org/sonar/java/checks/security/HardCodedCredentialsShouldNotBeUsedCheckTest.java

[SONARJAVA-5662](https://sonarsource.atlassian.net/browse/SONARJAVA-5662)
Part of 
[SONARJAVA-5662]: https://sonarsource.atlassian.net/browse/SONARJAVA-5662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5662 S6437 Remove an FP-prone signature

---

pom.xml

[SONARJAVA-5663](https://sonarsource.atlassian.net/browse/SONARJAVA-5663)
[SONARJAVA-5663]: https://sonarsource.atlassian.net/browse/SONARJAVA-5663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5663 Upgrade analyzer-commons to 2.18.0.3393

---

java-checks-test-sources/default/src/main/files/non-compiling/checks/OSCommandsPath.java
java-checks-test-sources/default/src/main/java/checks/OSCommandsPath.java
java-checks/src/main/java/org/sonar/java/checks/OSCommandsPathCheck.java

[SONARJAVA-5665](https://sonarsource.atlassian.net/browse/SONARJAVA-5665)
Part of

SONARJAVA-5665 Improve S4036 message for users

---

java-checks-test-sources/default/src/main/java/checks/ClassNameInClassTransformCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/ClassNameInClassTransformCheck.java

[SONARJAVA-5661](https://sonarsource.atlassian.net/browse/SONARJAVA-5661)
[SONARJAVA-5661]: https://sonarsource.atlassian.net/browse/SONARJAVA-5661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5494 Add quickfixes for S7477

---

sonar-java-plugin/src/test/java/org/sonar/plugins/java/MetadataTest.java

[SONARJAVA-5682](https://sonarsource.atlassian.net/browse/SONARJAVA-5682)
[SONARJAVA-5682]: https://sonarsource.atlassian.net/browse/SONARJAVA-5682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5682 Replace use of deprecated Charsets.UTF_8 constant

---

its/plugin/tests/src/test/java/com/sonar/it/java/suite/MultiModuleTelemetryTest.java
java-frontend/src/main/java/org/sonar/java/telemetry/DefaultTelemetry.java
java-frontend/src/main/java/org/sonar/java/telemetry/NoOpTelemetry.java
java-frontend/src/main/java/org/sonar/java/telemetry/Telemetry.java
java-frontend/src/main/java/org/sonar/java/telemetry/TelemetryKey.java
java-frontend/src/test/java/org/sonar/java/telemetry/DefaultTelemetryTest.java
sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java
sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java

[SONARJAVA-5693](https://sonarsource.atlassian.net/browse/SONARJAVA-5693)
[SONARJAVA-5693]: https://sonarsource.atlassian.net/browse/SONARJAVA-5693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5693 Report telemetry indicating autoscan

---

java-checks-test-sources/default/src/main/java/checks/CatchUsesExceptionWithContextCheckLombokSample.java
java-checks/src/main/java/org/sonar/java/checks/CatchUsesExceptionWithContextCheck.java
java-checks/src/test/java/org/sonar/java/checks/CatchUsesExceptionWithContextCheckTest.java

[SONARJAVA-5706](https://sonarsource.atlassian.net/browse/SONARJAVA-5706)
[SONARJAVA-5706]: https://sonarsource.atlassian.net/browse/SONARJAVA-5706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5706 S1166 Fix FP when the Java parser gets connfused due to Lombok

---

sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5841.html
sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5841.json
sonarpedia.json

[SONARJAVA-5716](https://sonarsource.atlassian.net/browse/SONARJAVA-5716)
[SONARJAVA-5716]: https://sonarsource.atlassian.net/browse/SONARJAVA-5716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5716 S5841: Fix typo in AssertJ "doesNotContain"

---

java-frontend/src/main/java/org/sonar/java/model/JType.java
java-frontend/src/main/java/org/sonar/java/model/Symbols.java
java-frontend/src/main/java/org/sonar/plugins/java/api/semantic/Type.java
java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
java-frontend/src/test/java/org/sonar/java/model/SymbolsTest.java

[SONARJAVA-5717](https://sonarsource.atlassian.net/browse/SONARJAVA-5717)
[SONARJAVA-5717]: https://sonarsource.atlassian.net/browse/SONARJAVA-5717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5717 Fix fullyQualifiedName() on intersection types

---

its/autoscan/src/test/resources/autoscan/diffs/diff_S6437.json
java-checks-aws/src/main/resources/org/sonar/java/checks/security/S6437-methods.json
java-checks-aws/src/test/java/org/sonar/java/checks/security/HardCodedCredentialsShouldNotBeUsedCheckTest.java
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/aws/src/main/java/checks/security/HardCodedCredentialsShouldNotBeUsedCheckSample.java

[SONARJAVA-5723](https://sonarsource.atlassian.net/browse/SONARJAVA-5723)
[SONARJAVA-5723]: https://sonarsource.atlassian.net/browse/SONARJAVA-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5723 S6437 Support jsonwebtoken hmacShaKeyFor method

---

check-list/pom.xml
docs/java-custom-rules-example/pom.xml
docs/pom.xml
external-reports/pom.xml
its/autoscan/pom.xml
its/plugin/plugins/java-extension-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
java-checks-aws/pom.xml
java-checks-common/pom.xml
java-checks-test-sources/aws/pom.xml
java-checks-test-sources/default/pom.xml
java-checks-test-sources/java-17/pom.xml
java-checks-test-sources/pom.xml
java-checks-test-sources/spring-3.2/pom.xml
java-checks-test-sources/test-classpath-reader/pom.xml
java-checks-testkit/pom.xml
java-checks/pom.xml
java-frontend/pom.xml
java-jsp/pom.xml
java-surefire/pom.xml
java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
java-symbolic-execution/java-symbolic-execution-plugin/pom.xml
java-symbolic-execution/pom.xml
pom.xml
sonar-java-plugin/pom.xml

[SONARJAVA-5732](https://sonarsource.atlassian.net/browse/SONARJAVA-5732)
[SONARJAVA-5732]: https://sonarsource.atlassian.net/browse/SONARJAVA-5732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5732 Upgrade commons-lang3 to 3.18.0

---

its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaClasspathTest.java
java-frontend/src/main/java/org/sonar/java/classpath/JavaSdkUtil.java

[SONARJAVA-5736](https://sonarsource.atlassian.net/browse/SONARJAVA-5736)
[SONARJAVA-5736]: https://sonarsource.atlassian.net/browse/SONARJAVA-5736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5736 Stop using org.apache.commons.lang3.SystemUtils

---

pom.xml

[SONARJAVA-5742](https://sonarsource.atlassian.net/browse/SONARJAVA-5742)
[SONARJAVA-5742]: https://sonarsource.atlassian.net/browse/SONARJAVA-5742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5742 Add some SCA exclusions to match what's excluded for mend

---

its/autoscan/src/test/resources/autoscan/autoscan-diff-by-rules.json
its/autoscan/src/test/resources/autoscan/diffs/diff_S3457.json
java-checks-test-sources/default/src/main/java/checks/PrintfMisuseCheckEnumsSample.java
java-checks/src/main/java/org/sonar/java/checks/PrintfMisuseCheck.java
java-checks/src/test/java/org/sonar/java/checks/PrintfMisuseCheckTest.java

[SONARJAVA-5759](https://sonarsource.atlassian.net/browse/SONARJAVA-5759)
[SONARJAVA-5759]: https://sonarsource.atlassian.net/browse/SONARJAVA-5759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5759 Fix NPE on S3457 on enums declaration type

---

java-checks-test-sources/default/src/main/java/checks/RawExceptionCheckSample.java
java-checks/src/main/java/org/sonar/java/checks/RawExceptionCheck.java

[SONARJAVA-5782](https://sonarsource.atlassian.net/browse/SONARJAVA-5782)
[SONARJAVA-5782]: https://sonarsource.atlassian.net/browse/SONARJAVA-5782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5782 Improve message in S112

---

java-frontend/pom.xml
java-frontend/src/test/java/org/sonar/java/model/ClassesLayoutTest.java

[SONARJAVA-5772](https://sonarsource.atlassian.net/browse/SONARJAVA-5772)
[SONARJAVA-5772]: https://sonarsource.atlassian.net/browse/SONARJAVA-5772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5772 Switch from testing object sizes to counting instance fields
