SonarSource/sonar-java

- java-checks/pom.xml
- java-checks/src/main/java/org/sonar/java/checks/NoTestInTestClassCheck.java
- java-checks/src/test/files/checks/NoTestInTestClassCheck.java
https://jira.sonarsource.com/browse/SONARJAVA-1254
> SONARJAVA-1254 Update rule S2187: NoTestInTestClassCheck should support TestNG Test annotation

- java-checks/src/main/java/org/sonar/java/checks/ClassComplexityCheck.java
- java-checks/src/main/java/org/sonar/java/checks/MethodComplexityCheck.java
- java-squid/src/main/java/org/sonar/java/Measurer.java
- java-squid/src/main/java/org/sonar/java/model/VisitorsBridge.java
- java-squid/src/main/java/org/sonar/plugins/java/api/JavaFileScannerContext.java
From JavaFileScannerContext deprecate:
* int getComplexity(Tree tree)
* int getMethodComplexity(ClassTree enclosingClass, MethodTree methodTree)
* void addNoSonarLines(Set<Integer> lines)
> SONARJAVA-1272 Restore complexity api breaking change and deprecate some methods

- java-squid/src/main/java/org/sonar/java/cfg/CFG.java
- java-squid/src/main/java/org/sonar/java/se/CheckerDispatcher.java
- java-squid/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-squid/src/test/files/se/Reproducer.java
- java-squid/src/test/java/org/sonar/java/cfg/CFGTest.java
Expression statements should clear the stack of program state. This was not done properly in some cases.
This lead to resolution of SONARJAVA-1386 about labeled break and continue.
> SONARJAVA-1387 Fix leaking of stack in program state.

- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1602.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1604.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1609.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1610.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1611.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1612.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1710.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2293.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2718.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2976.html
The property was listed as `java.source.version` only in inline docs. They are actually read by end users. In source files there were only `sonar.java.source`. I've change that to correct this issue.
Here are listings:
```bash
$ grep -r 'java.source.version'
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1602.html:  <em>Note</em> that this rule is automatically disabled when the project's <code>java.source.version</code> is lower than <code>8</code>.
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1604.html:  <em>Note</em> that this rule is automatically disabled when the project's <code>java.source.version</code> is lower than <code>8</code>.
java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1609.html:  <em>Note</em> that this rule is …
```
> Change project property name to be valid sonar.java.source in inline docs

- appveyor.yml
Appveyor almost never restores this cache, for reasons unclear to me, but spends significant amount of time to build it.
> Do not cache local Maven repository in Appveyor

- its/ruling/pom.xml
This `diffutils` dependency doesn't seem to be used to me - but let's leave the ITs verify this!
> IT Ruling: Remove unused dependency on diffutils

- appveyor.yml
Check of default Chocolatey feed fails from time to time. And this check was done for each build, even if Maven was already installed.
Also by removing usage of Chocolatey we receive less files for cache, and can automatically select Apache mirror.
> Do not use Chocolatey in Appveyor

- java-squid/src/main/java/org/sonar/java/cfg/CFG.java
- java-squid/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
By guaranteeing the fact that we will explore first body of a for loop it is very hard
(but not impossible) to have a case where the max execution of loops will lead to false positive.
Those cases seems to be out of real world example.
> SONARJAVA-1485 Preserving ordering in successors fix the issue.

- java-checks/src/main/java/org/sonar/java/checks/AbstractSerializableInnerClassRule.java
- java-checks/src/test/files/checks/InnerClassOfNonSerializableCheck.java
Note that this regression was introduced by 37c91855fcbd03b1ef3fb3540675e1a09fc2502d, which didn't take into account anonymous classes.
> SONARJAVA-1556 Handle NPEs on anonymous classes

- java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
- java-checks/src/test/files/checks/AssertionsInTestsCheckHamcrest.java
Add support for Hamcrest assertion with three arguments for rule "Tests should include assertions - squid:S2699"
> add support for Hamcrest assertion with three arguments (squid:S2699)

- README.md
* Fix the path of expected issues files, it was outdated and misleading. Also added `cp` command for easy copy-paste
* Adjust the markdown format to make it more readable (line breaks between formatting units) in plain text form
* Use indented code blocks instead of GitHub specific <code>```</code> fences: equivalent writing style but not GitHub specific, and more readable
* Use h1 style for title only, use h2 for the rest
* Don't skip heading levels like h3 -> h6, reorganize to always change one step at a time, like h3 -> h4
* Other minor improvements (punctuation, misc)
> Readme fix and markdown readability improvements

- java-frontend/src/test/java/org/sonar/java/MeasurerTest.java
The Windows file.seperator is '\' which causes a mismatch between the project key constructed in the assertions compared to one in DefaultInputFile.
This will allow 'mvn clean install' to cleanly run out of the box on windows.
> Make MeasurerTest compatible with Windows.

- java-checks/src/main/java/org/sonar/java/checks/PrintfCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2275_java.html
- java-checks/src/test/files/checks/PrintfCheck.java
Rule now detect call to "MessageFormat.format()" with:
- too few arguments;
- too many arguments;
- unbalanced quote or curly braces;
- useless calls to "toString()" in arguments.
> SONARJAVA-1783 Add handling of  MessageFormat to rule S2275

- java-checks/pom.xml
- java-checks/src/main/java/org/sonar/java/checks/AssertionsCompletenessCheck.java
- java-checks/src/main/java/org/sonar/java/checks/AssertionsInTestsCheck.java
- java-checks/src/test/files/checks/AssertionsCompletenessCheck.java
- java-checks/src/test/files/checks/AssertionsInTestsCheckTruth.java
- java-checks/src/test/java/org/sonar/java/checks/AssertionsInTestsCheckTest.java
A method invocation on the 'Subject' base-type of the Truth framework will
be considered as an assertion call.
> SONARJAVA-1793: Add support for Truth framework assertions.

- java-checks/src/main/java/org/sonar/java/checks/PrintfCheck.java
- java-checks/src/test/files/checks/PrintfCheck.java
Change to support "%n":
- "checkEmptyParams" is called before "cleanupLineSeparator" to take into account "%n"
Change the way "%%" is handled:
- "getParameters" now ignore "%%", so no need to clean "%%" in "cleanupLineSeparator"
> SONARJAVA-1835 S2275: FP on message format using '%n' but no parameter

- java-checks/src/main/java/org/sonar/java/checks/MagicNumberCheck.java
- java-checks/src/test/java/org/sonar/java/checks/MagicNumberCheckTest.java
Authorized numbers must be trimmered to avoid NumberFormatException if there is any space.
> SONARJAVA-1950 Fix Magic Number Check

- its/ruling/src/test/resources/jboss-ejb3-tutorial/squid-S2168.json
- its/ruling/src/test/resources/jdk6/squid-S2168.json
- java-checks/src/main/java/org/sonar/java/checks/synchronization/DoubleCheckedLockingCheck.java
- java-checks/src/test/files/checks/DoubleCheckedLockingCheck.java
SONARJAVA-1904-2 Rule S2168: Double-checked locking should not be used
- fix FP when both ifs are inside critical section
- fix FP when method itself is synchronized
- report issue on synchronized, ifs are secondary locations
> SONARJAVA-1904-2 Rule S2168: Double-checked locking should not be used

- its/ruling/src/test/resources/jdk6/squid-S128.json
- java-checks/src/main/java/org/sonar/java/checks/SwitchCaseWithoutBreakCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S128_java.html
- java-checks/src/test/files/checks/SwitchCaseWithoutBreakCheck.java
Now handles the cases by analyzing the various paths. 
I played around with secondary issue marking a little but getting it to markdown the most precise location(or locations in case multiple branches fail the constraint) was starting to add more and more code. So I decided that within my solution adding secondary flagging would clutter the code too much.
Feel free to shoot this solution down if I failed to grasp on how to tackle this problem properly.
During development I found that adding an irrelevant block after the switch statement could influence which call were being made to `checkPreStatement` which I couldn't really explain. If you're interested in those see [this …
> SONARJAVA-1336: Improve S128 to handle more situations

- its/ruling/src/test/resources/sonar-server/squid-S3066.json
- java-checks/src/main/java/org/sonar/java/checks/EnumMutableFieldCheck.java
- java-checks/src/test/files/checks/EnumMutableFieldCheck.java
* Now `public` `final `**mutable** fields are raising an issue.
* Mutable fields considered: `java.util.Collections`, `java.util.Date` and arrays.
* Collections extending [com.google.common.collect.ImmutableCollection](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/ImmutableCollection.html) are not considered mutable in the rule.
> SONARJAVA-1604 FN on S3066 - Public final fields should be checked for their mutability

- its/ruling/src/test/resources/jdk6/squid-S2259.json
- its/ruling/src/test/resources/jdk6/squid-S2583.json
- java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-frontend/src/main/java/org/sonar/java/se/ProgramState.java
- java-frontend/src/main/java/org/sonar/java/se/SymbolicValueFactory.java
- java-frontend/src/main/java/org/sonar/java/se/checks/ConditionAlwaysTrueOrFalseCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/CustomUnclosedResourcesCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/DivisionByZeroCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/FlowComputation.java
- java-frontend/src/main/java/org/sonar/java/se/checks/LocksNotUnlockedCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/NullDereferenceCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/OptionalGetBeforeIsPresentCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/SECheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java
- java-frontend/src/main/java/org/sonar/java/se/constraint/ConstraintManager.java
- java-frontend/src/main/java/org/sonar/java/se/constraint/ObjectConstraint.java
- java-frontend/src/test/files/se/FlowComputation.java
- java-frontend/src/test/files/se/LocksNotUnlockedCheck.java
- java-frontend/src/test/files/se/LocksNotUnlockedCheckCache.java
- java-frontend/src/test/files/se/MaxStepsWithIssue.java
- java-frontend/src/test/java/org/sonar/java/se/ConstraintTest.java
- java-frontend/src/test/java/org/sonar/java/se/ExplodedGraphWalkerTest.java
- java-frontend/src/test/java/org/sonar/java/se/MethodYieldTest.java
- java-frontend/src/test/java/org/sonar/java/se/SymbolicValueFactoryTest.java
- java-frontend/src/test/java/org/sonar/java/se/checks/FlowComputationTest.java
- java-frontend/src/test/java/org/sonar/java/se/checks/LocksNotUnlockedCheckTest.java
- java-frontend/src/test/java/org/sonar/java/se/checks/SECheckTest.java
Removes `syntaxNode` from `Constraint`. This changes the identity (`hashcode`) of `Constraint` and thus identity of `Node`. Which has the effect that the cache is used more often because we can internalize more nodes of the EG. 
However this change lead to two issues
1. when reporting the issue, flows need to be computed using all parents of the node. 
2. when calling endOfExecutionPath (EEP) , not all of the parents of the node are calculated
To solve #1 I first moved `SECheck#flow` to separate class and simplified the algorithm to use just recursion instead of mix of custom stack and recursive approaches. After I modified to use all parents to compute flow.
To solve #2 I deffer the call of EEP until the EG is fully explored or exploration is interrupted. This is achieved by maintaining …
> SONARJAVA-1963 remove syntaxNode from Constraint

- java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-frontend/src/test/files/se/PartialMethodYieldMaxStep.java
- java-frontend/src/test/java/org/sonar/java/se/SymbolicExecutionVisitorTest.java
Method behavior of interrupted exploration is never marked as completed, and mehtod behavior which have not been completed are never used. Therefore, no need to compute a yield when the method exploration is interrupted.
> Fix perf: do not compute method yield when method exploration is interrupted

- java-frontend/src/test/java/org/sonar/java/se/ProgramStateDataProvider.java
- java-frontend/src/test/java/org/sonar/java/viewer/EGViewer.java
- java-frontend/src/test/resources/viewer/viewer.js
Update the viewer with respect of recent evolution of the SE engine.
- Everytime a yield is used, the edge is now **purple**, and clickable to display the yield
- Everytime an exception is on the stack for a given node, the edge leading to that node is **red**
- Display in **red** the new nodes from the graph which have no parent, but are not the starting point (currently coming from checks creating exceptional yields)
Two examples:
> Update EGViewer in order to correctly display method yields and exceptional branching

- its/ruling/src/test/resources/jdk6/squid-S2259.json
- its/ruling/src/test/resources/jdk6/squid-S2583.json
- java-frontend/src/main/java/org/sonar/java/model/ExpressionUtils.java
- java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-frontend/src/main/java/org/sonar/java/se/checks/DivisionByZeroCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/NonNullSetToNullCheck.java
- java-frontend/src/test/files/model/ExpressionUtilsTest.java
- java-frontend/src/test/files/se/ConditionAlwaysTrueOrFalseCheck.java
- java-frontend/src/test/files/se/DivisionByZeroCheck.java
- java-frontend/src/test/files/se/NonNullSetToNullCheck.java
- java-frontend/src/test/files/se/NullDereferenceCheck.java
- java-frontend/src/test/java/org/sonar/java/cfg/CFGTest.java
- java-frontend/src/test/java/org/sonar/java/model/ExpressionUtilsTest.java
Note: This PR is not finished yet but as it's quite involved I'd like some early feedback to ensure that I'm staying on track.
- jdk6:java/awt/List.java:582: OK 
- jdk6:java/beans/DefaultPersistenceDelegate.java:220: Used in method with nullcheck (xproc). No clue why this changes now though.
- jdk6:java/security/UnresolvedPermission.java:370: FP. The if-mess on line 341 allows only for non-null values with equal length to pass. I think this should be resolved by backlearning [SONARJAVA-1791](https://jira.sonarsource.com/browse/SONARJAVA-1791).
- Handle Compound assignments: TBD (test/files/se/DivisionByZeroCheck.java:395). This requires more work on having some compound assignments being considered as simple statements …
> SONARJAVA-1776: Store SV of field using this assignments

- java-frontend/src/test/files/.gitattributes
Test in [SonarComponents](https://github.com/SonarSource/sonar-java/blob/6ce6e52a01e3608c9d6058996da438ecef953d64/java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java#L353-L353) requires LF line endings for size of the file to be consistent between platforms.
This PR enforces LF line endings with .gittatrributes file
> Add gitattributes to force eol

- java-frontend/src/main/java/org/sonar/java/xml/maven/PomParser.java
I actually have no idea how to test it except from manual tests. I reproduced the issue with an IBM jdk and sonalint CLI, while trying to analyze any POM file.
> SONARJAVA-2055 Enable locations for XML element in case of IBM JVMs.

- README.md
- java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
- java-checks/src/test/files/filters/LombokFilter.java
This PR fixes an false positive issue raised by analysis if one is using [Lombok Constructor annnotations](https://projectlombok.org/features/Constructor.html). The rule S1258 - `org.sonar.java.checks.AtLeastOneConstructorCheck` was not filtered properly by `org.sonar.java.filters.LombokFilter`.
> Bugfix: Lombok false positive on S1258

- java-checks/src/main/java/org/sonar/java/checks/PrintfFailCheck.java
This list is never read or used for anything, it only has arguments removed from it.
> Remove an unused list.

- its/performancing/src/test/java/JavaPerformanceTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaClasspathTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaComplexityTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/SuppressWarningTest.java
- its/ruling/src/test/java/org/sonar/java/it/JavaRulingTest.java
- java-frontend/src/main/java/org/sonar/java/AbstractJavaClasspath.java
- java-frontend/src/main/java/org/sonar/java/JavaClasspath.java
- java-frontend/src/test/java/org/sonar/java/JavaClasspathTest.java
Note : analysis do not fail if project contains only one source file. For ease of testing and because bytecode is not required in those cases.
> SONARJAVA-2169 fail analysis if sonar.java.binaries is empty

- java-checks/src/test/java/org/sonar/java/checks/CheckListTest.java
This has become irrelevant over the years, we don't need to test all checks for parseable issues as this
problem is handled in VisitorsBridge and covered by other tests (VisitorsBridgeTest notably).
> Remove parsing test in checklist

- its/ruling/src/test/resources/jdk6/squid-S3516.json
- its/ruling/src/test/resources/sonar-server/squid-JsonWriterNotClosed.json
- its/ruling/src/test/resources/sonar-server/squid-S2095.json
- java-frontend/src/main/java/org/sonar/java/bytecode/cfg/BytecodeCFG.java
- java-frontend/src/main/java/org/sonar/java/bytecode/se/BytecodeEGWalker.java
- java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-frontend/src/main/java/org/sonar/java/se/ProgramState.java
- java-frontend/src/main/java/org/sonar/java/se/checks/CustomUnclosedResourcesCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/InvariantReturnCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/LocksNotUnlockedCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/StreamNotConsumedCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java
- java-frontend/src/main/java/org/sonar/java/se/xproc/ExceptionalCheckBasedYield.java
- java-frontend/src/main/java/org/sonar/java/se/xproc/ExceptionalYield.java
- java-frontend/src/test/java/org/sonar/java/bytecode/se/BytecodeEGWalkerExecuteTest.java
- java-frontend/src/test/java/org/sonar/java/bytecode/se/BytecodeEGWalkerTest.java
- java-frontend/src/test/java/org/sonar/java/bytecode/se/testdata/ExceptionEnqueue.java
- java-frontend/src/test/java/org/sonar/java/se/BehaviorCacheTest.java
- java-frontend/src/test/java/org/sonar/java/se/xproc/ExceptionalCheckBasedYieldTest.java
- java-frontend/src/test/java/org/sonar/java/se/xproc/ExceptionalYieldTest.java
- java-frontend/src/test/java/org/sonar/java/se/xproc/MethodBehaviorTest.java
Because exit blocks are now properly enqueued when doing bytecode analysis, many more yields will have known exception types, which required change in checks how exit from the method on exception is handled. Now this decision is delegated to the individual checks.
> SONARJAVA-2594 enqueue exit blocks in bytecode analysis

- java-checks/src/main/java/org/sonar/java/checks/DiamondOperatorCheck.java
- java-checks/src/test/files/checks/DiamondOperatorCheck_java_7.java
- java-checks/src/test/files/checks/DiamondOperatorCheck_java_8.java
- java-checks/src/test/files/checks/DiamondOperatorCheck_no_version.java
Previously diamond operator check was not able to handle `TYPE_CAST` and `PARENTHESIZED_EXPRESSION` when trying to get assigned variable.
That was causing unclear failure (`ClassCastException`) during analysis of code with such patterns.
Code example that was causing failure previously:
```
((List[])data)[2] = new HashMap<String,List<Integer>>();
```
> Allow diamond operator check to handle casts and expressions parenthesis

- java-checks/src/main/java/org/sonar/java/checks/NoTestInTestClassCheck.java
- java-checks/src/test/files/checks/NoTestInTestClassCheck.java
This PR verifies that if there is a `@Nested` class with tests, SonarQube will not trigger a FP `S2187` : `Add some tests to this class.`
Also if there are no tests in the `@Nested` class, `S2187` still will be trigegred.
> Add support for @Nested test classes (JUnit5)

- its/ruling/src/test/resources/sonar-server/squid-S1312.json
- java-checks/src/main/java/org/sonar/java/checks/LoggersDeclarationCheck.java
- java-checks/src/test/files/checks/LoggersDeclarationCheck.java
This is a minor fix for S1312, so it also detects fully qualified logger class names (e.g. org.slf4j.Logger). I haven't run the integration test suite, since this fix is very minor...
> Bugfix for S1312: Find loggers which are fully qualified.

- java-checks/src/main/java/org/sonar/java/checks/DateUtilsTruncateCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2718_java.html
- java-checks/src/test/files/checks/DateUtilsTruncateCheck.java
- java-checks/src/test/files/checks/DateUtilsTruncateCheck_no_version.java
The existing solution of S2718 rule (replace `DateUtils.truncate` method with faster one from java.time) changes the behavior because `DateUtils.truncate` method performs calculation in default time zone but Instant does in UTC. Use `ZonedDateTime.truncateTo` method instead to get the same behavior as commons-lang method. JSR-310 solution remains more than 2 times faster than the alternative one.
> fixed compliant solution for S2718

- README.md
The minimum version of SonarQube Server is `6.7`
> Update README.md : increase SonarQube version

- check-license-compliance.sh
- missing-dep-licenses.properties
- pom.xml
- third-party-licenses.sh
- travis.sh
Upgrading to parent 45 allows to improve the verification of
license compliance of third-party dependencies.
The new script check-license-compliance.sh fails if a dependency
has a license that is not compatible with SonarSource policy.
See https://xtranet.sonarsource.com/display/DEV/Open+Source+Licenses
for more details.
> Check license compliance on Travis

- java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
- java-checks/src/test/files/filters/LombokFilter.java
This fixes false positives of S1118 ("Utility classes should not have public constructors") regarding lombok-generated constructors; see my post at https://groups.google.com/forum/#!topic/sonarqube/hu2sITqPyQs
- **_My local ruling test failed, but had exactly the same results as with `master`._**
- **_There was no reaction to my post, so there is no Jira ticket._**
> FP on S1118 with Lombok constructors

- java-frontend/src/main/java/org/sonar/java/UCFGJavaVisitor.java
- java-frontend/src/test/java/org/sonar/java/UCFGJavaVisitorTest.java
Instead of translating only arrayGet on primitive arrays (and not arraySet), ignore both arrayGet and arraySet.
Keep references to arrays in the uCFG.
> SONARSEC-165 Fix uCFG array access inconsistency with primitives

- java-frontend/pom.xml
- java-frontend/src/main/java/org/sonar/java/UCFGJavaVisitor.java
- java-frontend/src/test/java/org/sonar/java/UCFGJavaVisitorTest.java
c15c37e780ed216286db00ed737b7249741a6004 - SONARSEC-175 UCFGJavaVisitor should handle multi-dim array initialization (#2127)
3eb97bd71fbf3884602588835179b35e7d3ed08b - SONARSEC-165 Fix uCFG array access inconsistency with primitives (#2118)
ec0029838e3d73c00cfde6c5000ea7e113b6fb3d - Use static import in tests
cbefb33e4d919ebdbdf5a6abd793c2a1490f8401 - SONARSEC-154 Fix case of parameter not annotated when annotations are present
6f96f40d180595b0fb4d65daf6bb0b863ae318d5 - SONARSEC-158 Array variable declaration should be translated to uCFG
8da9efe949a1536f6a3c2e0d133eb40def65a30e - SONARSEC-154 Handle method annotations propagated to parameters
2f6042d625107238607b0a832ee6d4126e38e895 - SONARSEC-154 Update handling of annotations to use '__annotate()' …
> Revert all SonarSecurity 7.3 related commits:

- java-checks/src/main/java/org/sonar/java/checks/TooManyParametersCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S107_java.html
- java-checks/src/test/files/checks/TooManyParameters.java
Updated the white list for `@GetMapping` and other shortcut annotations for `@RequestMapping`
> SONARJAVA-2874: Exclude Spring @RequestMapping shortcut annotations from too many parameters check rule

- external-reports/src/test/java/org/sonar/java/externalreport/SpotBugsSensorTest.java
- java-frontend/src/main/java/org/sonar/java/AnalysisWarningsWrapper.java
- java-frontend/src/main/java/org/sonar/java/JavaClasspath.java
- java-frontend/src/main/java/org/sonar/java/JavaTestClasspath.java
- java-frontend/src/test/java/org/sonar/java/AnalysisWarningsWrapperTest.java
- java-frontend/src/test/java/org/sonar/java/JavaClasspathTest.java
- java-frontend/src/test/java/org/sonar/java/JavaIssueTest.java
- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/java/TestUtils.java
- java-frontend/src/test/java/org/sonar/java/TestUtilsTest.java
- pom.xml
- sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaPlugin.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaPluginTest.java
This work depends on new features in the SonarQube API. It can be merged after the API changes are part of a milestone / stable release (ETA Sep 28).
**Update:** the new ETA is Oct 10.
> SONARJAVA-2888 Register warning when missing bytecode detected

- java-surefire/src/main/java/org/sonar/plugins/surefire/data/SurefireStaxHandler.java
- java-surefire/src/test/java/org/sonar/plugins/surefire/data/SurefireStaxHandlerTest.java
- java-surefire/src/test/resources/org/sonar/plugins/surefire/data/SurefireStaxHandlerTest/TEST-#29.xml
This can be produced by buggy junit 5.2 surefire reports
> SONARJAVA-2931 workaround bad classname in surefire reports

- README.md
With the removal of jacoco-previous, I believe this paragraph is not relevant anymore.
> Remove note about jacoco-previous from README.md

- java-checks/src/main/java/org/sonar/java/checks/PackageInfoCheck.java
- java-checks/src/test/java/org/sonar/java/checks/PackageInfoCheckTest.java
- sonar-java-plugin/pom.xml
For some reason, the `relativize` method does not generate same output on windows and linux OS:
Linux: Paths.get("").relativize(Paths.get("path")).toString() -> "path"
Windows: Paths.get("").relativize(Paths.get("path")).toString() -> "..\path"
This causes conflict when creating `TestInputFileBuilder` relying on existing files when the module directory is `new File("")` as it prepends the `..`, and file cannot be found
> Fix build on windows OS due to path resolution and plugin size

- java-jacoco/pom.xml
- java-jacoco/src/main/java/org/sonar/plugins/jacoco/JaCoCoSensor.java
- java-jacoco/src/main/java/org/sonar/plugins/jacoco/UnitTestAnalyzer.java
- java-jacoco/src/test/java/org/sonar/plugins/jacoco/JaCoCoSensorTest.java
Do not squash, contains 2 tickets
SONARJAVA-3065 Deprecate coverage per test
SONARJAVA-3066 Update message for old deprecated JaCoCo properties
>  SONARJAVA-3065 & SONARJAVA-3066 Deprecate coverage per test

- java-checks/src/test/files/checks/AssertionsInTestsCheck/AssertJ.java
- java-frontend/src/main/java/org/sonar/java/resolve/Resolve.java
- java-frontend/src/test/files/sym/references/MostSpecificGenericMethodCall.java
- java-frontend/src/test/java/org/sonar/java/resolve/SymbolTableTest.java
We are resolving the wrong one in such cases:
```java 
<T> List<T> foo(List<? extends T> t);
<T> T foo(T t);
...
void test(List<String> list) {
foo(list); // wrongly resolved to the 2nd method instead of the first one 
}
```
https://docs.oracle.com/javase/specs/jls/se8/html/jls-18.html#jls-18.5.4
> SONARJAVA-3079 Fix method resolution

- java-checks/src/main/java/org/sonar/java/checks/MutableMembersUsageCheck.java
- java-checks/src/main/java/org/sonar/java/checks/PublicStaticMutableMembersCheck.java
- java-checks/src/test/files/checks/MutableMembersUsageCheck.java
- java-checks/src/test/files/checks/PublicStaticMutableMembersCheck.java
Note that in S2384 I am deliberately not adding `java.util.Map` because it creates lot of new issues unrelated to this ticket. We might create a new ticket to have the support of `java.util.Map` in this rule.
> SONARJAVA-3086 Support Java 9 immutable collections in S2384 and S2386

- java-checks/src/test/files/checks/CloneMethodCallsSuperCloneCheck.java
- java-checks/src/test/files/checks/ToStringUsingBoxingCheck.java
According to Java Language Specification
".super" and ".this" can be preceded only by type name.
> Fix syntax errors in test files

- java-checks/src/main/java/org/sonar/java/checks/SillyStringOperationsCheck.java
- java-checks/src/test/files/checks/SillyStringOperationsCheck.java
* Avoid considering String#replaceAll:
- Unwanted issues may be raised because of regular expressions.
* Fix resolution of String constant:
- Use `ConstantUtils.resolveAsStringConstant` instead of `ExpressionsHelper.getConstantValueAsString`.
> SONARJAVA-3134 Fix detection of silly String operations

- Jenkinsfile
This test executes (almost) all the rules against all the test
files writen to test each rule individually.
It makes little sense to execute this test during ruling. Wile
related to rules, it tests rule's ability to cover complex
constructs tested by other rules, rather than non-regression.
> Execute 'Sanity' test independantly rather than during ruling

- Jenkinsfile
Removing conditions on ruling and build with specific OS
during QA. This will enforce that the artifacts to be
used as dogfood went through full QA.
> Drop conditional execution of QA jobs

- java-checks/src/test/java/org/sonar/java/checks/DisallowedClassCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/ConstantUtilsTest.java
- java-frontend/src/test/java/org/sonar/java/bytecode/se/BytecodeEGWalkerTest.java
- java-frontend/src/test/java/org/sonar/java/bytecode/se/BytecodeSECheckTest.java
- java-frontend/src/test/java/org/sonar/java/resolve/ConstantTest.java
- java-frontend/src/test/java/org/sonar/java/se/ExpectationsParserTest.java
- pom.xml
It was not supposed to be used after replacement on assertj
by commit 2e74eccc1be636c43092d96adb5b4825ac5812a2 (SONARJAVA-1970),
but again sneaked in, because was not excluded from dependencies.
> Do not use fest-assert

- java-checks/src/test/files/checks/naming/KeywordAsIdentifierCheck.java
- java-checks/src/test/java/org/sonar/java/checks/naming/KeywordAsIdentifierCheckTest.java
* 'enum' used as identifier was only possible till java 1.4
* '_' used as identifier was only possible till java 1.8,
and has never been possible with lambdas
> Fix test file

- java-jacoco/src/main/java/org/sonar/plugins/jacoco/UnitTestAnalyzer.java
past tense of "forget" is "forgot"
> Fix grammar in log output

- java-checks/src/main/java/org/sonar/java/checks/ArrayForVarArgCheck.java
- java-checks/src/main/java/org/sonar/java/checks/IteratorNextExceptionCheck.java
For `ArrayForVarArgCheck` I duplicated the logic which was using the `MethodJavaType`. When dropping old semantic, we will be able to drop all this code and therefore get rid of the duplication.
> Fix ClassCastException which could occur with new semantic

- java-checks/src/test/files/checks/SimpleClassNameCheck.java
- java-frontend/src/main/java/org/sonar/java/model/JParser.java
- java-frontend/src/main/java/org/sonar/java/model/expression/VarTypeTreeImpl.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
- java-frontend/src/test/java/org/sonar/java/model/JSymbolTest.java
A temporary `IdentifierTreeImpl` was created before being converted into `VarTypeTreeImpl`.
But the `IdentifierTreeImpl`, which is not in the AST (null parent), was wrongly added to the binding usage (in `JParser#createExpression(Expression node)`) and could be retrieved by rules like in ` SimpleClassNameCheck`.
> SONARJAVA-3229 NPE SimpleClassNameCheck(S1942) when IdentifierTree of "var" type has a null parent

- java-checks/src/main/java/org/sonar/java/checks/TryWithResourcesCheck.java
- java-checks/src/test/files/checks/TryWithResourcesCheck.java
The rule uses the internal API "CFG.buildCFG" to create the cfg of none method tree that contains 'break' or 'continue' without the loop context.
> SONARJAVA-2939 S2093 throws IllegalStateException: 'continue' statement not in loop or switch statement

- java-checks/pom.xml
Declaration of dependency on `sonar-analyzer-test-commons` in `java-checks` with a default scope `compile` seems useless, and leads to following warning during build
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.sonarsource.java:java-checks:jar:6.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.sonarsource.analyzer-commons:sonar-analyzer-test-commons:jar -> duplicate declaration of version (?) @ line 94, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
> Remove useless declaration of dependency

- sonar-java-plugin/src/main/resources/static/documentation.md
Currently, double warning icons show up in the public documentation. The `[[warning]]` block will automatically add these icons, they don't have to be added manually.
See [SONAR-12374](https://jira.sonarsource.com/browse/SONAR-12374)
> Prevent double warning icons

- sonar-java-plugin/src/main/resources/static/documentation.md
The [SonarCloud documentation](https://sonarcloud.io/documentation) is currently broken because of the Java plugin doc page.
Here is a fix for it.
Is it possible to get a build with this fix so that we can re-deploy it asap ?
PS: I didn't put any ticket number in the commit message because I'm not sure how you want to handle this ? Create a ticket on your side ? Or reference the incident ?
> INCID-43 Fix broken documentation

- java-checks/src/test/java/org/sonar/java/checks/helpers/JParserTestUtils.java
- java-checks/src/test/java/org/sonar/java/checks/security/TriggeringSecuringHelperTest.java
- java-checks/src/test/resources/checks/security/TriggeringSecuringHelperTest.java
TriggeringSecuringHelper is currently partially used, but we expect it to be useful when we will tackle SONARJAVA-3296.
> Improve coverage for TriggeringSecuringHelper

- java-frontend/src/main/java/org/sonar/java/se/checks/XxeProcessingCheck.java
- java-frontend/src/main/java/org/sonar/java/se/checks/XxeProperty.java
- java-frontend/src/test/files/se/XxeProcessingCheck_SchemaFactory_Validator.java
- java-frontend/src/test/files/se/XxeProcessingCheck_XmlInputFactory.java
S2755 implementation failed to detect two cases:
- When "transferring" method call are used with any number of argument.
- When the property is set from a variable.
> SONARJAVA-3312 FN for S2755: improve detection of XXE attacks

- java-checks-test-sources/src/main/java/checks/DiamondOperatorCheck_java_7.java
- java-checks-test-sources/src/main/java/checks/DiamondOperatorCheck_java_8.java
- java-checks-test-sources/src/main/java/checks/DiamondOperatorCheck_no_version.java
- java-checks/src/main/java/org/sonar/java/checks/DiamondOperatorCheck.java
- java-checks/src/test/java/org/sonar/java/checks/DiamondOperatorCheckTest.java
It does not handle all the cases, as it's not triggered when the diamond could be removed thanks to type inferences on provided parameters, but to me it's not really the same ticket. I anyway added a case, flagged as FN.
Please **do not** squash the commits
> SONARJAVA-2549 Improve S2293 to handle cases where constructor is used in argument

- java-checks-test-sources/src/main/java/checks/UnreachableCatchCheck.java
- java-checks/src/main/java/org/sonar/java/checks/UnreachableCatchCheck.java
Exception can also be a runtime exception, we should not report an issue for them.
> SONARJAVA-2944 S4970: don't report issue for Exception

- java-checks/src/main/java/org/sonar/java/checks/regex/AbstractRegexCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/AnchorPrecedenceCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/DuplicatesInCharacterClassCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/InvalidRegexCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/RedosCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/UnicodeCaseCheck.java
- java-frontend/src/main/java/org/sonar/java/model/DefaultJavaFileScannerContext.java
- java-frontend/src/main/java/org/sonar/java/regex/RegexCache.java
- java-frontend/src/main/java/org/sonar/java/regex/RegexParseResult.java
- java-frontend/src/main/java/org/sonar/java/regex/RegexParser.java
- java-frontend/src/main/java/org/sonar/java/regex/RegexScannerContext.java
- java-frontend/src/main/java/org/sonar/java/regex/ast/FlagSet.java
- java-frontend/src/main/java/org/sonar/java/regex/ast/RegexBaseVisitor.java
- java-frontend/src/main/java/org/sonar/java/regex/ast/RegexVisitor.java
- java-frontend/src/test/java/org/sonar/java/regex/RegexCacheTest.java
- java-frontend/src/test/java/org/sonar/java/regex/RegexParserTestUtils.java
- java-frontend/src/test/java/org/sonar/java/regex/ast/CurlyBraceQuantifierTest.java
- java-frontend/src/test/java/org/sonar/java/regex/ast/GroupTreesTest.java
- java-frontend/src/test/java/org/sonar/java/regex/ast/QuantifierTest.java
- java-frontend/src/test/java/org/sonar/java/regex/ast/RegexBaseVisitorTest.java
Make the result of parsing a regex contain information about which
flags the regex was created with.
Use this information in the RegexBaseVisitor to set the initial
flags, removing any need to call setFlags, which is now removed.
Also move the logic of checking whether the regex contains syntax
errors before visiting anything into the RegexBaseVisitor and the
methods before and after to it, so now rules should all be
implementable with only a suitable definition of a visitor class
and then `new MyVisitor(possibleArguments).visit(regexForLiterals);`.
> Refactoring to avoid duplicated code for flags and error handling

- java-checks-test-sources/src/main/java/checks/regex/DuplicatesInCharacterClassCheck.java
- java-frontend/src/main/java/org/sonar/java/regex/JavaCharacterParser.java
- java-frontend/src/main/java/org/sonar/java/regex/JavaUnicodeEscapeParser.java
- java-frontend/src/main/java/org/sonar/java/regex/RegexParser.java
Some escape sequences had locations which included one character too
many and/or did not include the leading backslash.
> Fix the locations of escape sequences

- java-frontend/src/main/java/org/sonar/java/regex/ast/RegexBaseVisitor.java
- java-frontend/src/main/java/org/sonar/java/regex/ast/RegexTree.java
Also change some misleading wording in the documentation of
RegexBaseVisitor.before.
> Document the correct usage of Visitor.visit vs. RegexTree.accept

- java-checks/src/main/java/org/sonar/java/checks/UseSwitchExpressionCheck.java
- java-checks/src/test/java/org/sonar/java/checks/UseSwitchExpressionCheckTest.java
- java-frontend/src/main/java/org/sonar/java/model/JParser.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
- jdt/pom.xml
* Brings support for Java 14, excluding Preview Features.
* Removes support for Java 13 Preview Features.
> SONARJAVA-3332 Upgrade org.eclipse.jdt.core to 3.22.0

- java-checks/src/main/java/org/sonar/java/checks/regex/RegexComplexityCheck.java
The message should only contain "incl N for nesting" if N > 0.
> SONARJAVA-3415 Fix the secondary message

- java-frontend/src/main/java/org/sonar/java/model/JParser.java
- java-frontend/src/main/java/org/sonar/java/model/expression/InstanceOfTreeImpl.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/tree/InstanceOfTree.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
Added element is marked as deprecated because
it is preview feature and might change.
> SONARJAVA-3286 Update AST for Java 14 Preview Feature: Pattern Matching for instanceof

- java-checks-test-sources/src/main/files/non-compiling/checks/UnreachableCatchCheck.java
- java-checks-test-sources/src/main/java/checks/UnreachableCatchCheck.java
- java-checks/src/main/java/org/sonar/java/checks/UnreachableCatchCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4970_java.html
Also fix a bug where try-statements weren't properly skipped when
throwing unknown exceptions. The bug previously didn't have an effect
because unknown exceptions are also unrelated exceptions thus causing
a FN anyway.
> SONARJAVA-3403 FN in S4970: support unrelated Exception

- java-checks/src/test/files/checks/IgnoredReturnValueCheckJava14.java
- java-checks/src/test/java/org/sonar/java/checks/IgnoredReturnValueCheckTest.java
False-positive is gone thanks to the addition of AST node for
implicit yield-statement.
> SONARJAVA-3304 Add test demonstrating fix of false-positive in S2201

- java-frontend/src/main/java/org/sonar/java/cfg/CFG.java
- java-frontend/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-frontend/src/main/java/org/sonar/java/se/checks/NullDereferenceCheck.java
- java-frontend/src/main/java/org/sonar/java/se/constraint/ConstraintManager.java
- java-frontend/src/test/files/se/DivisionByZeroCheck.java
- java-frontend/src/test/files/se/UnclosedResourcesCheck.java
- java-frontend/src/test/java/org/sonar/java/cfg/CFGTest.java
Fix CFG generation for switch expressions.
The generated CFG for switch expressions previously included the
switch expression twice, once as a terminator (as it should be) and
once as an expression in the block that used the result of the switch
expression. This would make the switch expression the top of the stack
instead of the result and once the user popped the switch expression,
the result of the switch expression would be left on the stack when
the stack should either be empty or contain the results of other
subexpressions.
With the CFG fixed, switch expressions should now be handled properly
with no need to change the symbolic execution engine itself.
> SONARJAVA-3069 Adapt SE engine to Switch Expressions

- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2039_java.json
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S2386_java.json
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4784_java.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4784_java.json
Please rebase the two commits.
> Deprecate S4784 and change type of S2039 and S2386 to Code Smell

- java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
- java-checks/src/test/files/filters/LombokFilter.java
- java-checks/src/test/java/org/sonar/java/filters/FilterVerifier.java
> SONARJAVA-3501 only ignore usued imports on lombok.val and lombok.var

- java-checks-test-sources/pom.xml
- java-checks-test-sources/src/main/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
- java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
Apache Wicket will inject a serializable Proxy in @SpringBean annotated fields, which delegates to the corresponding Spring Bean. 
This change will eliminate a false-positive on `S1948` when using Apache Wicket with @SpringBean.
- some ITs (Plugin Test) are failing, but I get the same errors/failures on master. Maybe this is a ENV issue on my machine, but my changes should not influnece the Plugin Test at all. So lets see what the CI/CD results say :zany_face: 
- all other ITs are running fine :smiley: 
- no Jira issue available
> S1948: handle a org.apache.wicket.spring.injection.annot.SpringBean annotated field as transient or serializable

- java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/JavaCheckVerifierTest.java
- java-frontend/src/main/java/org/sonar/java/testing/Expectations.java
- java-frontend/src/main/java/org/sonar/java/testing/InternalCheckVerifier.java
- java-frontend/src/test/files/testing/MultipleIssuesSameLine.java
- java-frontend/src/test/java/org/sonar/java/testing/CheckVerifierTest.java
- java-frontend/src/test/java/org/sonar/java/testing/ExpectationsTest.java
- java-frontend/src/test/java/org/sonar/java/testing/InternalCheckVerifierTest.java
The actual fix has been done by @sebastian-hungerecker-sonarsource and @alban-auzeill while working on another ticket, and it is already part of Master: https://github.com/SonarSource/sonar-java/commit/2b50830337bf844e443898834ecce4b92084e3b6
This PR only add more tests for consistency and remove the need of Guava in the verifier module
> SONARJAVA-3602 Add test at verifier level

- java-checks-test-sources/src/main/java/checks/tests/MockitoEqSimplificationCheck.java
- java-checks/src/main/java/org/sonar/java/checks/tests/MockitoEqSimplificationCheck.java
Mockito's Matchers.eq() method is a static method, so there is no risk of
highlighting too much when raising on the 'methodSelect()' part of the
method invocations. Such calls can not be chained.
> SONARJAVA-3608 Report on the methodSelect instead of only name

- its/plugin/plugins/java-extension-plugin/pom.xml
- its/plugin/plugins/java-extension-plugin/src/main/java/org/sonar/samples/java/JavaExtensionPlugin.java
- java-checks-testkit/pom.xml
- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/JavaCheckVerifier.java
- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/MultipleFilesJavaCheckVerifier.java
- java-checks/pom.xml
- java-frontend/pom.xml
- java-surefire/src/main/java/org/sonar/plugins/surefire/SurefireExtensions.java
- java-surefire/src/main/java/org/sonar/plugins/surefire/data/UnitTestIndex.java
- sonar-java-plugin/pom.xml
Depends on this [pr](https://github.com/SonarSource/sonar-java/pull/3343) Only the last commit is relevant
> SONARJAVA-2154 Remove remaining usages of guava from sonar-java main sources

- java-checks-test-sources/src/main/java/checks/UselessPackageInfoCheck/package-info.java
- java-checks-test-sources/src/main/java/checks/UselessPackageInfoCheck/packageWithNoOtherFiles/package-info.java
- java-checks-test-sources/src/main/java/checks/UselessPackageInfoCheck/packageWithNoOtherFilesButNotPackageInfo/HelloWorld.java
- java-checks-test-sources/src/main/java/checks/UselessPackageInfoCheck/packageWithNoOtherFilesButNotPackageInfo/package-info.java
- java-checks/src/test/files/checks/UselessPackageInfoCheck/package-info.java
- java-checks/src/test/files/checks/UselessPackageInfoCheck/packageWithNoOtherFiles/package-info.java
- java-checks/src/test/files/checks/UselessPackageInfoCheck/packageWithNoOtherFilesButNotPackageInfo/HelloWorld.java
- java-checks/src/test/files/checks/UselessPackageInfoCheck/packageWithNoOtherFilesButNotPackageInfo/package-info.java
- java-checks/src/test/java/org/sonar/java/checks/UselessPackageInfoCheckTest.java
Due to a bug in the JavaCheckVerifier (see [SONARJAVA-3643](https://jira.sonarsource.com/browse/SONARJAVA-3643)), I have to postpone the implementation of the fix of SONARJAVA-3633.
Since I already made the effort to move the test files to the compiled module, it makes sense to still merge this code.
> SONARJAVA-3633 Move test files to compiled module for S4032

- its/plugin/projects/java-version-aware-visitor/pom.xml
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTest.java
Starting from [this commit](https://github.com/SonarSource/sonar-scanner-maven/commit/0d618b5b8a622aa8c97232bb5acb3fb488387e8a) release version configured in pom.xml will be considered as `sonar.java.source` version.
Our plugin test projects are all configured to run on java 11 using this property in parent's pom.xml. 
To keep testing older versions of java in this test I removed parent section only from this project. So now `sonar.java.source` version won't be overridden and we'll get the right fallback from maven, which is Java 5
> Fix its expecting default Java version in maven

- java-checks-test-sources/src/main/files/non-compiling/checks/StaticMemberAccess.java
- java-checks-test-sources/src/main/java/checks/SimpleClassNameCheck.java
- java-checks-test-sources/src/main/java/checks/StaticMemberAccess.java
- java-checks/src/test/java/org/sonar/java/checks/SimpleClassNameCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/StaticMemberAccessCheckTest.java
During the Guava removal, 2 tests ended up not testing anything, since they `verifyNoIssues` despite the fact that the rule should still raise issues.
Only the tests are affected, the behavior of the rules are correct and unchanged.
> Update tests for S3252 and S1942

- java-checks/src/main/java/org/sonar/java/checks/security/ExcessiveContentRequestCheck.java
- java-frontend/src/main/java/org/sonar/java/model/DefaultJavaFileScannerContext.java
- java-frontend/src/main/java/org/sonar/java/model/VisitorsBridgeForTests.java
See [DefaultJavaFileScannerContext.java#L263](https://github.com/SonarSource/sonar-java/blob/master/java-frontend/src/main/java/org/sonar/java/model/DefaultJavaFileScannerContext.java#L263).
I believe this is a protection, to not store references to trees across different files analysis.
In this case, I don't think it was relevant: the issue was directly reported during the analysis of the file (and not at the end of the analysis), but we can report with AnalyzerMessage anyway since it does not change anything at the end.
> SONARJAVA-3679 Report issue with AnalyzerMessage

- java-frontend/src/main/java/org/sonar/java/regex/RegexCheck.java
- java-frontend/src/test/java/org/sonar/java/regex/RegexCheckTest.java
> SONARJAVA-3636 Improve secondary message for regex rules when issues are reported across different string literals

- java-checks-test-sources/src/main/files/non-compiling/checks/StrongCipherAlgorithmCheck.java
- java-checks/src/test/java/org/sonar/java/checks/StrongCipherAlgorithmCheckTest.java
In fact, the important change ([supporting text block in `asConstant`](https://github.com/SonarSource/sonar-java/pull/3504/files#diff-e09d8d74fec9f3de313b998a998a1118aa3b9f58eabc6d5fb76f525aa402b337R214)) was already done in #3504, so this PR contains only one test to make sure this feature is supported in the different rules.
> SONARJAVA-3736 Test support of Text Block in rules relying on String literals from expressions

- java-checks-test-sources/src/main/files/non-compiling/checks/tests/MockitoArgumentMatchersUsedOnAllParameters.java
- java-checks-test-sources/src/main/java/checks/tests/MockitoArgumentMatchersUsedOnAllParameters.java
- java-checks/src/main/java/org/sonar/java/checks/tests/MockitoArgumentMatchersUsedOnAllParametersCheck.java
- java-checks/src/test/java/org/sonar/java/checks/tests/MockitoArgumentMatchersUsedOnAllParametersCheckTest.java
This pull request adds the capability to the check to look into methods that might return an argument matcher.
If the method cannot be resolved or its code explored, then it is assumed that the method might return an argument matcher and thus no issue is reported.
> SONARJAVA-3822: S6073 should not report on method invocation arguments that actually return an argument matcher

- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4604_java.html
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S4604_java.json
Following the [deprecation of S4604](https://github.com/SonarSource/rspec/pull/131), this change updates the documentation of rule S4604 in the java analyzer.
> SONARJAVA-3865: Deprecate S4604

- java-checks-test-sources/src/main/java/checks/CollectorsToList.java
- java-checks/src/main/java/org/sonar/java/checks/CollectorsToListCheck.java
Use semantics to find the usages of a variable to simplify the
implementation and fix FPs where lists were assigned to fields or
array slots.
> SONARJAVA-3745 Simplify implementation and fix FPs

- java-checks-test-sources/src/main/files/non-compiling/symbolicexecution/checks/ConditionAlwaysTrueOrFalseCheck.java
- java-frontend/src/main/java/org/sonar/java/cfg/CFG.java
- java-frontend/src/test/java/org/sonar/java/cfg/CFGTest.java
- java-symbolic-execution/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-symbolic-execution/src/main/java/org/sonar/java/se/constraint/ConstraintManager.java
For:
```
if (x instanceof String) {}
```
The basic block of the CFG looks like this:
- IDENTIFIER (x)
- INSTANCE_OF
- IF_STATEMENT
When the ExplodedGraphWalker reaches "INSTANCE_OF", the symbolic value of "x" will be on top of the stack. We will wrap it into a "InstanceOfSymbolicValue". (This new symbolic value is not doing much, as we currently do not track the types constraints.) This new symbolic value will replace the top of the stack. "IF_STATEMENT" will then consume this symbolic value.
For:
```
if (x instanceof String str) {} else if (x instanceof Integer i) {}
```
the corresponding cfg is:
- IDENTIFIER (x)
- PATTERN_INSTANCE_OF
- IF_STATEMENT
- IDENTIFIER (x)
- PATTERN_INSTANCE_OF
- IF_STATEMENT
The problem is that we are doing nothing when PATTERN_INSTANCE_OF is reached. It means …
> SONARJAVA-3986 FP in S2583 with Java 16 pattern matching

- java-checks-test-sources/pom.xml
- java-checks-test-sources/src/main/java/checks/AssertionTypesCheck_AssertJ.java
All the changes only impact the `java-checks-test-sources` module, which only contains test code, nothing being shipped with the analyzer.
* Updated dependencies to match versions used by sonar-java parent pom.
* Updated logback version to not use one being vulnerable and get rid of the warning (even if we do strictly nothing with this library)
> Update dependencies of sonar-checks-test-sources

- java-checks-test-sources/src/main/java/checks/JunitNestedAnnotationCheck.java
- java-checks/src/main/java/org/sonar/java/checks/tests/JunitNestedAnnotationCheck.java
Inner classes that are abstract but contain test code should not be
reported by S5790.
> SONARJAVA-4100 Abstract classes should be excluded from S5790

- java-frontend/src/main/java/org/sonar/java/model/JSymbol.java
- java-frontend/src/test/java/org/sonar/java/model/JSymbolTest.java
Relates to #3884.
I decided to get rid of the `null` approach in order to avoid any future NPE, and assigned ownership of primitive type symbols to the root package.
> SONARJAVA-4010 Make sure primitive type symbols have an owner

- java-checks-test-sources/src/main/files/non-compiling/symbolicexecution/checks/S2755_XxeProcessingCheck_DocumentBuilderFactory.java
- java-checks-test-sources/src/main/java/symbolicexecution/checks/S2755_XxeProcessingCheck_DocumentBuilderFactory.java
- java-symbolic-execution/src/test/java/org/sonar/java/se/checks/XxeProcessingCheckTest.java
The problems of both SONARJAVA-3899 and SONARJAVA-3842 were solved in https://github.com/SonarSource/sonar-java/pull/3926, more specifically in https://github.com/SonarSource/sonar-java/pull/3926/commits/496c487c251791a3935595c500f6c2ceb6429b7f.
This PR aims to test the correct behavior of this change with regard to the two tickets.
> SONARJAVA-3899 SONARJAVA-3842 Test correct behavior of "newDocumentBuilder" usage

- its/plugin/projects/spotbugs-external-report/pom.xml
- its/plugin/tests/pom.xml
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/ExternalReportTest.java
- Fix NoClassDefFoundError related to org.codehaus.groovy.vmplugin.v7.Java7 using java 17 like described by https://github.com/aws/aws-sdk-java-v2/issues/2165
- Fix jdk8 for linux downloaded on a mac
> Fix its plugin failure on mac

- java-checks/src/main/java/org/sonar/java/checks/regex/AnchorPrecedenceCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/EmptyStringRepetitionCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/ImpossibleBackReferenceCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/PossessiveQuantifierContinuationCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/SingleCharacterAlternationCheck.java
- java-checks/src/test/java/org/sonar/java/checks/regex/AnchorPrecedenceCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/regex/EmptyStringRepetitionCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/regex/ImpossibleBackReferenceCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/regex/PossessiveQuantifierContinuationCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/regex/SingleCharacterAlternationCheckTest.java
This first PR migrates all the rules that are strictly equivalent (almost token by token) in Analyzer Commons.
> SONARJAVA-4156 Refactor regex rules using sonar-analyzer-commons

- its/ruling/src/test/resources/autoscan/autoscan-diff-by-rules.json
- java-checks-test-sources/src/main/java/checks/ArrayCopyLoopCheck.java
I have added a comment and a test to S3012.
The comment is because it took me a while to understand why the test case was a FP.
The test is to make sure that the rule does not get triggered when 'copying' arrays to non collections.
> S3012 add test and comment

- java-frontend/src/main/java/org/sonar/java/DefaultJavaResourceLocator.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/JavaResourceLocator.java
- java-frontend/src/test/java/org/sonar/java/DefaultJavaResourceLocatorTest.java
Follow-up to the discussion: https://community.sonarsource.com/t/locating-compiled-class-files/69145
This illustrates how the plugin API could expose the contents of `sonar.java.binaries`
> expose ClasspathForMain.getBinaryDirs() via JavaResourceLocator API

- java-checks-test-sources/pom.xml
- pom.xml
- Move woodstox-core to java-checks-test-sources
- Document staxmate as java-surefire dependency
> Cleanup top-level dependencies

- its/ruling/src/test/java/org/sonar/java/it/AutoScanTest.java
- its/ruling/src/test/resources/autoscan/autoscan-diff-by-rules.json
- its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S1612.json
- its/ruling/src/test/resources/eclipse-jetty/java-S1612.json
- java-checks-test-sources/src/main/files/non-compiling/checks/ReplaceLambdaByMethodRefCheck.java
- java-checks-test-sources/src/main/java/checks/ReplaceLambdaByMethodRefCheck.java
- java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
- java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S1612.html
After this change, no issue will be raised when a lambda is shorter than its equivalent method reference.
To determine whether a lambda is shorter than its replacement, we make an approximation and only measure the size of single-line lambdas. The reason is that accurately getting the original code's length is hard when it spans multiple line. This means we will report multi-line lambdas that have an equivalent method reference and are shorter than it, but this is very rare in practice and is the status quo.
See the [corresponding PR for the RSPEC update](https://github.com/SonarSource/rspec/pull/1471).
> SONARJAVA-4098 Update S1612: Short lambdas are considered compliant

- java-checks-test-sources/src/main/java/checks/ReplaceLambdaByMethodRefCheck.java
- java-checks/src/main/java/org/sonar/java/checks/ReplaceLambdaByMethodRefCheck.java
- java-frontend/src/main/java/org/sonar/java/model/JUtils.java
- java-frontend/src/test/java/org/sonar/java/model/JUtilsTest.java
This PR changes the following:
- Ambiguous method references, like `Integer::toString` for lambda `x -> x.toString()` and `x -> Integer.toString(x)`, are not suggested anymore. This also works for lambdas with multiple arguments
- If there exist an unambiguous reference in a supertype, this will be suggested instead. For example `x -> x.toString()` where `x` is an `Integer` can be unambiguously referred by `Object::toString`. The replacement only happens if thrown exceptions are the same in the supertype method. Annotations are not checked.
> SONARJAVA-4329 Fix FNs in S1612 when replacement reference is ambiguous

- its/ruling/src/test/resources/guava/java-S2272.json
- java-checks-test-sources/src/main/files/non-compiling/checks/IteratorNextExceptionCheck.java
- java-checks-test-sources/src/main/java/checks/IteratorNextExceptionCheck.java
- java-checks/src/main/java/org/sonar/java/checks/IteratorNextExceptionCheck.java
Method calls are visited recursively to check if they might throw NoSuchElementException.
Methods outside the current file and try-catch statement are not handled.
> SONARJAVA-4363 Fix FNs on S2272 when NoSuchElementException is thrown indirectly

- .mailmap
Set up a `.mailmap` document to clean up the contributor list using various emails when committing (including internal developers from Sonar).
You can compare the differences in results when executing the following command line, before and after the commit.
```
git shortlog -sne
```
> Add .mailmap file to sort out contributors with multiple emails

- .cirrus.yml
Since the artifacts produced on this branch are only meant to run on SQ 9.9, we can limit cycle waste by avoiding to test against unrelated versions.
> Restrict ITs to run on 9.9 LTS

- pom.xml
* Update parent version to `67.0.0.241` in pom.xml
That way the code uses the last published parent-oss version
The project `parent-oss` now follows the standardized pattern used across the SonarSource organization for versioning: `x.x.x.buildnumber`.
> [BUILD-2836] Update parent version to 67.0.0.241 in pom.xml

- java-checks-test-sources/src/main/java/symbolicexecution/checks/ConditionAlwaysTrueOrFalseNoExceptionOnBranchingStatementsLogicalAndOrTestCase.java
- java-symbolic-execution/src/main/java/org/sonar/java/se/ExplodedGraphWalker.java
- java-symbolic-execution/src/test/java/org/sonar/java/se/checks/ConditionAlwaysTrueOrFalseCheckTest.java
Previously, we regularly nuked the stack. Since 82ee22d49f959284e72470110998c507129ce948 we don't do this anymore and instead try to handle the stack in a bit more coordinated manner. However, for logical AND and OR operations, this exposed some stack pollution. This commit works around a prior hack to avoid this stack pollution.
> SONARJAVA-4420 Fix exception due to stack pollution

- its/plugin/tests/src/test/java/com/sonar/it/java/suite/SonarLintTest.java
- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalSensorContext.java
- java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/internal/InternalSensorContextTest.java
- java-frontend/src/main/java/org/sonar/java/reporting/InternalJavaIssueBuilder.java
- java-frontend/src/main/java/org/sonar/java/reporting/JavaQuickFix.java
- java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/java/reporting/InternalJavaIssueBuilderTest.java
- pom.xml
Upgraded sonarlint-plugin-api to version 8.18 and sonar-plugin-api to version 9.13 in lockstep to facilitate the migration of the quickfixes API from sonarlint-plugin-apo to the common sonar-plugin-api.
> SONARJAVA-4445 Upgrade sonarlint-plugin-api to version 8.18

- java-frontend/src/main/java/org/sonar/java/SonarComponents.java
- java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
- java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
The current implementation does not provide the best approach to log common issues between files and currently only logs the filename instead of the full path.
This reverts commit d165c98dcb4db03c450ca1ffcf416e00853f29ea.
> Revert SONARJAVA-4559 faulty implementation

- its/ruling/src/test/java/org/sonar/java/it/AutoScanTest.java
This will allow us to see all failing assertions instead of only the first one.
> [No Jira] Improve AutoScanTest assertions by using soft assertions

- java-checks-test-sources/pom.xml
- pom.xml
Can be tested by adding a local repository to the top-level pom and running `mvn clean deploy`.
An example of a local repository in your pom.xml
```xml
<distributionManagement>
<repository>
<id>local-folder</id>
<name>Local folder to test deployment configuration</name>
<url>file:./local-deployment</url>
</repository>
</distributionManagement>
```
> SONARJAVA-4664 Disable deployment of java-check-test-sources artifacts

- .cirrus.yml
The goal is to experiment with a new build method that separates the build from the tests and analysis. This will allow us to start the integration tests just after the build and not wait for the analysis to be completed.
> [NO JIRA] Improve CI performance, split compile, test and analysis

- java-checks-test-sources/aws/pom.xml
- java-checks-test-sources/default/pom.xml
- java-checks-test-sources/pom.xml
- java-checks-test-sources/test-classpath-reader/pom.xml
From
```
[INFO] SonarQube Java :: Test Sources ..................... SUCCESS [  0.006 s]
[INFO] SonarQube Java :: AWS Checks Test Sources .......... SUCCESS [  0.010 s]
[INFO] SonarQube Java :: Default Checks Test Sources ...... SUCCESS [  0.449 s]
[INFO] test-classpath-reader ............ SUCCESS [  0.009 s]
```
To
```
[INFO] SonarQube Java :: Checks Test Sources :: Parent Pom SUCCESS [  0.004 s]
[INFO] SonarQube Java :: Checks Test Sources :: AWS ....... SUCCESS [  0.004 s]
[INFO] SonarQube Java :: Checks Test Sources :: Default ... SUCCESS [  0.005 s]
[INFO] SonarQube Java :: Checks Test Sources :: Test Classpath Reader SUCCESS [  0.005 s]
```
> [NO JIRA] Fix not consistent maven module names

- java-checks-test-sources/default/src/main/java/checks/spring/DirectBeanMethodInvocationWithoutProxyCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/spring/DirectBeanMethodInvocationWithoutProxyCheck.java
Issues should only be raise when the method would be proxied if `proxyBeanMethods` was set to `true`. While this is the case for `@Bean` annotated methods, it is not the case for other methods.
> SONARJAVA-4685 Remove FP on invocation of non-bean methods

- its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
- its/autoscan/src/test/resources/autoscan/diffs/diff_S1161.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S1874.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S1948.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S2092.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S2160.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S2226.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S2441.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S3330.json
- java-checks-test-sources/default/src/main/java/checks/ServletInstanceFieldCheckJakarta.java
- java-checks-test-sources/default/src/main/java/checks/regex/RegexComplexityCheck.java
- java-checks-test-sources/default/src/main/java/checks/regex/ReluctantQuantifierWithEmptyContinuationCheck.java
- java-checks-test-sources/default/src/main/java/checks/security/SecureCookieCheck.java
- java-checks-test-sources/default/src/main/java/checks/security/SecureCookieCheckJakarta.java
- java-checks-test-sources/default/src/main/java/checks/serialization/SerializableObjectInSessionCheck.java
- java-checks/src/main/java/org/sonar/java/checks/ServletInstanceFieldCheck.java
- java-checks/src/main/java/org/sonar/java/checks/security/SecureCookieCheck.java
- java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableObjectInSessionCheck.java
- java-checks/src/test/java/org/sonar/java/checks/ServletInstanceFieldCheckTest.java
- java-checks/src/test/java/org/sonar/java/checks/security/SecureCookieCheckTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/SanityTest.java
Add support for the Jakarta namespace for the following checks:
* RegexComplexityCheck
* ReluctantQuantifierWithEmptyContinuationCheck
* SecureCookieCheck
* SerializableObjectInSessionCheck
* ServletInstanceFieldCheck
> SONARJAVA-4638 Improve Jakarta support

- .cirrus.yml
There is an infrastructure change on CirrusCI EKS cluster: we are about to replace all the various node instance types with unique `m6a.8xlarge`.
This PR updates the reference. An alternative would be to remove the nodeSelectorTerms. If another instance type is required, this will require additional work on the cluster node groups.
See https://github.com/SonarSource/cirrus-ci-infra/pull/114
To be merged after deployment to prod: https://github.com/SonarSource/cirrus-ci-infra/actions/runs/8007883775/job/21873413072
> BUILD-4576 node instance type update

- its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S6912.json
- its/ruling/src/test/resources/eclipse-jetty/java-S6912.json
- java-checks-test-sources/default/src/main/java/checks/BatchSQLStatementsCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/BatchSQLStatementsCheck.java
Reduce the rule scope to raise issues only on Statements executed in the loop body directly, i.e. not enclosed in other instructions.
> Reduce rule S6912 scope

- .cirrus.yml
SQ 10 seems to have issues with nondeterministic responses of the rule list in some cases. This causes ITs to fail randomly. As a workaround, we should use the LTS version until this is fixed.
> Temporarily use LATEST_RELEASE[9.9] for ITs

- its/ruling/src/test/resources/guava/java-S2694.json
- java-checks/src/main/java/org/sonar/java/checks/InnerStaticClassesCheck.java
- java-checks/src/test/files/checks/InnerStaticClassesCheckSample.java
- java-checks/src/test/java/org/sonar/java/checks/InnerStaticClassesCheckTest.java
- sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2694.html
The changes are split into 2 commits:
1. the first commit has the fix that avoids reporting in the case of local classes
2. the second commit is a rework to improve the readability and understanding of the implementation logic. It separates the state of the rule, i.e. the logic that detects if a nested class references an outer class into a nested static class.
> SONARJAVA-4829: Fix FP in S2694 on local classes

- its/autoscan/src/test/resources/autoscan/autoscan-diff-by-rules.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S3655.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S5960.json
- java-checks-test-sources/default/src/main/java/symbolicexecution/checks/OptionalGetBeforeIsPresentCheck_jdk11.java
- java-symbolic-execution/src/main/java/org/sonar/java/se/xproc/BehaviorCache.java
- java-symbolic-execution/src/main/resources/org/sonar/java/se/xproc/org.junit.json
- java-symbolic-execution/src/main/resources/org/sonar/java/se/xproc/org.junit.jupiter.api.json
- java-symbolic-execution/src/test/java/org/sonar/java/se/xproc/BehaviorCacheTest.java
This PR adds support for some methods of the Junit framework (`assertTrue`, `assertFalse`, and `fail`, not all overloads) to the SE engine.
> SONARJAVA-4520 Rule S3655: False Positive with JUnit assertions

- java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
- java-frontend/src/main/java/org/sonar/java/SonarComponents.java
- java-frontend/src/main/java/org/sonar/java/caching/CacheContextImpl.java
- java-frontend/src/main/java/org/sonar/java/caching/ContentHashCache.java
- java-frontend/src/main/java/org/sonar/java/model/DefaultModuleScannerContext.java
- java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/InputFileScannerContext.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/ModuleScannerContext.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/caching/SonarLintCache.java
- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/java/caching/CacheContextImplTest.java
- java-frontend/src/test/java/org/sonar/java/caching/ContentHashCacheTest.java
- java-frontend/src/test/java/org/sonar/java/model/DefaultModuleScannerContextTest.java
- java-frontend/src/test/java/org/sonar/java/testing/VisitorsBridgeForTestsTest.java
- java-frontend/src/test/java/org/sonar/plugins/java/api/caching/SonarLintCacheTest.java
- sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaPlugin.java
- sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaPluginTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java
> SONARJAVA-4988: Use SonarLintCache component and make it accessible to custom rules via the caching APIs

- its/ruling/src/test/resources/eclipse-jetty/java-S1312.json
- java-checks/src/main/java/org/sonar/java/checks/LoggersDeclarationCheck.java
- java-checks/src/test/files/checks/LoggersDeclarationCheckInterface.java
- java-checks/src/test/java/org/sonar/java/checks/LoggersDeclarationCheckTest.java
Should not report on interfaces since fields cannot be private and static final is redundant.
> SONARJAVA-5089 S1312 should not report on interfaces

- .cirrus.yml
As the container was frequently killed with OOM already during the maven cache population.
> [NO JIRA] Increase sanity task memory

- .cirrus.yml
[SONARJAVA-5175](https://sonarsource.atlassian.net/browse/SONARJAVA-5175)
[SONARJAVA-5175]: https://sonarsource.atlassian.net/browse/SONARJAVA-5175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5175 Remove subnet configuration from .cirrus.yml. This is provided by the cirrus-modules v3

- .cirrus.yml
- docs/java-custom-rules-example/pom_SQ_10_6_LATEST.xml
[SONARJAVA-5173](https://sonarsource.atlassian.net/browse/SONARJAVA-5173)
We were not able to compile some tests, because
org.sonar.api.testfixtures.log.LogTester moved to
sonar-plugin-api-test-fixtures.
Tested with `mvn clean install -f pom_SQ_10_6_LATEST.xml`
[SONARJAVA-5173]: https://sonarsource.atlassian.net/browse/SONARJAVA-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5173 Fix broken docs for SQ_10_6.

- java-frontend/src/main/java/org/sonar/java/model/JParser.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
[SONARJAVA-5015](https://sonarsource.atlassian.net/browse/SONARJAVA-5015)
[SONARJAVA-5015]: https://sonarsource.atlassian.net/browse/SONARJAVA-5015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5015 Improve the tolerance to syntax errors when parsing switch expressions

- java-frontend/src/main/java/org/sonar/plugins/java/api/semantic/MethodMatchers.java
[SONARJAVA-5179](https://sonarsource.atlassian.net/browse/SONARJAVA-5179)
Improve rendering.
Fixes #4817 
[SONARJAVA-5179]: https://sonarsource.atlassian.net/browse/SONARJAVA-5179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5179 Improve Javadoc in MethodMatchers.java

- java-checks-test-sources/default/src/main/java/checks/BoxedBooleanExpressionsCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/BoxedBooleanExpressionsCheck.java
[SONARJAVA-5184](https://sonarsource.atlassian.net/browse/SONARJAVA-5184)
[SONARJAVA-5184]: https://sonarsource.atlassian.net/browse/SONARJAVA-5184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5184 Suppress boxed Boolean warnings on @NonNull parameters.

- sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S5411.html
- sonarpedia.json
[SONARJAVA-5178](https://sonarsource.atlassian.net/browse/SONARJAVA-5178)
[SONARJAVA-5178]: https://sonarsource.atlassian.net/browse/SONARJAVA-5178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5178 Update RSPEC before 8.7 release

- external-reports/src/main/resources/org/sonar/l10n/java/rules/checkstyle/rules.json
[SONARJAVA-5224](https://sonarsource.atlassian.net/browse/SONARJAVA-5224)
> SONARJAVA-5224 Update checkstyle rule mappings

- its/ruling/src/test/resources/sonar-server/java-S2201.json
- java-checks-test-sources/default/src/main/java/checks/S2201_IgnoredReturnValueCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/IgnoredReturnValueCheck.java
[SONARJAVA-5185](https://sonarsource.atlassian.net/browse/SONARJAVA-5185)
Part of 
[SONARJAVA-5185]: https://sonarsource.atlassian.net/browse/SONARJAVA-5185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5185 exclude Optional.orElseThrow from S2201 as it has side effects

- java-checks-test-sources/default/src/main/java/checks/StringIsEmptyCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/StringIsEmptyCheck.java
[SONARJAVA-5221](https://sonarsource.atlassian.net/browse/SONARJAVA-5221)
[SONARJAVA-5221]: https://sonarsource.atlassian.net/browse/SONARJAVA-5221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5221 QuickFix for S7158 (String.isEmpty() instead of length check).

- java-checks-test-sources/default/src/main/files/non-compiling/checks/serialization/SerializableFieldInSerializableClassCheckSample.java
- java-checks-test-sources/default/src/main/java/checks/serialization/SerializableFieldInSerializableClassCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/serialization/SerializableFieldInSerializableClassCheck.java
https://sonarsource.atlassian.net/browse/SONARJAVA-5238
Messages to make fields serializable or transient are created only for non-static fields. We make this explicit to mildly suggest making a field static as a fix for the problem.
An alternative is to change the message to "Make fieldName serializable, transient, or static", but it might be confusing why we suggest making a field static (often, it will not be possible).
> SONARJAVA-5238 Clarify that serialization applies only to non-static fields.

- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaComplexityTest.java
Part of [SONARJAVA-5239](https://sonarsource.atlassian.net/browse/SONARJAVA-5239)
Remove obsolete test that prevents QA from succeeding.
[SONARJAVA-5239]: https://sonarsource.atlassian.net/browse/SONARJAVA-5239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5239 Remove obsolete test that uses removed SonarQube metric

- its/autoscan/src/test/java/org/sonar/java/it/AutoScanTest.java
- its/autoscan/src/test/resources/autoscan/diffs/diff_S2187.json
- java-checks-test-sources/default/src/main/files/non-compiling/checks/NoTestInTestClassCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/tests/NoTestInTestClassCheck.java
- java-checks/src/test/java/org/sonar/java/checks/tests/NoTestInTestClassCheckTest.java
[SONARJAVA-4446](https://sonarsource.atlassian.net/browse/SONARJAVA-4446)
If any symbol is not known, do not raise an issue to avoid false positives.
[SONARJAVA-4446]: https://sonarsource.atlassian.net/browse/SONARJAVA-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4446 Check if the parent class or implemented interface symbols of the test class are known.

- its/autoscan/src/test/resources/autoscan/diffs/diff_S2187.json
- java-checks-test-sources/default/src/main/files/non-compiling/checks/NoTestInTestClassCheckSample.java
- java-checks-test-sources/default/src/test/java/checks/tests/NoTestInTestClassCheckTestNgTest.java
- java-checks/src/main/java/org/sonar/java/checks/tests/NoTestInTestClassCheck.java
- java-checks/src/test/java/org/sonar/java/checks/tests/NoTestInTestClassCheckTest.java
[SONARJAVA-4424](https://sonarsource.atlassian.net/browse/SONARJAVA-4424)
Part of 
[SONARJAVA-4424]: https://sonarsource.atlassian.net/browse/SONARJAVA-4424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4424 add methods annotated with @Test to the list of testNg test methods

- java-symbolic-execution/java-symbolic-execution-plugin/src/main/java/org/sonar/java/se/checks/UnclosedResourcesCheck.java
- java-symbolic-execution/java-symbolic-execution-plugin/src/test/files/se/UnclosedResourcesLombokCheck.java
- java-symbolic-execution/java-symbolic-execution-plugin/src/test/java/org/sonar/java/se/checks/UnclosedResourcesCheckTest.java
https://sonarsource.atlassian.net/browse/SONARJAVA-4436
> SONARJAVA-4436 Fix FP on S2095 when using @lombok.Cleanup

- java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
- java-checks/src/test/files/filters/LombokFilterWithoutSemantic.java
- java-checks/src/test/java/org/sonar/java/filters/LombokFilterTest.java
https://sonarsource.atlassian.net/browse/SONARJAVA-4973
> SONARJAVA-4973 Fix FP on S1118 with Lombok @UtilityClass in automatic analysis

- its/ruling/src/test/resources/sonar-server/java-S1075.json
- java-checks-test-sources/default/src/main/files/non-compiling/checks/HardcodedURICheckSample.java
- java-checks-test-sources/default/src/main/java/checks/HardcodedURICheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/HardcodedURICheck.java
- java-checks/src/test/java/org/sonar/java/checks/HardcodedURICheckTest.java
[SONARJAVA-5149](https://sonarsource.atlassian.net/browse/SONARJAVA-5149)
[SONARJAVA-5149]: https://sonarsource.atlassian.net/browse/SONARJAVA-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5149 S1075: find when uri is short and relative and stop raising issues

- java-checks-test-sources/default/src/test/java/checks/tests/IgnoredTestsCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/AnnotationsHelper.java
- java-checks/src/main/java/org/sonar/java/checks/tests/IgnoredTestsCheck.java
- java-checks/src/main/java/org/sonar/java/filters/LombokFilter.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/AnnotationsHelperTest.java
- java-checks/src/test/java/org/sonar/java/filters/LombokFilterTest.java
[SONARJAVA-5258](https://sonarsource.atlassian.net/browse/SONARJAVA-5258)
[SONARJAVA-5258]: https://sonarsource.atlassian.net/browse/SONARJAVA-5258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5258 Report secondary location on annotation in S1607.

- java-checks-test-sources/default/src/test/java/checks/tests/SwitchAtLeastThreeCasesCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/SwitchAtLeastThreeCasesCheck.java
- java-checks/src/test/files/checks/SwitchAtLeastThreeCasesCheck.java
- java-checks/src/test/java/org/sonar/java/checks/SwitchAtLeastThreeCasesCheckTest.java
[SONARJAVA-4441](https://sonarsource.atlassian.net/browse/SONARJAVA-4441)
[SONARJAVA-4441]: https://sonarsource.atlassian.net/browse/SONARJAVA-4441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4441 Fix FP on S1301 when mutiple `case` labels are used in Java 14 `switch`.

- java-checks-test-sources/default/src/main/java/checks/VirtualThreadNotSynchronizedCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/VirtualThreadNotSynchronizedCheck.java
[SONARJAVA-5265](https://sonarsource.atlassian.net/browse/SONARJAVA-5265)
[SONARJAVA-5265]: https://sonarsource.atlassian.net/browse/SONARJAVA-5265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5265 S6906 ClassCastException: IdentifierTreeImpl cannot be cast to MemberSelectExpressionTree

- its/autoscan/src/test/resources/autoscan/diffs/diff_S2187.json
- java-checks-test-sources/default/pom.xml
- java-checks-test-sources/default/src/test/java/checks/tests/NoTestInTestClassCheckCucumberTest.java
- java-checks-test-sources/default/src/test/java/checks/tests/NoTestInTestClassCheckCucumberWithoutSemanticTest.java
- java-checks/src/main/java/org/sonar/java/checks/tests/NoTestInTestClassCheck.java
- java-checks/src/test/java/org/sonar/java/checks/tests/NoTestInTestClassCheckTest.java
[SONARJAVA-5262](https://sonarsource.atlassian.net/browse/SONARJAVA-5262)
[SONARJAVA-5262]: https://sonarsource.atlassian.net/browse/SONARJAVA-5262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5262 Fix FP on S2187 in Cucumber tests with JUnit5.

- java-checks-test-sources/default/src/main/java/checks/regex/RedundantRegexAlternativesCheckSample.java
[SONARJAVA-5259](https://sonarsource.atlassian.net/browse/SONARJAVA-5259)
[SONARJAVA-5259]: https://sonarsource.atlassian.net/browse/SONARJAVA-5259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5259 Migrate secondary locations in RedundantRegexAlternativesCheckSample to the new syntax

- its/plugin/tests/src/test/java/com/sonar/it/java/suite/SonarLintTest.java
- pom.xml
- sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSensor.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java
[SONARJAVA-5296](https://sonarsource.atlassian.net/browse/SONARJAVA-5296)
[SONARJAVA-5296]: https://sonarsource.atlassian.net/browse/SONARJAVA-5296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5296 Report Java version via addTelemetryProperty().

- java-checks-test-sources/default/src/main/java/checks/PublicStaticMutableMembersCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/PublicStaticMutableMembersCheck.java
[SONARJAVA-4876](https://sonarsource.atlassian.net/browse/SONARJAVA-4876)
[SONARJAVA-4876]: https://sonarsource.atlassian.net/browse/SONARJAVA-4876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4876 FP in rule S2386 when collection was created with `Stream.toList()`

- docs/CUSTOM_RULES_101.md
[SONARJAVA-5333](https://sonarsource.atlassian.net/browse/SONARJAVA-5333)
The previous link was referencing an older version of the xml file which is no longer present in the repository.
[SONARJAVA-5333]: https://sonarsource.atlassian.net/browse/SONARJAVA-5333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5333 DOC Fix xml link in CUSTOM_RULES_101.md

- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/java/TestUtils.java
- java-frontend/src/test/java/org/sonar/java/ast/JavaAstScannerTest.java
[SONARJAVA-5303](https://sonarsource.atlassian.net/browse/SONARJAVA-5303)
The Windows build task occasionally fails because a progress log line appears when the test runs a little longer than expected. With this change, the test accepts that the logs may contain some "XX% analyzed" lines.
[SONARJAVA-5303]: https://sonarsource.atlassian.net/browse/SONARJAVA-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5303 Fix flaky Windows QA build

- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/java/TestUtils.java
- java-frontend/src/test/java/org/sonar/java/testing/ThreadLocalLogTester.java
[SONARJAVA-5303](https://sonarsource.atlassian.net/browse/SONARJAVA-5303)
With this change we should avoid the togs being polluted by messages coming from different threads.
[SONARJAVA-5303]: https://sonarsource.atlassian.net/browse/SONARJAVA-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5303 Replace logTester by ThreadLocalLogTester

- its/autoscan/src/test/resources/autoscan/diffs/diff_S2699.json
- java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/AssertJ.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/UnitTestUtilsTest.java
[SONARJAVA-5256](https://sonarsource.atlassian.net/browse/SONARJAVA-5256)
There are many methods that can be used to write assertions with AssertJ. The previous pattern was only recognizing a couple of assertJ classes.
With this PR we generalize the pattern for recognizing AssertJ assertion methods so that it applies to many of these classes.
[SONARJAVA-5256]: https://sonarsource.atlassian.net/browse/SONARJAVA-5256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5256 Fix false positives on S2699 for AssertJ assertions

- java-checks-test-sources/default/pom.xml
- java-checks-test-sources/default/src/test/java/checks/tests/AssertionsInTestsCheck/AssertJ.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
[SONARJAVA-5256](https://sonarsource.atlassian.net/browse/SONARJAVA-5256)
Fixes some false positive introduced by the previous PR for rule S2699
[SONARJAVA-5256]: https://sonarsource.atlassian.net/browse/SONARJAVA-5256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5256 Consider classes extending AssertJ AbstractAssert as assertion classes

- java-checks-test-sources/default/src/main/java/filters/SpringFilter.java
- java-checks/src/main/java/org/sonar/java/filters/SpringFilter.java
[SONARJAVA-5128](https://sonarsource.atlassian.net/browse/SONARJAVA-5128)
When the method is marked as autowired, it makes sense to have some optional parameter because of the way Spring resolve dependencies.
[SONARJAVA-5128]: https://sonarsource.atlassian.net/browse/SONARJAVA-5128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5128 Disable Optional parameter check for autowired methods

- java-checks-test-sources/default/src/main/java/checks/BoxedBooleanExpressionsCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/BoxedBooleanExpressionsCheck.java
[SONARJAVA-5146](https://sonarsource.atlassian.net/browse/SONARJAVA-5146)
When we have a `Optional.map` called on a lambda, we now the value for the parameters will never be null, so the check for rule S5411 is not useful and can be skipped. 
We this PR we keep track of the variables in the current scope that are known to be safe. 
[SONARJAVA-5146]: https://sonarsource.atlassian.net/browse/SONARJAVA-5146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5146 Fix false positive in Optional.map lambdas in rule S5411

- java-checks-test-sources/default/src/main/java/checks/InstanceOfPatternMatching.java
- java-checks/src/main/java/org/sonar/java/checks/InstanceOfPatternMatchingCheck.java
[SONARJAVA-5304](https://sonarsource.atlassian.net/browse/SONARJAVA-5304)
Array type names cannot directly be used as variable names as they contain square brackets ([]).
[SONARJAVA-5304]: https://sonarsource.atlassian.net/browse/SONARJAVA-5304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5304 Improve issue message in case of array type cast in S6201

- its/autoscan/src/test/resources/autoscan/diffs/diff_S3752.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S6856.json
- java-checks-test-sources/default/src/main/java/checks/MissingPathVariableAnnotationCheckSample.java
- java-checks-test-sources/default/src/main/java/checks/spring/MissingPathVariableAnnotationCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/MissingPathVariableAnnotationCheck.java
- java-checks/src/main/java/org/sonar/java/checks/spring/MissingPathVariableAnnotationCheck.java
- java-checks/src/test/java/org/sonar/java/checks/spring/MissingPathVariableAnnotationCheckTest.java
[SONARJAVA-5324](https://sonarsource.atlassian.net/browse/SONARJAVA-5324)
[SONARJAVA-5324]: https://sonarsource.atlassian.net/browse/SONARJAVA-5324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5324 @PathVariable must have path template placeholder

- its/autoscan/src/test/resources/autoscan/diffs/diff_S5786.json
- its/autoscan/src/test/resources/autoscan/diffs/diff_S5810.json
- its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S5786.json
- its/ruling/src/test/resources/eclipse-jetty/java-S5786.json
- java-checks-test-sources/default/src/test/java/checks/tests/JUnit5DefaultPackageClassAndMethodCheckSample.java
- java-checks-test-sources/default/src/test/java/checks/tests/JUnit5SilentlyIgnoreClassAndMethodCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/UnitTestUtils.java
- java-checks/src/main/java/org/sonar/java/checks/tests/AbstractJUnit5NotCompliantModifierChecker.java
- java-checks/src/main/java/org/sonar/java/checks/tests/JUnit5DefaultPackageClassAndMethodCheck.java
- java-checks/src/main/java/org/sonar/java/checks/tests/JUnit5SilentlyIgnoreClassAndMethodCheck.java
[SONARJAVA-5041](https://sonarsource.atlassian.net/browse/SONARJAVA-5041)
[SONARJAVA-5041]: https://sonarsource.atlassian.net/browse/SONARJAVA-5041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5041 S5786 should raise an issue on JUnit5 annotated lifecycle methods with a public modifier

- java-checks-test-sources/default/src/main/files/non-compiling/checks/SwitchWithTooManyCasesCheckCustom.java
- java-checks/src/main/java/org/sonar/java/checks/SwitchWithTooManyCasesCheck.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/TernaryValue.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/TernaryValueTest.java
[SONARJAVA-5341](https://sonarsource.atlassian.net/browse/SONARJAVA-5341)
When we don't know if the symbol in the switch is an enum, we shouldn't raise that issue.
[SONARJAVA-5341]: https://sonarsource.atlassian.net/browse/SONARJAVA-5341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5341 Fix FP reported for too many cases on switches when enum types are unknown

- its/ruling/src/test/resources/commons-beanutils/java-S1192.json
- its/ruling/src/test/resources/eclipse-jetty-similar-to-main/java-S1192.json
- its/ruling/src/test/resources/eclipse-jetty/java-S1192.json
- its/ruling/src/test/resources/guava/java-S1192.json
- java-checks-test-sources/default/src/main/java/checks/StringLiteralDuplicatedCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/StringLiteralDuplicatedCheck.java
- java-checks/src/test/java/org/sonar/java/checks/StringLiteralDuplicatedCheckTest.java
[SONARJAVA-5232](https://sonarsource.atlassian.net/browse/SONARJAVA-5232)
Previously  #4984 and #5006
[SONARJAVA-5232]: https://sonarsource.atlassian.net/browse/SONARJAVA-5232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5232 S1192 Relax duplicate string check for Throwable arguments

- .cirrus.yml
[SONARJAVA-5417](https://sonarsource.atlassian.net/browse/SONARJAVA-5417)
Update the CI SCA configuration to exclude a few directories that appear to contain test fixtures. Since test fixtures are generally not relevant for SCA, this change should help remove false positives and improve scan performance.
If these exclusions don't quite match your needs, I'm happy to further adjust the PR. Alternatively, code owners can choose to close this PR and create your own PR. Ultimately, you have the final say on which files should be analyzed for SCA.
After this change, the following files will be analyzed by SCA:
```
check-list/maven-dependency-tree.txt
docs/java-custom-rules-example/maven-dependency-tree.txt
docs/java-custom-rules-example/pom.xml
docs/maven-dependency-tree.txt
docs/pom.xml …
```
> SONARJAVA-5417 Exclude test fixtures from SCA analysis

- java-checks-test-sources/default/src/main/java/checks/VarCanBeUsedCheck.java
- java-frontend/src/main/java/org/sonar/java/model/JMethodSymbol.java
- java-frontend/src/main/java/org/sonar/java/model/JSymbol.java
- java-frontend/src/test/java/org/sonar/java/model/JMethodSymbolTest.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
- java-frontend/src/test/java/org/sonar/java/model/JSymbolTest.java
- java-frontend/src/test/java/org/sonar/java/model/JVariableSymbolTest.java
[SONARJAVA-5338](https://sonarsource.atlassian.net/browse/SONARJAVA-5338)
The computation of owners in lambdas was returning the interface method implemented by the lambda (for instance accept for Function) which doesn't allow distinguishing between symbols declared in different lambdas in different methods with the same variable name.
[SONARJAVA-5338]: https://sonarsource.atlassian.net/browse/SONARJAVA-5338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5338 Fix variable owner in the case of lambdas

- java-checks-test-sources/default/src/main/java/checks/StaticMethodCheckSample.java
- java-checks-test-sources/default/src/main/java/checks/VarCanBeUsedCheck.java
- java-frontend/src/main/java/org/sonar/java/model/JMethodSymbol.java
- java-frontend/src/main/java/org/sonar/java/model/JSymbol.java
- java-frontend/src/test/java/org/sonar/java/model/JMethodSymbolTest.java
- java-frontend/src/test/java/org/sonar/java/model/JParserSemanticTest.java
- java-frontend/src/test/java/org/sonar/java/model/JSymbolTest.java
- java-frontend/src/test/java/org/sonar/java/model/JVariableSymbolTest.java
[SONARJAVA-5338](https://sonarsource.atlassian.net/browse/SONARJAVA-5338)
We observed that in some cases, in particular recursive method inside generic classes, the same method binding could be attributed different keys. The changes in this PR work around this problem by only using the key comparison for lambda methods (which cannot be recursive). 
[SONARJAVA-5338]: https://sonarsource.atlassian.net/browse/SONARJAVA-5338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5338 Do not compare method binding key for non-lambdas

- external-reports/src/main/resources/org/sonar/l10n/java/rules/spotbugs/findsecbugs-rules.json
- external-reports/src/main/resources/org/sonar/l10n/java/rules/spotbugs/spotbugs-rules.json
[SONARJAVA-5516](https://sonarsource.atlassian.net/browse/SONARJAVA-5516)
[SONARJAVA-5516]: https://sonarsource.atlassian.net/browse/SONARJAVA-5516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5516 Update external rules

- java-checks-test-sources/default/src/main/java/checks/DefaultInitializedFieldCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
- java-frontend/src/main/java/org/sonar/java/model/LiteralUtils.java
- java-frontend/src/test/java/org/sonar/java/model/LiteralUtilsTest.java
[SONARJAVA-5522](https://sonarsource.atlassian.net/browse/SONARJAVA-5522)
[SONARJAVA-5522]: https://sonarsource.atlassian.net/browse/SONARJAVA-5522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5522 S3052: Let DefaultInitializedFieldCheck handle underscores in float/double literals

- java-checks-test-sources/default/src/main/java/checks/DefaultInitializedFieldCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/DefaultInitializedFieldCheck.java
- java-frontend/src/main/java/org/sonar/java/model/LiteralUtils.java
- java-frontend/src/test/java/org/sonar/java/model/LiteralUtilsTest.java
[SONARJAVA-5522](https://sonarsource.atlassian.net/browse/SONARJAVA-5522)
[SONARJAVA-5522]: https://sonarsource.atlassian.net/browse/SONARJAVA-5522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert SONARJAVA-5522 to wait for the external contributor agreement

- its/autoscan/src/test/resources/autoscan/diffs/diff_S6856.json
- java-checks-test-sources/default/src/main/java/checks/spring/MissingPathVariableAnnotationCheckSample.java
- java-checks-test-sources/default/src/main/java/checks/spring/MissingPathVariableParentInDifferentSample.java
- java-checks/src/main/java/org/sonar/java/checks/spring/MissingPathVariableAnnotationCheck.java
[SONARJAVA-4901](https://sonarsource.atlassian.net/browse/SONARJAVA-4901)
Part of 
[SONARJAVA-4901]: https://sonarsource.atlassian.net/browse/SONARJAVA-4901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4901 S6856 does not raise when parent class defines model attribute

- java-checks-test-sources/default/src/main/java/checks/regex/UnusedGroupNamesCheck.java
- java-checks/src/main/java/org/sonar/java/checks/regex/AbstractRegexCheckTrackingMatchers.java
[SONARJAVA-5101](https://sonarsource.atlassian.net/browse/SONARJAVA-5101)
There is an existing mechanism to track regex that escape analysis when they are passed in a constructor to another class or returned. We use the same mechanism to exclude regex used in lambdas and method references.
[SONARJAVA-5101]: https://sonarsource.atlassian.net/browse/SONARJAVA-5101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5101 Fix FP on S5860 when Regex are used in lambdas

- java-checks-test-sources/default/src/main/files/non-compiling/checks/MissingDeprecatedCheckWithRecords.java
- java-checks-test-sources/default/src/main/java/checks/MissingDeprecatedCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/MissingDeprecatedCheck.java
[SONARJAVA-5274](https://sonarsource.atlassian.net/browse/SONARJAVA-5274)
[SONARJAVA-5274]: https://sonarsource.atlassian.net/browse/SONARJAVA-5274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5274 Fix FP in S1123 on deprecated record fields.

- java-checks/src/main/java/org/sonar/java/checks/EmptyBlockCheck.java
- java-checks/src/test/files/checks/EmptyBlock.java
[SONARJAVA-5436](https://sonarsource.atlassian.net/browse/SONARJAVA-5436)
This is to avoid user reporting FPs on this rule, but instead have them add comments about why the block is empty.
[SONARJAVA-5436]: https://sonarsource.atlassian.net/browse/SONARJAVA-5436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5436 Suggest to add comment in message for S108

- .cirrus.yml
[SONARJAVA-5542](https://sonarsource.atlassian.net/browse/SONARJAVA-5542)
`sonar.sca.excludedManifests` is deprecated in SQS 2025.3 and is replaced with `sonar.sca.exlusions`. The behavior is exactly the same, this is just a rename to better match other sonar properties.
[SONARJAVA-5542]: https://sonarsource.atlassian.net/browse/SONARJAVA-5542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5542 chore: use the renamed sonar.sca.exclusions property

- java-checks-test-sources/default/src/main/java/checks/StringPrimitiveConstructorCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/StringPrimitiveConstructorCheck.java
- java-checks/src/test/java/org/sonar/java/checks/StringPrimitiveConstructorCheckTest.java
[SONARJAVA-4376](https://sonarsource.atlassian.net/browse/SONARJAVA-4376)
When semantic is missing for the argument of String constructor for instance, the parser takes a guess at which constructor it is and this may cause some false positives. The fix in this PR, skips the case where we detect an unknown in the argument types. The second sample is comming from SONARJAVA-5388
[SONARJAVA-4376]: https://sonarsource.atlassian.net/browse/SONARJAVA-4376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4376 Fix S2129 in the case of missing semantic

- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/TestCheckRegistrarContext.java
- java-checks-testkit/src/test/java/org/sonar/java/checks/verifier/TestCheckRegistrarContextTest.java
- java-frontend/src/main/java/org/sonar/java/SonarComponents.java
- java-frontend/src/main/java/org/sonar/plugins/java/api/CheckRegistrar.java
- java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
- java-frontend/src/test/java/org/sonar/java/SonarComponentsTest.java
- java-frontend/src/test/java/org/sonar/plugins/java/api/CheckRegistrarTest.java
[SONARCH-708](https://sonarsource.atlassian.net/browse/SONARCH-708)
[SONARCH-708]: https://sonarsource.atlassian.net/browse/SONARCH-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARCH-708, SONARJAVA-5497: Extend SonarJava CheckRegistrar API for registering custom file scanner hooks

- its/autoscan/src/test/resources/autoscan/diffs/diff_S6857.json
- java-checks-test-sources/default/src/main/java/checks/spring/SpelExpressionCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/spring/SpelExpressionCheck.java
[SONARJAVA-4917](https://sonarsource.atlassian.net/browse/SONARJAVA-4917)
[SONARJAVA-4917]: https://sonarsource.atlassian.net/browse/SONARJAVA-4917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4917 S6857 support property placeholder inside SpEL

- its/autoscan/src/test/resources/autoscan/diffs/diff_S5778.json
- java-checks-test-sources/default/src/test/java/checks/tests/OneExpectedRuntimeExceptionCheckSample.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/MethodTreeUtils.java
- java-checks/src/main/java/org/sonar/java/checks/tests/OneExpectedRuntimeExceptionCheck.java
[SONARJAVA-4543](https://sonarsource.atlassian.net/browse/SONARJAVA-4543)
[SONARJAVA-4543]: https://sonarsource.atlassian.net/browse/SONARJAVA-4543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4543 S5778 does not report on final enum methods

- .github/workflows/UpdateRuleMetadata.yml
[SONARJAVA-5551](https://sonarsource.atlassian.net/browse/SONARJAVA-5551)
[SONARJAVA-5551]: https://sonarsource.atlassian.net/browse/SONARJAVA-5551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5551 Create GitHub action to update rule metadata.

- java-checks-test-sources/default/pom.xml
- java-symbolic-execution/java-symbolic-execution-checks-test-sources/pom.xml
[SONARJAVA-5550](https://sonarsource.atlassian.net/browse/SONARJAVA-5550)
Added `<arg>-Xlint:-deprecation</arg>` to remove deprecation warnings during maven-compiler in java-checks-test-sources, as we do not care about the code there.
Also specified for the symbolic-execution test sources modules all the annotation processors, to allow develocity to leverage the cache for that module. Locally improved my build time by ~8 secs
[SONARJAVA-5550]: https://sonarsource.atlassian.net/browse/SONARJAVA-5550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5550 Add some pom configuration to cleanup build logs and improve build caching

- java-checks-aws/src/test/java/org/sonar/java/checks/security/HardCodedCredentialsShouldNotBeUsedCheckTest.java
- java-checks-common/src/main/java/org/sonar/java/checks/helpers/CredentialMethod.java
- java-checks-common/src/test/java/org/sonar/java/checks/helpers/CredentialMethodTest.java
[SONARJAVA-4634](https://sonarsource.atlassian.net/browse/SONARJAVA-4634)
Adding a test for duplicated entries found a few cases where we could have false positives because of wildcard usage.
[SONARJAVA-4634]: https://sonarsource.atlassian.net/browse/SONARJAVA-4634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4634 Test for duplicates in credential method json file

- .github/workflows/ReleasabilityCheck.yml
[SONARJAVA-5568](https://sonarsource.atlassian.net/browse/SONARJAVA-5568)
Infra provides two similar but different checks (https://github.com/SonarSource/gh-action_releasability) so we cannot just add another trigger to the existing check.
It is not possible to test on a branch, but the code should be simple enough to copy-and-paste and then verify on master.
[SONARJAVA-5568]: https://sonarsource.atlassian.net/browse/SONARJAVA-5568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5568 Create continuous releasability check

- java-checks/src/main/java/org/sonar/java/checks/ParameterReassignedToCheck.java
- java-checks/src/main/java/org/sonar/java/checks/SwitchCaseWithoutBreakCheck.java
- java-checks/src/main/java/org/sonar/java/checks/TryWithResourcesCheck.java
- java-frontend/src/main/java/org/sonar/java/cfg/CFG.java
- java-frontend/src/test/java/org/sonar/java/cfg/CFGTest.java
[SONARJAVA-5628](https://sonarsource.atlassian.net/browse/SONARJAVA-5628)
Instead of causing the rule to crash with a stack trace in the logs
[SONARJAVA-5628]: https://sonarsource.atlassian.net/browse/SONARJAVA-5628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5628 In CFG computation, mark semantic incomplete for unexpected break

- java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
- java-frontend/src/main/java/org/sonar/java/model/VisitorsBridge.java
[SONARJAVA-5658](https://sonarsource.atlassian.net/browse/SONARJAVA-5658)
[SONARJAVA-5658]: https://sonarsource.atlassian.net/browse/SONARJAVA-5658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5658 Refactoring: simplify object construction in JavaFrontend constructor

- java-checks/src/main/java/org/sonar/java/checks/VirtualThreadNotSynchronizedCheck.java
- java-checks/src/test/java/org/sonar/java/checks/VirtualThreadNotSynchronizedCheckTest.java
[SONARJAVA-5443](https://sonarsource.atlassian.net/browse/SONARJAVA-5443)
Since java 24 synchronize block don't affect virtual thread pinning. Thus, we should not raise S6906 on version of java greater or equal to 24.
[SONARJAVA-5443]: https://sonarsource.atlassian.net/browse/SONARJAVA-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5443, S6906: Ignore issues when Java version is >= 24

- java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
- java-frontend/src/main/java/org/sonar/java/SonarComponents.java
- java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
- java-frontend/src/test/java/org/sonar/java/JavaVersionAwareVisitorTest.java
- java-frontend/src/test/java/org/sonar/java/MeasurerTest.java
- java-frontend/src/test/java/org/sonar/java/MeasurerTester.java
- java-frontend/src/test/java/org/sonar/java/TestUtils.java
- java-frontend/src/test/java/org/sonar/java/ast/visitors/FileLinesVisitorTest.java
- java-frontend/src/test/java/org/sonar/java/ast/visitors/SyntaxHighlighterVisitorTest.java
[SONARJAVA-5670](https://sonarsource.atlassian.net/browse/SONARJAVA-5670)
Null SonarComponents is used only tests. JavaFrontend is created in JavaSensor, which calls a method on SonarComponents before it is passed the the constructor, therefore the parameter can never be null in production.
Replacing those nulls with mocks will simplify the production code.
[SONARJAVA-5670]: https://sonarsource.atlassian.net/browse/SONARJAVA-5670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5670 Make SonarComponents in JavaFrontend not @Nullable.

- .cirrus.yml
- its/plugin/projects/servlet-jsp/src/test/java/EmptyTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/JspTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTutorialTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/TestUtils.java
- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/InternalCheckVerifier.java
- java-checks-testkit/src/main/java/org/sonar/java/checks/verifier/internal/JavaCheckVerifier.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/QuickFixHelperTest.java
- java-checks/src/test/java/org/sonar/java/filters/PostAnalysisIssueFilterTest.java
- java-frontend/src/main/java/org/sonar/java/ExecutionTimeReport.java
- java-frontend/src/main/java/org/sonar/java/JavaFrontend.java
- java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
- java-frontend/src/main/java/org/sonar/java/model/InputFileUtils.java
- java-frontend/src/main/java/org/sonar/java/telemetry/TelemetryKey.java
- java-frontend/src/test/java/org/sonar/java/JavaFrontendTest.java
- java-frontend/src/test/java/org/sonar/java/ast/JavaAstScannerTest.java
- java-frontend/src/test/java/org/sonar/java/ast/visitors/FileLinesVisitorTest.java
- java-frontend/src/test/java/org/sonar/java/classpath/ClasspathForMainTest.java
- java-frontend/src/test/java/org/sonar/java/classpath/ClasspathForTestTest.java
- java-frontend/src/test/java/org/sonar/java/model/InputFileUtilsTest.java
- java-frontend/src/test/java/org/sonar/java/model/JParserTest.java
- java-frontend/src/test/java/org/sonar/java/reporting/InternalJavaIssueBuilderTest.java
- java-frontend/src/test/java/org/sonar/java/reporting/JavaIssueTest.java
- java-frontend/src/test/java/org/sonar/java/telemetry/TelemetryKeyTest.java
- java-frontend/src/test/java/org/sonar/plugins/java/api/IssuableSubscriptionVisitorTest.java
- java-frontend/src/test/java/org/sonar/plugins/java/api/caching/SonarLintCacheTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaRulesDefinitionTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/SanityTest.java
[SONARJAVA-5695](https://sonarsource.atlassian.net/browse/SONARJAVA-5695)
[SONARJAVA-5695]: https://sonarsource.atlassian.net/browse/SONARJAVA-5695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5695 Report speed of analysis and analysis errors

- java-checks-test-sources/default/src/main/files/non-compiling/checks/SQLInjectionSample.java
- java-checks-test-sources/default/src/main/java/checks/SQLInjection.java
- java-checks/src/main/java/org/sonar/java/checks/SQLInjectionCheck.java
- java-checks/src/test/java/org/sonar/java/checks/SQLInjectionCheckTest.java
[SONARJAVA-5683](https://sonarsource.atlassian.net/browse/SONARJAVA-5683)
[SONARJAVA-5683]: https://sonarsource.atlassian.net/browse/SONARJAVA-5683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5683 S2077 Fix FN on strings built with String.format()/formatted().

- its/plugin/tests/src/test/java/com/sonar/it/java/JspTest.java
- its/plugin/tests/src/test/java/com/sonar/it/java/suite/JavaTutorialTest.java
- java-frontend/src/main/java/org/sonar/java/ast/JavaAstScanner.java
- java-frontend/src/main/java/org/sonar/java/telemetry/TelemetryKey.java
- java-frontend/src/test/java/org/sonar/java/telemetry/TelemetryKeyTest.java
- sonar-java-plugin/src/test/java/org/sonar/plugins/java/JavaSensorTest.java
[SONARJAVA-5698](https://sonarsource.atlassian.net/browse/SONARJAVA-5698)
[SONARJAVA-5698]: https://sonarsource.atlassian.net/browse/SONARJAVA-5698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5698 Report Eclipse parser type errors

- java-checks/src/main/java/org/sonar/java/checks/DisallowedConstructorCheck.java
- java-checks/src/main/java/org/sonar/java/checks/DisallowedMethodCheck.java
- java-checks/src/main/java/org/sonar/java/checks/PatternUtils.java
[SONARJAVA-5740](https://sonarsource.atlassian.net/browse/SONARJAVA-5740)
We can use standard String::trim() because the results of splitting a String cannot be null.
[SONARJAVA-5740]: https://sonarsource.atlassian.net/browse/SONARJAVA-5740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5740 Stop using StringUtils::trim

- .github/workflows/PrepareNextIteration.yml
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/ReleasabilityCheck.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- .github/workflows/ToggleLockBranch.yml
- .github/workflows/UpdateRuleMetadata.yml
- .github/workflows/dogfood.yml
- .github/workflows/mark-prs-stale.yml
- .github/workflows/releasability.yaml
- .github/workflows/slack_notify.yml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
> BUILD-8875: Migrate to standardized GitHub runner names

- java-checks/src/main/java/org/sonar/java/checks/DeprecatedTagPresenceCheck.java
- java-checks/src/main/java/org/sonar/java/checks/helpers/DeprecatedCheckerHelper.java
- java-checks/src/main/java/org/sonar/java/checks/spring/SpringComposedRequestMappingCheck.java
- java-checks/src/test/files/checks/DeprecatedTagPresenceCheck.java
- java-checks/src/test/java/org/sonar/java/checks/helpers/DeprecatedCheckerHelperTest.java
- java-frontend/src/main/java/org/sonar/java/model/ExpressionUtils.java
- java-frontend/src/test/java/org/sonar/java/model/ExpressionUtilsTest.java
[SONARJAVA-5755](https://sonarsource.atlassian.net/browse/SONARJAVA-5755)
This PR aims to allow deprecated code to be used without having an issue raised whenever the `@Deprecated` annotation is marked with `forRemoval = false`, as that code is not planned for future removal.
As part of the change, a utility method to extract the name of an annotation attribute was extracted from an existing check `SpringComposedRequestMappingCheck` into `ExpressionUtils`. About this I am not 100% sure about the utility method's name, and if the method should also consider more cases than `Tree.Kind.ASSIGNMENT`
[SONARJAVA-5755]: https://sonarsource.atlassian.net/browse/SONARJAVA-5755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5755 FP on S1133 when using forRemoval=false

- java-jsp/pom.xml
[SONARJAVA-5784](https://sonarsource.atlassian.net/browse/SONARJAVA-5784)
This will resolve a dependency risk (CVE-2025-48989).
The risk is a non-issue because no tomcat server is actually being operated, but this will resolve some noise in the dependency risks.
[SONARJAVA-5784]: https://sonarsource.atlassian.net/browse/SONARJAVA-5784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5784 Upgrade tomcat embed dependency

- pom.xml
[SONARJAVA-5786](https://sonarsource.atlassian.net/browse/SONARJAVA-5786)
[SONARJAVA-5786]: https://sonarsource.atlassian.net/browse/SONARJAVA-5786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5786 Bump org.springframework:spring-expression 6.1.21 -> 6.2.11 because of CVE-2025-41249
